### ISSUE TITLE
Add the ability to import bookmarks

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1079]
### Description: 
Add the ability to import bookmarks from Safari on iOS

Bonus
If we can import 
- Tabs
- History 

That would be super

May need to be added to onboarding @jamesmudgett 

User requesting this feature
https://appfigures.com/reviews/42132121512L7860mJzu0C1FgFRMLmH1VA?lang=en

**Comment by cndouglas** [comment]
Because of API restrictions, copying data directly from Safari on iOS to Brave is impossible.

Workaround (requires iCloud account):
1. Sync Safari iOS bookmarks to iCloud
2. Enable iCloud bookmarks in Safari on Mac or Chrome/Firefox on Windows
3. Import bookmarks from the other browser to Brave on computer
4. Sync bookmarks from Brave on computer via Brave Sync
5. Enable Brave Sync on Brave iOS to receive bookmarks

**Comment by anthonypkeane** [comment]
Closing as not possible currently without a workaround
