### ISSUE TITLE
Data from normal tab is carried over into private tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1102]
### Description: 
Data from normal tab is carried over into private tab

### Steps to Reproduce 
  1. Visit jbhifi.com.au
  2. Add a product to shopping cart
  3. Long press on a different product and open in private tab via context menu
  4. Shopping cart in private tab already has the item added in step 2 

**Actual result:** 
Data from normal tab is carried over into private tab

**Expected result:**
No data should be carried over from normal tab to private tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.9.3(19.05.20.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
cc: @danishjafri88 @jumde

**Comment by danishjafri88** [comment]
A regression of #1100. In this case The privacy protection is determined from a global variable. This is used to set Data store on WebView init. The problem is for this particular and similar scenarios(Any way to switch to and fro the privacy mode), The tab is created before the variable is updated.

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14). Verified STR from description.
* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
