### ISSUE TITLE
Address bar revamp

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1134]
- [ ] Embed shields button into URL bar
- [ ] Replace forward button with reload button in portrait mode
- [ ] Move reload button next to back/forward in horizontal mode
- [ ] Show a line separator between shields button and reader mode(if avaialble)
- [ ] Slight color changes

concept
![iPhone XS](https://user-images.githubusercontent.com/6950387/59204486-04eac100-8ba1-11e9-94fd-93188caeeb64.png)

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14) - per discussion this issue is superseded by https://github.com/brave/brave-ios/issues/1207.

![ipadURLbar](https://user-images.githubusercontent.com/28145373/61157342-dde71e00-a4c3-11e9-95d9-a324b9bd4269.png)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`

<img width="587" alt="Screen Shot 2019-07-18 at 10 00 23 AM" src="https://user-images.githubusercontent.com/2602313/61463677-ecf62200-a942-11e9-82b1-dc74cef1dc39.png">

<img width="587" alt="Screen Shot 2019-07-18 at 10 00 12 AM" src="https://user-images.githubusercontent.com/2602313/61463678-ecf62200-a942-11e9-90c0-ec6a815f5074.png">

<img width="1088" alt="Screen Shot 2019-07-18 at 10 02 27 AM" src="https://user-images.githubusercontent.com/2602313/61463816-30e92700-a943-11e9-80d3-81b91364e1a2.png">

<img width="1013" alt="Screen Shot 2019-07-18 at 10 02 12 AM" src="https://user-images.githubusercontent.com/2602313/61463818-30e92700-a943-11e9-95c2-6fdd5717f797.png">

**Comment by kjozwiak** [comment]
@anthonypkeane @EyanGoldman as this is a design/UX issue, can you guys go through this on an `iPhone X`? If you've already been dog fooding and feel comfortable with the new design/functionality, can either of you please add the `QA Pass - iPhone X` label? Thanks!

**Comment by EyanGoldman** [comment]
@kjozwiak looks good for iPhoneX. Label added
