### ISSUE TITLE
User agent on iPad should default to a desktop one.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1290]
### Steps to Reproduce 
  1. Visit a website

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
Hmm.. this seems to have adverse effects (on iPad).
IE: if we change it to `let firefoxUA = UIDevice.current.userInterfaceIdiom == .pad ? UserAgent.desktopUserAgent() : UserAgent.defaultUserAgent()`

It will work.. however, sites like Youtube will disable fullscreen because they are checking for `document.fullscreenEnabled || mozFullScreenEnabled || msFullscreenEnabled || document.webkitFullscreenEnabled ? true : false`

but it always returns false on iOS WebKit (it's a bug because if you do `videoElement.requestFullScreen() || videoElement.webKitRequestFullScreen()`).. it works :(

Is it only for certain sites or all? Is there an option to select the user agent somewhere?

**Comment by iccub** [comment]
there's `customUserAgent` property in `WKWebView`, you can use it even now by tapping on `Share` button in menu and select `request desktop site`. I am not sure how robust this is

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.11.15)`:

<img width="789" alt="Screen Shot 2019-09-11 at 5 58 41 PM" src="https://user-images.githubusercontent.com/2602313/64738661-cf19e900-d4bd-11e9-837f-301bfaff5c61.png">

* Visited the following websites and ensured that the desktop version was being loaded:
   * `youtube.com`, `amazon.com`, `ebay.com`, `coinmarketcap.com`, `facebook.com`

Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.11.14)`:

<img width="776" alt="Screen Shot 2019-09-11 at 6 32 04 PM" src="https://user-images.githubusercontent.com/2602313/64740188-89135400-d4c2-11e9-97d2-ac495ad77e9f.png">

* Visited the following websites and ensured that the desktop version was being loaded:
   * `youtube.com`, `amazon.com`, `ebay.com`, `coinmarketcap.com`, `facebook.com`
