### ISSUE TITLE
navigator.credentials should implement CredentialsContainer

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1296]

**Comment by lgarron** [comment]
FYI, we just switched GitHub to https://github.com/github/webauthn-json/ , with significantly less strict feature detection:

https://github.com/github/webauthn-json/blob/61dfd2b004316f5ebc096dfd2ac0576318bfdee7/src/webauthn.ts#L29

(I believe this bug was originally filed for GitHub WebAuthn compatibility.)

**Comment by jumde** [comment]
right, thanks @lgarron. The authentication workflow is fixed. Registration fails for some reason, will keep you posted.
