### ISSUE TITLE
search data via Google is retained in PB in certain cases

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1395]
### Description: 

In certain cases, search terms are still being displayed in PB via Google even though PB was previously closed.

Firefox retains opened tabs when switching back and forth between PB unless the user closes them. Sounds like we're clearing the tabs in Brave whenever someone closes PB but retain some data because the user didn't close the tab themselves which might be inherited from FX.

### Steps to Reproduce 
  1. using `1.11.1 (19.08.13.17)` open PB (leave everything default)
  2. visit https://www.google.com and search using a few terms
  3. clicking on the search box should display your terms that you just used
  4. switch over to regular browsing (don't close the PB tab that you had opened)
  5. **note: creating a new tab once you're in regular mode will clear the data**
  6. switch back to PB and you'll notice that the tab was cleared (expected)
  7. open a new tab, visit https://www.google.com and tap on the search box
  8. you'll notice that the previous search terms are still being listed
  9. close the PB tab yourself and revisit https://www.google.com in a new tab

You'll notice that the search terms are not cleared.

**Actual result:** 

`Example of the issue occurring #1` --> https://youtu.be/apDitCKBM_Q
`Example of the issue occurring #2` --> https://youtu.be/LEBD1ukZHAk

**Expected result:**

Searches that have been completed via PB should never be retained under PB

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducuble using the above STR. @LaurenWags also reproduced using the above STR.

**Brave Version:** 

* Using `1.11.1 (19.08.13.17)`

**Device details:** 

* `iPhone 6s+` running `iOS 12.4` --> Reproduced by @kjozwiak 
* `iPad 5th Gen` running `iOS 12.3.1` --> Reproduced by @LaurenWags

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)?  Comment about Firefox mentioned above via the summary.

**Comment by Brandon-T** [comment]
NOTE:

To reproduce this bug was difficult for me. I actually had to follow the exact words in the steps posted above.

You **MUST NOT** create a new "**normal tab**" when you switch from PB to Normal.

IE:

PB
Search Google
Press Mode Switcher
See Tab Switcher with Normal Tabs (collection view)
Switch back to PB immediately (do not open a normal tab otherwise the tab switcher closes and the PB clears all data)

If you switch from PB to tab switcher and open a normal tab, it will close the tab switcher and all PB data will be lost. If you never exit the tab switcher and go straight back to PB, the history is there. 

Seems like we only clear the history when the tab-switcher is closed and the user fully switches to normal mode. We aren't clearing it for the in-between state (IE: tab-switcher state).

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.07.08)
* Verified steps from https://github.com/brave/brave-ios/issues/1395#issuecomment-521409390
* Verified closing and opening new private tabs via tab manager didn't retain any search history
[privatesearch_1395.zip](https://github.com/brave/brave-ios/files/3596045/privatesearch_1395.zip)

Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.11.14)`:

* Verified test cases from https://github.com/brave/brave-ios/issues/1395#issuecomment-521409390 & https://github.com/brave/brave-ios/issues/1395#issue-480856266
* Verified that closing PB didn't retain the following:
   * History, Passwords, Sessions, Cookies, SE History

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified steps from https://github.com/brave/brave-ios/issues/1395#issuecomment-521409390
* Verified closing and opening new private tabs via tab manager didn't retain any search history
