### ISSUE TITLE
adding "find text in" support for PDF documents

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1508]
### Description:

We should look into adding `find text in` support for PDF documents. The current `find text in` features under the omnibox (URL bar) or the `Share with..` menu are not working within PDF documents.

Originally requested via https://twitter.com/jeb_1989/status/1170413266251788288.

### Steps to Reproduce

**`Case #1`**

  1. open `1.11.4 (19.08.29.21)` (latest release)
  2. open https://ddot.dc.gov/sites/default/files/dc/sites/ddot/publication/attachments/ddot_public_realm_design_manual_2011.pdf in a new tab
  3. `find text` using either `On this page` via the omnibox (URL bar) or `Find in Page` via the `Share with..` menu

**`Case #2`**

  1. download/install `1.11.4 (19.08.29.21)`
  2. open https://bitcoin.org/bitcoin.pdf in a new tab
  3. `find text` using either `On this page` via the omnibox (URL bar) or `Find in Page` via the `Share with..` menu

**Actual result:** 

Example of the issue occurring: https://twitter.com/jeb_1989/status/1170445149794689025

![IMG_D2F8A6E6830C-1](https://user-images.githubusercontent.com/2602313/64483875-27a86800-d1d8-11e9-93dd-a2406f88a7bf.jpeg)

**Expected result:**

We should add `find text in` support for PDF documents.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.11.4 (19.08.29.21)` - Reproduced (no support)
* `1.11.3 (19.08.16.20)` - Reproduced (no support)
* `1.11.1 (19.08.13.17)` - Reproduced (no support)

**Device details:** 

* `iPad Mini 4 using iOS 12.4.1`
* Community member reproduced the issue with an iPhone as well.

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes, works correctly under `Safari`. Seems like both Firefox & Chrome don't support `find text in` via PDF's.

### Additional Information

CCing @anthonypkeane @jhreis @srirambv

**Comment by Brandon-T** [comment]
In order to add this feature (which doesn't exist in Firefox-iOS or Chrome-iOS), we have three choices:

1. We can use Private API: `- (void)_findString:(NSString *)string options:(_WKFindOptions)options maxCount:(NSUInteger)maxCount` To highlight the text and also to unhighlight it (tested and it works). However, it doesn’t let you go to the “next” text. It’ll just highlight all.

2. We could use a PDF library in Javascript and inject the entire thing into a page to allow highlighting.

3. We could add a button somewhere to download or save the PDF (into our existing downloads manager) and have a custom view that uses PDFKit to highlight the text. I think this is the best option as you can allow the user to view the PDF with iBooks or built-in PDF viewer, etc..

Currently, this feature only works in Safari.

**Comment by hennrynusasatria** [comment]
Hi @Brandon-T 

Do you have any update on this topic? Can you explore Option 2 above (use a PDF library in Javascript)?

Thank you.

**Comment by hennrynusasatria** [comment]
Hi @Brandon-T @iccub @anthonypkeane 

Please check:

https://github.com/mozilla-mobile/firefox-ios/issues/7116

It is mentioned that the performance is terrible on using JS for "Find in Page" function, perhaps a better plan is to implement a function on WKWebView for the "Find in Page" function.

Thank you.

**Comment by iccub** [comment]
will be fixed in https://github.com/brave/brave-ios/issues/3312
