### ISSUE TITLE
Tips flow doesn't have smooth transition between screens

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1692]
### Description: 
Tips flow doesn't have a smooth transition between screens

### Steps to Reproduce 
  1. Enable rewards
  2. Visit a site and tip
  3. The tips message screen doesn't have a smooth transition

**Actual result:** 
![RPReplay_Final1571171819](https://user-images.githubusercontent.com/17010094/66868030-8cd74200-ef6a-11e9-86f2-67f1e2703a1f.gif)

**Expected result:**
Have a smooth transition between screens

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13

**Device details:** 
iPhone Xr

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @jenn-rhim @jamesmudgett @kylehickinson @Brandon-T

**Comment by kylehickinson** [comment]
@srirambv Sorry, which part doesn't have a smooth transition? I'm not sure what you mean by the GIF

**Comment by srirambv** [comment]
@kylehickinson  when you select the tip value and click on send tip, the success message screen just pops up and barely has any fade-in transition or fade-out transition. Dismisses the message instantly

**Comment by kylehickinson** [comment]
@srirambv There is animation, it just happens a little quicker _and_ its happening at the same time as dismissing the tipping screen below which is probably causing some feeling of it dismissing instantly.

You can even see it in frame 88 of the gif:
![66868030-8cd74200-ef6a-11e9-86f2-67f1e2703a1f-88 (dragged)](https://user-images.githubusercontent.com/529104/69282001-4acb9c80-0bb7-11ea-8793-31c356fa7385.png)

For reference, the background animation has **the same** speed on both presentation & dismissal. The contents (favicon, labels, etc.) have a 0.4s presentation animation and a 0.35s dismissal animation. These are fractions of a second but I think it maybe just perceived as quicker because things are going off the screen instead of coming onto them (therefore having no feedback of stopping on screen).  I could slow things down a tad, but I don't see a big reason to as dismissal animation should usually be faster anyways (lets user take control quicker)

**Comment by kylehickinson** [comment]
@srirambv Is this still a problem based on my previous comments above, or can this be closed?
