### ISSUE TITLE
Set up SwiftLint

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#172]
- [ ] decide which rules to use, create/modify existing `.swiftlint.yml` file
- [ ] add a buildscript to make it run on builds
- [ ] Update the setup/bootstrap script to ensure swiftlint is installed/install it otherwise

**Comment by kylehickinson** [comment]
- [ ] Update the setup/bootstrap script to ensure swiftlint is installed/install it otherwise

**Comment by kylehickinson** [comment]
After updating `.swiftlint.yaml` to use `Xcode` reporting and adding a build phase for checking what the damage was:

`Done linting! Found 451 violations, 23 serious in 337 files.`

So that amounts to 23 errors, and 428 warnings generated from SwiftLint.  The errors can be dealt with fairly easily. Most of these are due to code added/ported from 1.6 while not running SwiftLint.

Running `swiftlint autocorrect` fixes a significant chunk of these violations:

`Done linting! Found 280 violations, 4 serious in 337 files.`

It also looks like a few of the rules name's have changed or been removed.

```
'variable_name' rule has been renamed to 'identifier_name' and will be completely removed in a future release.
configuration error: 'valid_docs' is not a valid rule identifier
```

This research work has been pushed to the `swiftlint` branch
