### ISSUE TITLE
Wallet is created but onboarding is relaunched if app is removed from memory during onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1753]
### Description: 
Wallet is created but onboarding is relaunched if app is removed from memory during onboarding

### Steps to Reproduce 
  1. Clean install 1.13
  2. Continue with onboarding
  3. Tap on `Turn on` to enable rewards
  4. Remove app from memory while the loading spinner is being shown
  5. Relaunch app, onboarding shows up again(expected as it wasnt complete in step 4)
  6. Shows to enable rewards again
  7. Tap on Skip and open rewards panel, wallet is already created

**Actual result:** 
![onboarding](https://user-images.githubusercontent.com/17010094/67299375-986ebf80-f4ba-11e9-86fc-c3e20840b934.gif)

**Expected result:**
Even if onboarding is relaunched it should not ask to enable rewards again

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.21.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Will be fixed post 1.13 release

**Comment by Brandon-T** [comment]
There was a comment left in the code quite a while back since "Shields" that if onboarding isn't fully complete, to NOT mark the flow as complete (expected).. IE: It doesn't keep track of progress or where you left off.

So my question for a fix for this is: Are we just going to fix it for the "Rewards wallet creation" part and still show the rest of onboarding from the beginning? OR, do we continue the onboarding where the user left off OR other?

In the case of this ticket, the server call to create a wallet was already completed but I don't get notified of that since the app got killed. The next time you launch, you have a wallet yes, but onboarding was still incomplete. So what should be the behaviour here?

**Comment by kylehickinson** [comment]
Closed because there is no more spinner

**Comment by srirambv** [comment]
@kylehickinson  this is still reproducible on the new beta. Even after you turn on ads without completing the onboarding it still asks to go over the entire onboarding and asks to turn on rewards again even though its enabled already

**Comment by kylehickinson** [comment]
@srirambv I think this is expected (force quitting during onboarding doesn't "complete" the onboarding step, therefore you are shown it again) but maybe @Brandon-T can confirm

**Comment by srirambv** [comment]
Moving out of milestone as there is no fix on this. Follow up issue #2010 logged
