### ISSUE TITLE
Some people are writing review that they can’t go back to original page from full screen mode in YouTube

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1959]
### Description: 

Some people are writing review that they can’t go back to original page from full screen mode in YouTube

Internal chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1573719143286100

**Comment by Brandon-T** [comment]
I discovered the issue.

WKWebView's `fullscreenEnabled` is now behaving differently in new versions of iOS 13..
If using a Mobile User Agent, this value must ALWAYS return `false`. If it returns true at all, it will dismiss the video, but the div tag that was fullscreen will not go back to normal.

However, it must always return `true` for Desktop User Agent otherwise fullscreen on iPad will never work.

It's due to the way Youtube handles fullscreen.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.27.14)
* Verified able to navigate back to the original page after exiting from fullscreen
--------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.27.14)
* Verified able to navigate back to the original page after exiting from fullscreen
--------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.27.14)
* Verified able to navigate back to the original page after exiting from fullscreen
--------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.27.14)
* Verified able to navigate back to the original page after exiting from fullscreen
--------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.27.14)
* Verified able to navigate back to the original page after exiting from fullscreen
