### ISSUE TITLE
Session is retained when PBO is setting is toggled [Follow up to 1987]

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2041]
### Description: 
Session is retained when PBO is setting is toggled [Follow up to #1987]

### Steps to Reproduce 
  1. Login to a site in a normal tab
  2. Enable PBO from settings, do not click on done
  3. Turn off PBO, switches to a new normal tab
  4. Visit the site from step 1, the session is restored

**Actual result:** 
![sessions_ios](https://user-images.githubusercontent.com/17010094/69727476-9f5ba400-10f0-11ea-928f-6789194e625e.gif)

**Expected result:**
Should clear session when the user hits ok on the alert.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.27.14)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Bump to 1.20

**Comment by GeetaSarvadnya** [comment]
Settings > Clear Private Data, and clear all. Check only the history is cleared and favourites are retained

1. Clean profile 1.19 (20.7.21.9)
2. Open a few sites in NTP's
3. Open Hamburger menu->History and verify that history is stored for the opened sites
4. Open settings->`Clear Private Data` and clear all.
5. Navigate back to Hamburger menu->`History` ----> history is not deleted since tab is reloading and storing the history again

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.2.20)
- Verified test plan from issue description
----------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.2.20)
- Verified test plan from issue description
----------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.2.20)
- Verified test plan from issue description
