### ISSUE TITLE
Disable downloading of files into the Downloads folder

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#205]
Disable the UI for downloading of files into the Downloads folder. This feature will be re-enabled in a future version when privacy concerns have been addressed in #195

**Comment by kylehickinson** [comment]
This code is actually tied to #185 (this is another instance of their `PhotonActionSheet`), therefore a future revert of this PR fix would not be clean down the road (`PhotonActionSheet` will not exist anymore).

Also the `DownloadsPanel` UI hasn't been in use since we implemented our own `FavoritesViewController` new tab, so a revert would only bring back the download handling logic.

![simulator screen shot - iphone 8 - 2018-09-11 at 12 16 29](https://user-images.githubusercontent.com/529104/45373143-aa461980-b5bc-11e8-962d-316858707217.png)

**Proposal**: Remove all current & legacy download UI, but keep all the download business logic in-tact, and later when we want to add this feature we will just need to create our own custom UI to integrate with.
