### ISSUE TITLE
Switching to external without permission [Follow up to #551] 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2119]
### Description: 
Switching to external without permission [Follow up to #551] 

### Steps to Reproduce 
  1. Install blick app from app store
  2. Upgrade to 1.14.1 via appstore
  3. Search for blick.ch and click on search result, automatically opens the installed app

**Actual result:** 
No user permission asked before switching to external app

**Expected result:**
Should have asked persmission which was the fix on #551 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.1

**Device details:** 
iPhone and iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Reported on community https://community.brave.com/t/ask-before-open-app-instead-of-website/97970 and reproduced on iPhone
Adding same security labels as #551 
cc: @jumde

**Comment by Brandon-T** [comment]
This one may involve Private-APIs in order to fix. I researched it many many times. There used to be a solution to this with `decidePolicyForNavigation` but it no longer works after iOS 10.

**Problem:** Universal Links (Deep-Linking) via `apple-app-site-association.json`.

If you go to `google` or any search engine, and you type in a URL of the search result belongs to some app installed on your phone, the moment you tap on the link, it will open in WKWebView and therefore open the app automatically. It does NOT have a callback for this and it does not hit `decidePolicyForNavigation` either.

Therefore, the only way to fix this is to use private-apis in order to determine if the WebView is going to open a deep-link.


Option: 2, pull down the deep-link config for EVERY single request the WKWebView makes. IE: If we visit reddit.com, we'd have to pull down: `https://www.reddit.com/apple-app-site-association` to and parse it first..

Both of these options are not worth it. Option 1 can get us rejected from the store by Apple for use of Private-APIs. Option 2 will involve a LOT of parsing (especially for websites like facebook).. Option 2 will mean that every site we visit will be slower as we have to parse the config if it exists..

**Comment by Brandon-T** [comment]
cc: @jhreis ^

Not sure what we should do if anything.

**Comment by jumde** [comment]
@Brandon-T @srirambv @jhreis - I don't think we can do anything right away. May be we can reach out to our friends at Apple and see if they are willing to expose these APIs?

**Comment by kylehickinson** [comment]
@jumde @jhreis 

FYI the private API needed to accomplish this: https://stackoverflow.com/questions/38450586/prevent-universal-links-from-opening-in-wkwebview-uiwebview

(https://github.com/WebKit/webkit/blob/371119ce88f4e1e3c7945e7860fbb3a4d5fc7402/Source/WebKit/UIProcess/API/Cocoa/WKNavigationDelegatePrivate.h#L63)

We should however also ask Apple to make this a public API. (either filing our own rdar or duping an existing one)

**Comment by alanhoyle** [comment]
Chrome for iOS suppresses external app loading if in a private browser window.  I feel like it should be fine to load external apps in regular windows, but in private windows, it should be suppressed.  

I started a discussion about this here:  

https://community.brave.com/t/suppress-app-loading-in-private-browser-on-ios/97382

**Comment by jamesmudgett** [comment]
Focus uses method mentioned above https://github.com/mozilla-mobile/focus-ios/blob/464b65ff9e3568ae3dc2f2d95184e33625db202b/Blockzilla/Modules/WebView/WebViewController.swift#L369

**Comment by kylehickinson** [comment]
@srirambv The solution to this problem cannot be solved by adding a permission prompt (as we do with known schemes such as maps/tel/etc.) because we do not know that Brave will launch another app when a user taps a link. Therefore the original issue has been solved a different way as seen in the PR: https://github.com/brave/brave-ios/pull/3329

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.24 (21.3.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3329

<details>
<summary>Normal tab</summary>

https://user-images.githubusercontent.com/17010094/112590143-3e360480-8dfa-11eb-9a1b-219047ed418c.mp4

</details>
<details>
<summary>Private tab</summary>

https://user-images.githubusercontent.com/17010094/112590661-1c894d00-8dfb-11eb-8a50-84b6ccba1bfe.MP4

</details>

--------------
Verification passed on iPhone XR with iOS 13.5 running 1.24 (21.3.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3329

<details>
<summary>Normal tab</summary>

https://user-images.githubusercontent.com/17010094/112592004-27dd7800-8dfd-11eb-9794-d90264272c02.MP4

</details>
<details>
<summary>Private tab</summary>

https://user-images.githubusercontent.com/17010094/112592258-9b7f8500-8dfd-11eb-9258-ba17bcd5210a.MP4

</details>

--------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.24 (21.3.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3329

<details>
<summary>Normal tab</summary>

https://user-images.githubusercontent.com/17010094/112592680-43954e00-8dfe-11eb-98f4-7d309b992bac.MP4

</details>
<details>
<summary>Private tab</summary>

https://user-images.githubusercontent.com/17010094/112592727-5d369580-8dfe-11eb-86fa-3a6a42259cdd.MP4

</details>
