### ISSUE TITLE
Second NTP notification showing if enabling Rewards via NTP

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2260]
### Steps to Reproduce 
  1. Fresh launch, skip onboarding
  2. Open sponsored tab, wait for banner
  3. Tap on `turn rewards` on the banner, wait until wallet is created
  4. Open new tabs until another sponsored image is shown, wait 1.5 sec

**Actual result:** 
Another NTP notification will show `you are getting paid for this image...`

**Expected result:**
Shouldn't show, the notification should show only once, exception is when you reset ads or rewards via Rewards settings panel

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by GeetaSarvadnya** [comment]
This issue is happening in a few more upgrade scenarios:

Scenario1:
1. Clean profile 1.13
2. Skip the onboarding flow
3. Upgrade to 1.14.3
4. Open a 1st SNTP `you are getting paid for this image...` notification is shown on 1st SNTP
5. Enable rewards from 1st SNTP 
6. Open a 2nd SNTP `you are getting paid for this image...` notification is shown for 2nd SNTP also

Scenarios2:
1. Clean profile 1.13
2. Enable rewards through the onboarding flow
3. Turn off Ads, AC, and Brave rewards switch one by one
4. Upgrade to 1.14.3
5. Open 1st SNTP, sponsored image is shown with `you are getting paid for this image...` notification
6. Enable rewards from the notification modal which is shown in step 5
7. Open 2nd SNTP, sponsored image is shown with notification `you are getting paid for this image...`

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12 running 1.14.3 (20.1.29.20)
   - Verified STR from description. Confirmed notification does show when Ads/Rewards status is changed as noted in description.
   - Verified scenarios from https://github.com/brave/brave-ios/issues/2260#issuecomment-579754350 did not show the second message.

Verification passed on iPad Mini with iOS 13 running 1.14.3 (20.1.29.20)
   - Verified STR from description. Confirmed notification does show when Ads/Rewards status is changed as noted in description.
   - Verified scenarios from https://github.com/brave/brave-ios/issues/2260#issuecomment-579754350 did not show the second message.

Verification passed on 1.14.3(20.01.29.20) on Production on iPhone SE (iOS 12.4)
   - Verified STR from description. Confirmed notification does show when Ads/Rewards status is changed as noted in description.
   - Verified scenarios from https://github.com/brave/brave-ios/issues/2260#issuecomment-579754350 did not show the second message.

Verification **PASSED** on `iPhone 11` using `iOS 13.3` running `1.14.3(20.01.29.20`):

* Reproduced the original scenario via https://github.com/brave/brave-ios/issues/2260#issue-556730439 using `1.14.3 (20.01.28.18)`
* Reproduced the original scenarios via https://github.com/brave/brave-ios/issues/2260#issuecomment-579754350 using `1.14.3 (20.01.28.18)`
* Verified STR from description. Confirmed notification does show when Ads/Rewards status is changed as noted in description.
* Verified scenarios from https://github.com/brave/brave-ios/issues/2260#issuecomment-579754350 did not show the second message.

Verification **PASSED** on `iPhone 8` using `iOS 13.3` running `1.14.3(20.01.29.20`):
* Verified STR from description. Confirmed notification does show when Ads/Rewards status is changed as noted in description.
* Verified scenarios from https://github.com/brave/brave-ios/issues/2260#issuecomment-579754350 did not show the second message.
