### ISSUE TITLE
Launching with a new tab should bring up keyboard

### ISSUE THREAD

**Issue by petercockroach** [brave/brave-ios#2429]
- Long press on the icon on home screen
- Select New Tab or New Private Tab
- App opens with the new tab, but the user needs to tap the search bar to bring up the keyboard. 
- In Safari, this bar is automatically targeted so users can start typing immediately.

**Comment by iccub** [comment]
You can enable it in settings.

Settings -> New Tab -> Open keyboard automatically.

Can you check if it works for you?

**Comment by petercockroach** [comment]
Thanks. That does work. Should launching from home screen be special-cased though?

**Comment by iccub** [comment]
@petercockroach I see your point, 
we have and plan to have bunch of features on new tab page like customized homepage or widgets that require a lot of screen real estate, that's why we introduced it as an option for users

closing this ticket, but feel free to comment on it or bring this topic to our community forums
