### ISSUE TITLE
Implement state level ads delivery

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#2636]
https://github.com/brave/brave-browser/issues/9200

**Comment by srirambv** [comment]
@tmancey  can you please add iOS specific test plan for this issue?

**Comment by tmancey** [comment]
@srirambv iOS works same as desktop. For United States state level targeting will appear in the Ads UI. Ads for the United States which are part of a subdivision (i.e. FL, NY etc.) should only be show if you are in those regions. Thanks

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPad Air (3rd Gen)` on `iOS 14.0.1` using `1.21 (20.11.2.20)`

Settings | Received Ad | Total Count
---------|--------------|-------------
<img width="374" alt="Screen Shot 2020-11-05 at 11 22 57 PM" src="https://user-images.githubusercontent.com/2602313/98325907-4b2a9680-1fc6-11eb-8657-ce2257f3a0af.png"> | ![IMG_0167](https://user-images.githubusercontent.com/2602313/98318476-0ea26f00-1fb5-11eb-860a-999c0c7357e2.PNG) | <img width="371" alt="Screen Shot 2020-11-05 at 11 23 07 PM" src="https://user-images.githubusercontent.com/2602313/98325918-5382d180-1fc6-11eb-8578-19bddec00127.png">


* Verification **PASSED** on `iPhone 11` on `iOS 14.1` using `1.21 (20.11.2.20)`

Settings | Received Ad | Total Count
---------|--------------|-------------
<img width="374" alt="Screen Shot 2020-11-05 at 11 22 57 PM" src="https://user-images.githubusercontent.com/2602313/98325941-639ab100-1fc6-11eb-8219-3043ae145ee5.png"> | ![9EC3109F-4513-4642-B476-00466691150F](https://user-images.githubusercontent.com/2602313/98318555-3560a580-1fb5-11eb-807a-1afea44da3c1.PNG) | <img width="371" alt="Screen Shot 2020-11-05 at 11 23 07 PM" src="https://user-images.githubusercontent.com/2602313/98325951-69909200-1fc6-11eb-85e6-bd59cda31f81.png">

* Verification **PASSED** on `iPad Mini 4` on `iOS 13.7` using `1.21 (20.11.2.20)`

Settings | Received Ad | Total Count
---------|--------------|-------------
<img width="374" alt="Screen Shot 2020-11-05 at 11 22 57 PM" src="https://user-images.githubusercontent.com/2602313/98325989-84fb9d00-1fc6-11eb-8afd-eb9254a442f5.png"> | ![IMG_0358](https://user-images.githubusercontent.com/2602313/98326008-95ac1300-1fc6-11eb-9fa9-c71c5aa9510f.PNG) | <img width="371" alt="Screen Shot 2020-11-05 at 11 23 07 PM" src="https://user-images.githubusercontent.com/2602313/98326022-9e044e00-1fc6-11eb-8823-d42c53ebb7ae.png">


Prerequisites for the below cases:

* iOS region set to `US`
* connected to `US` VPN and selecting `IL`

**`STR/Cases used`**

* ensured that `IL` is automatically selected via `State level ad targeting` (due to being connected to IL VPN)
* ensured that a state level ad is delivered without any issues and appears under `Ad notifications received this month`
* double checked with @tmancey and ensured
