### ISSUE TITLE
implement twitter tipping

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2729]
### Description: 
When on a verified twitter publisher the BAT logo displays the verified icon, but the panel just shows `mobile.twitter.com` as the publisher. Also, the tip button does not work: https://github.com/brave/brave-ios/issues/2689

### Steps to Reproduce 
  1. Have rewards enabled
  2. Visit a verified twitter publisher (ex. twitter.com/brianbondy)
  3. Open panel

**Actual result:** 
BAT logo shows verified icon, but panel doesn't display 'Brian Bondy on Twitter' (or similar)
![IMG_5C8C0ECB16A9-1](https://user-images.githubusercontent.com/28145373/88100588-b90f9700-cb6a-11ea-97e9-e9796e2b83a0.jpeg)

**Expected result:**
correct publisher info on the panel if we're going to show the verified icon

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.18.1 (20.07.06.15) and 1.19 (20.07.21.11)

**Device details:** 
all

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc @brave/legacy_qa

**Comment by Brave-Matt** [comment]
Another user reporting verified sites not appearing as verified on iOS:
https://community.brave.com/t/ios-twitter-and-youtube-verified-tips-not-working-on-mobile/169700/2

**Comment by VivaLaRobo** [comment]
This issue seems to happen on any of the Brave Creator options, not just Twitter. I have YouTube, Twitter, GitHub, and Reddit all synced and verified with my account, but none of them say verified when I visit them on Brave on my iPhone. They all say verified on my Desktop and Laptop but not my iPhone. 

Technically, right now there is no way for me to transfer BAT on Brave for iOS to my UpHold account, it is just stuck on my phone. Other people’s Twitter/YouTube accounts appear verified, but mine do not even though they have in the past and have been verified for months. I’ve tried deleting the accounts and re-adding them, then waiting 72+ hours and still they’re not verified.

**Comment by VivaLaRobo** [comment]
11 days and no updates? Is this being worked on? None of my accounts are working and all of my BAT on mobile is just sitting not able to be moved...

**Comment by VivaLaRobo** [comment]
An update, I downloaded the iOS Brave Beta through TestFlight and it shows my Twitter account as verified. The regular Brave app still does not show it as verified. Any idea why the difference?

**Comment by iccub** [comment]
yes @VivaLaRobo, the beta app contains few improvements to publishers database, which means more accounts and websites should show as verified

**Comment by VivaLaRobo** [comment]
@iccub thanks, but this doesn’t solve why the regular Brave iOS app shows my accounts as unverified. I have BAT on the regular Brave app that I want to send to myself. I can’t do that at all with the regular app at the moment...

**Comment by kylehickinson** [comment]
Closing since we no longer have tipping available in Brave iOS
