### ISSUE TITLE
Add Support for PDF File Sharing

### ISSUE THREAD

**Issue by hennrynusasatria** [brave/brave-ios#2827]
**Problem Description:**
Add support for PDF file sharing

**Feature Overview:**
Add support for PDF file sharing like Safari

![image](https://user-images.githubusercontent.com/69782842/90598124-a39a9500-e21c-11ea-8453-bcc69ae91270.png)

**Brave iOS currently does not have PDF file sharing like Safari as above.**

![image](https://user-images.githubusercontent.com/69782842/90598363-13108480-e21d-11ea-89b1-5a0ed1eeaf97.png)

**Please add PDF file sharing like Safari as above.**

Thank you.

**Comment by hennrynusasatria** [comment]
Hi All,

Please also take reference from Firefox iOS as follow: https://github.com/mozilla-mobile/firefox-ios/issues/6019

Thank you.

**Comment by kylehickinson** [comment]
Hi @hennrynusasatria, we currently have a PDF export feature planned for iOS 14 which is tracked here #2807 so I will close this ticket as a duplicate.

Unfortunately it is not possible to implement it the way you describe because Apple does not expose this as an API for us to use, but we if things ever change in the future we can always re-evaluate :)
