### ISSUE TITLE
Update Startpage SE

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3002]
See https://github.com/brave/brave-browser/issues/12257

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.22(20.11.19.10)
**Clean Install**
- Verified onboarding shows `Startpage` instead of `StatPage`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99798246-99907700-2b28-11eb-9122-d34b52a891b4.png>

- Verified selecting `Startpage` during onboarding sets it as default for both normal and private tabs
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99798321-baf16300-2b28-11eb-959f-94bc5e84f939.png>

- Verified setting `Startpage` as default during onboarding and performing a search appends `&segment=startpage.brave` at the end of query parameter
- Verified attribution is appended for both normal and private tabs when set to default

Normal Tab | Private Tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/99798258-9eedc180-2b28-11eb-88e5-c9661f275e97.png) | ![image](https://user-images.githubusercontent.com/17010094/99798269-a2814880-2b28-11eb-9d18-01729b296c7e.png)

- Verified manually visiting `https://startpage.com/` and performing a search doesn't add any attribution at the end of URL instead just uses `https://startpage.com/sp/search`

**Upgrade Install**
- Verified setting `StartPage` as default in 1.21 and upgrading to 1.22 updates the search engine text to `Startpage`
- Verified performing a search on 1.21 appends `pl=opensearch` in search URL, upgrading to 1.22 retains `pl=opensearch` for existing searches
- Verified new searches done is appending attribution at the end of URL
- Logged follow up #3056 
-----------------------
Verification passed on iPhone 7+ with iOS 13.5 running 1.22(20.11.20.16)
**Clean Install**
- Verified onboarding shows `Startpage` instead of `StatPage`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99938095-068d5200-2d5f-11eb-8dd5-8f6da4a71c82.png>

- Verified selecting `Startpage` during onboarding sets it as default for both normal and private tabs
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99938111-0e4cf680-2d5f-11eb-94f6-45a0d5ca7d12.png>

- Verified setting `Startpage` as default during onboarding and performing a search appends `&segment=startpage.brave` at the end of query parameter
- Verified attribution is appended for both normal and private tabs when set to default

Normal Tab | Private Tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/99938136-186ef500-2d5f-11eb-8f7f-e1892c2b2a62.png) | ![image](https://user-images.githubusercontent.com/17010094/99938153-1d33a900-2d5f-11eb-9efe-19a857928869.png)


- Verified manually visiting `https://startpage.com/` and performing a search doesn't add any attribution at the end of URL instead just uses `https://startpage.com/sp/search`

**Upgrade Install**
- Verified setting `StartPage` as default in 1.21 and upgrading to 1.22 updates the search engine text to `Startpage`
- Verified performing a search on 1.21 appends `pl=opensearch` in search URL, upgrading to 1.22 retains `pl=opensearch` for existing searches
- Verified new searches done is appending attribution at the end of URL
-------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.22(20.11.20.16)
**Clean Install**
- Verified onboarding shows `Startpage` instead of `StatPage`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99939225-7e5c7c00-2d61-11eb-8fd1-19a204228012.png>

- Verified selecting `Startpage` during onboarding sets it as default for both normal and private tabs
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99939201-6e449c80-2d61-11eb-80cc-2cfeb8f104c4.png>

- Verified setting `Startpage` as default during onboarding and performing a search appends `&segment=startpage.brave` at the end of query parameter
- Verified attribution is appended for both normal and private tabs when set to default

Normal Tab | Private Tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/99939187-6684f800-2d61-11eb-9bb8-14f2ca32ed03.png) | ![image](https://user-images.githubusercontent.com/17010094/99939168-6127ad80-2d61-11eb-894c-c9b6201a4b4d.png)

- Verified manually visiting `https://startpage.com/` and performing a search doesn't add any attribution at the end of URL instead just uses `https://startpage.com/sp/search`

**Upgrade Install**
- Verified setting `StartPage` as default in 1.21 and upgrading to 1.22 updates the search engine text to `Startpage`
- Verified performing a search on 1.21 appends `pl=opensearch` in search URL, upgrading to 1.22 retains `pl=opensearch` for existing searches
- Verified new searches done is appending attribution at the end of URL
