### ISSUE TITLE
[Sync v2] - Follow up of #2996 Crash when moving bookmark to just deleted folder

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#3011]
### Description: 
[Sync v2] - Follow up of #2996 Crash when moving bookmark to just deleted folder

### Steps to Reproduce 
DeviceA : iPhone 8
DeviceB: Windows 10 x64

1. Clean install on DeviceA and DeviceB
2. Establish sync chain between DeviceA and DeviceB
3. DeviceA: Add bookmark folder FA1
4. DeviceA: Add bookmark A1
5. Wait for sync update
6. DeviceB: Delete FA1 and at the same time on DeviceA: Move A1 to FA1
7. Wait for sync update

**Actual result:** 
Crash

Please find the recorded file for reference
https://drive.google.com/file/d/1m5aRUydiZuHh5CuWpDBI1_7D2djWpWNR/view

**Expected result:**
No Crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Always
**Brave Version:** 

1.21(20.11.02.20)
**Device details:** 

iPhone 8 - iOS 13.3.1
**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc @brave/legacy_qa @jsecretan @iccub @Brandon-T

**Comment by btlechowski** [comment]
Reproduced on 1.21(20.11.2.20) on iPhone SE

**Comment by Brandon-T** [comment]
Related issue: https://github.com/brave/brave-browser/issues/12530

Same exact problem. Only difference is that instead of just waiting for it to delete, you've visited the deleted/zombie folder. This is technically an invalid sync state on ALL platforms..

I have mitigated the crash by taking the user to the root bookmarks folder as there is not much else I can do since the folder was deleted AND we are purposely breaking sync by doing so.

We will create a build so you can verify this is fixed.

**Comment by iccub** [comment]
Please retest in `Dev 1.21 (20.11.6.12)`

**Comment by btlechowski** [comment]
Verification passed on 1.21(20.11.06.12) on iPhone SE (iOS 12.4). No crash observed.

--------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.11.6.12)
- Verified no crash when sync changes
-------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.11.6.12)
- Verified no crash when sync changes
