### ISSUE TITLE
HTTP icon should be a warning symbol instead of lock

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ios#3098]
currently on iOS, brave shows a red lock icon if a site is loaded over insecure HTTP. since it's a lock shape, colorblind users may think that it's a secure site when it actually isn't.

it should be changed to a warning icon like on desktop

**Comment by Robodog63** [comment]
Thank you very muchSent using the mobile mail appOn 12/2/20 at 1:50 PM, Kyle Hickinson wrote:
                
            
            
                
                    From: "Kyle Hickinson" <notifications@github.com>Date: December 2, 2020To: "brave/brave-ios" <brave-ios@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Subject: Re: [brave/brave-ios] HTTP icon should be a warning symbol instead of lock (#3098)
                
                
Closed #3098 via #3102.TRD

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/brave/brave-ios/issues/3098#event-4064534518",
"url": "https://github.com/brave/brave-ios/issues/3098#event-4064534518",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.23(21.2.10.18)
- Verified test plan from #3102

HTTP | HTTPS
-- | --
![image](https://user-images.githubusercontent.com/17010094/107610936-b7a6d880-6c3a-11eb-85f4-3f67d045779c.png) | ![image](https://user-images.githubusercontent.com/17010094/107610940-bbd2f600-6c3a-11eb-8c45-d516dcf847e3.png)

-------
Verification passed on iPhone XR with iOS 13.5running 1.23(21.2.10.18)
- Verified test plan from #3102

HTTP | HTTPS
-- | --
![image](https://user-images.githubusercontent.com/17010094/107611049-02285500-6c3b-11eb-87bd-ac939c5de10f.png) | ![image](https://user-images.githubusercontent.com/17010094/107611053-05bbdc00-6c3b-11eb-8807-473ed47daef4.png)

-------
Verification passed on iPad Pro with iOS 12.4.1running 1.23(21.2.10.18)
- Verified test plan from #3102

HTTP | HTTPS
-- | --
![image](https://user-images.githubusercontent.com/17010094/107611063-0a809000-6c3b-11eb-815c-85419f432508.png) | ![image](https://user-images.githubusercontent.com/17010094/107611069-0e141700-6c3b-11eb-986f-f34ec56a98dd.png)
