### ISSUE TITLE
changing "we somehow goofed" string

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3103]
### Description: 

We'll need to change the current `or we somehow goofed.` message that appears when an error occurred when doing a transfer.

### Steps to Reproduce

**`Prerequisite:`** ensure that you're in a state where you can transfer BAT using the transfer feature
 
  1. using the `scan` feature, scan an invalid QR code and you'll see the error message

**Actual result:** 

![IMG_03528D1A3051-1](https://user-images.githubusercontent.com/2602313/100923407-20403f00-34ad-11eb-96c9-8734b8cdfb54.jpeg)

**Expected result:**

![image](https://user-images.githubusercontent.com/2602313/100923427-26ceb680-34ad-11eb-9a2d-71490d931be7.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Reproducible 100% of the time using the above STR.

**Brave Version:** 

* Reproduced using `1.22 (20.11.25.21)`

**Device details:** 

* Affects all devices and iOS versions.

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.2` using `1.22 (20.12.2.0)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.0.1` using `1.22 (20.12.2.0)`
* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.22 (20.12.2.0)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.22 (20.12.2.1)`

**`iPhone 11`** | **`iPad Air (3rd Gen)`** | **` iPhone 6s+`** | **` iPad Mini 4`** |
-----------------|---------------------------|------------------|------------------|
![IMG_3482](https://user-images.githubusercontent.com/2602313/100931519-a4e48a80-34b8-11eb-9575-837bcdee70e8.png) | ![IMG_0169](https://user-images.githubusercontent.com/2602313/100932597-18d36280-34ba-11eb-83df-3dfd3ec8f8b7.png) | ![IMG_0078](https://user-images.githubusercontent.com/2602313/100933563-88961d00-34bb-11eb-8622-88af581602d0.png) | ![IMG_0361](https://user-images.githubusercontent.com/2602313/100965247-5060ff80-34f8-11eb-9799-3ad92f4dbc15.png)

**Comment by Robodog63** [comment]
Sent using the mobile mail appOn 12/2/20 at 1:34 PM, Kamil Jozwiak wrote:
                
            
            
                
                    From: "Kamil Jozwiak" <notifications@github.com>Date: December 2, 2020To: "brave/brave-ios" <brave-ios@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Subject: Re: [brave/brave-ios] changing "we somehow goofed" string (#3103)
                
                

Verification PASSED on iPhone 11 running iOS 14.2 using 1.22 (20.12.2.0)

Verification PASSED on iPad Air (3rd Gen) running iOS 14.0.1 using 1.22 (20.12.2.0)

Verification PASSED on iPhone 6s+ running iOS 12.4.1 using 1.22 (20.12.2.0)





iPhone 11
iPad Air (3rd Gen)
 iPhone 6s+











—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/brave/brave-ios/issues/3103#issuecomment-737509901",
"url": "https://github.com/brave/brave-ios/issues/3103#issuecomment-737509901",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Robodog63** [comment]
> ```
- `@_pl_`
```

**Comment by Robodog63** [comment]
Sent using the mobile mail app
