### ISSUE TITLE
Shared link from different sites on the same tab is incorrect

### ISSUE THREAD

**Issue by ianrahman** [brave/brave-ios#3246]
### Description: 
Sharing a URL for the current page, using the same tab that was used to previously share a different page’s URL, will result in the original URL being shared.

### Steps to Reproduce 
  1. Open the three dot menu from any page
  2. Tap “Share with...”
  3. Either share the page or close out of the share window
  4. In the same tab, navigate to another website
  5. Using steps 1-3, attempt to share the page
  6. Observe the link being shared 

**Actual result:** 
Link shared the second time is the same as the first link. 

Screenshot of issue: https://imgur.com/a/AA3xRbb

**Expected result:**
Link shared the second time is for the second page shared. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always reproducible 

**Brave Version:** 
Version 1.22.2 (21.1.21.11)

**Device details:** 
iPhone 12 Pro Max, iOS 14.4

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
N/A

**Comment by LaurenWags** [comment]
I also know someone who encountered this issue a few times. cc @anthonypkeane @kylehickinson @iccub

**Comment by marcopelegrini** [comment]
For me you don’t even need steps 4-6:
Open a tab, google something, open a link, click share… copy
The urls copied is the google search, not from the page.

On top of that it’s literally impossible to “Select all” in the url, the menu never pops out

**Comment by StevenGodfrey** [comment]
> For me you don’t even need steps 4-6:
> Open a tab, google something, open a link, click share… copy
> The urls copied is the google search, not from the page.
> 
> On top of that it’s literally impossible to “Select all” in the url, the menu never pops out

The OP probably noticed the bug via their flow above, but I agree it occurs when you navigate to a new page. The share link holds the link from the original page navigated from rather than the current page. An easy example to repeat:

1.) Close all tabs and thumb up from bottom screen of phone to close the instance of brave from iPhone’s App memory to start fresh
2.) open brave
3.) start typing in the address bar and search for anything
4.) click link in search engine
5.) tap the 3 dot menu
6.) tap share with...
7.) try sharing temporarily with anyone
8.) see that the share link is still pointed to the search engine and not the current website displayed

**Comment by komape** [comment]
This bug was reported in January 31st and has not been fixed. And it's actually a real bug. Not a button that has the wrong color or something similar. If I want to share a website's URL I have to copy it out of the address bar which is quite annoying because there is no option 'select all'. Please fix this ASAP.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3614
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3614
------------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3614
