### ISSUE TITLE
"Share with.." stops working when left opened after sharing with "Books" app

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3279]
### Description: 

When you've shared/sent a PDF from Brave to `Books.app`, the `Share with...` menu stays opened. If you switch back to Brave and try sharing the same PDF using either `Mail` or `Messages`, you'll notice that nothing happens.

### Steps to Reproduce 

  1. launch `1.23 (21.2.5.15)`
  2. open https://bitcoin.org/bitcoin.pdf
  3. click on `Share with...` and select `Books`
  4. once the PDF has been shared with `Book`, go back into Brave and you'll notice that the `Share with...` modal is still opened
  5. attempt to share the PDF with either `Mail` or `Messages` and you'll notice nothing happens
  6. close/re-open the `Share with...` modal and you'll now be able to share the PDF without any issues

**Actual result:** 

https://youtu.be/AGwxY5dDqH4

**Expected result:**

Probably should dismiss the `Share with...` modal once a user has shared with another app

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR mentioned above.

**Brave Version:** 

* `1.23 (21.2.5.15)`

**Device details:** 

* `iPhone 11` running `iOS 14.4` using `1.23 (21.2.5.15)`
* `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.5.15)`
* `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.5.15)`
* `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.5.15)`

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @iccub @srirambv @bsclifton @anthonypkeane @soner-yuksel

**Comment by soner-yuksel** [comment]
Looks like this bug is a system problem. Shortly when user tries to share with iBooks and other activity types that opens the recipient application directly, UIActivityController never calls back completionWithItemsHandler.

In addition to this after sharing in 'ibooks', other share types like mail or message will not work until Share sheet is closed and opened again. However since we cant have a callback related with ShareSheet after Share is done, we cant even tell the application to dismiss the ShareSheet.

I opened a radar "Feedback" on Apple Side FB8999695. I will monitor the reply and inform about the details.

FYI: Same behaviour happens in **SAFARI**

**Comment by kjozwiak** [comment]
Thanks for investigating @soner-yuksel 👍 I'll move this out of the milestone as discussed in the planning/triage meeting.
