### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#3385]
## Problem Description 
Safari on iOS lets users create a limited version of a PWA via the share menu and `Add to Home Screen`.

![image](https://user-images.githubusercontent.com/4733304/110351491-bd999a80-7fe9-11eb-8198-92398545d09b.png)

## Feature Overview 
User would visit a site meeting the Safari spec for PWA (https, manifest file, uses service worker) and they should see `Add to Home Screen` in the share menu

## Design 
Would be interesting if we had the ability to put the Brave icon in the corner of the icon (if this capability existed)

## Implementation Details 
We're blocked on this at the moment and can't implement as this is not exposed outside of Safari ☹️ Apple would need to make a change in order for this to work

**Comment by bsclifton** [comment]
Is there a radar open to add support for PWA to WkWebview?

**Comment by ItzYanick** [comment]
What about transferring the user to Safari? This would at least make it easier to add it to the Homescreen as currently you have to manually open up Safari and search for the site again.

**Comment by iccub** [comment]
@ItzYanick it can be done, Aloha browser does a cool thing with Safari redirect, i think we could copy the behavior

**Comment by ItzYanick** [comment]
I would love to help out, but sadly I am not a iOS Developer :(
But I would love to give you guys ideas/feedback and test the feature out in the Beta ^^

**Comment by ItzYanick** [comment]
> @ItzYanick it can be done, Aloha browser does a cool thing with Safari redirect, i think we could copy the behavior

I just had a look at the Aloha Browser and I am pretty impressed at how they implemented it. So basically they open up a local page (encoded as a base64 string) in the Safari Browser which you can add to the iOS Homescreen. If you open the PWA it will redirect you to the Aloha Browser itself where it opens up the page in a Full screen mode. So far I am really impressed. Especially as they open up the page on their own app the page is also loaded with tracking protection.

I just saw 3 "minor issues":
1. when I clicked the "add to homescreen"-Button in Aloha it got me to the Brave Browser as Brave is set as my default one.
(but I do think this can be fixed to force open Safari instead as I saw that with other Apps happen too but correct me if I am wrong here. As I said I am not a iOS Developer and I have no clue haha)
2. Using the Aloha/Brave Browser in a Fullscreen Mode is a incredible great idea but would also mean switching out of the PWA and opening up the Browser normally would end up to the same page. And even going further: you would have "give up" the functionality of just switching the app to the browser to search up for a information as you are already on the browser (I hope you understand what I mean. I want the PWA to be a "independent" app so that I can use it whilst opening Brave in the background to search for something else)
3. going even further into this issue. You would have to add a little button on one of the corners to exit the Fullscreen mode (just like Aloha did). Meaning you would loose the full-Fullscreen-Experience. And this button could also end up blocking UI from the page.

I do have some ideas but none of them are easy-to-use or sustainable or make sense at all.

**Comment by iccub** [comment]
yeah i noticed bugs 1 and 2 too, and when I added brave.com to homepage the favicon was blurry, this is something we could fix potentially

the full screen thing invites another set of problems like you said, if you use siri shortcuts, open a link from another app, this may still take you to the fullscreen-mode in our app

not sure if we can force safari to show, there might be a custom scheme url to do so,

on our end this task requires some investigation and design work, 
given the limitations we could make a hybrid approach maybe, then the site you add to homepage would open as a regular Brave tab, skipping the standalone/fullscreen mode

**Comment by ItzYanick** [comment]
i personally would prefer to have the PWA open up as a "normal Safari PWA" because I prefer the standalone/fullscreen approach more than having it also open in Brave as a tab or in fullscreen there. Having it opening in Brave would totally ruin the idea of PWAs having them as separate kinda Apps. 
For example websites like Geforce Now and Google Stadia are using PWAs on iOS as a way to bring their game streaming website to the iPhone and iPad without the need of going through the Apple App Store. 
Therefore making the website open in Brave would be a terrible idea :(

**Comment by iccub** [comment]
let's close, this can't be easily done without Apple providing us WKWebView api for it
