### ISSUE TITLE
Improve reliability of saved screenshots of opened tabs

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3430]
There's bunch of problems, many times screenshots of opened tabs are white.

This happens sometimes when you browse the app and open links in new tab, happens when you relaunch the app and tabs are restored.

See this recording for example, tabs screenshots are not restored correctly

https://user-images.githubusercontent.com/6950387/138260817-071312b0-f64a-4e38-b670-142b7457b22a.MP4

**Comment by Uni-verse** [comment]
Verification completed using build version `1.35 (22.1.26.17)`

**PASSED** on `iPhone X` running iOS 14.4.2
**PASSED** on `iPhone 12 Pro` running `'iOS 15.1.1'`
**PASSED** on `iPad (7th Gen)` running `iPadOS 15.2.1`

https://github.com/brave/brave-ios/pull/4763#issue-1086274331
- Test session restore
- Test opening pages in new tabs
- Test private browsing tab tray
- Test performance (open many tabs and restore session or open many tabs and then tab tray).

Note: Open tab screenshot reliability will still need to be improved because this continues to happen intermittently.
