### ISSUE TITLE
Double Tap in URL input for Text Menu

### ISSUE THREAD

**Issue by thall1961** [brave/brave-ios#3444]
## Problem Description 
Initial tap in the browser url bar highlights the entire url, but subsequent taps do not bring up a menu as expected.  Tapping several times and dragging the copy section to the beginning and the end of the url text is the only way to show the copy menu.

## Feature Overview 
Show text menu on 2nd tap

## Design 
On 2nd tap in url bar, keep text highlighted and show menu

## Implementation Details 

https://youtu.be/drHSd-SjFEY

##User Experience 

   1.  Double tap in the url input
   2. Menu should show
   3. Tap a 3rd time to place cursor

**Comment by fear-the-beaver** [comment]
In Safari, second tap in the address bar highlights the whole URL and presents menu with "Copy / Cut" options.

**Comment by jonathansampson** [comment]
### Comparison with Other Browsers

_In addition to Safari_, the _tap + tap + copy_ behavior is also observed in the following:

- Firefox
- Chrome
- Opera
- Duck Duck Go
- Edge

Browsers which behave similar to Brave are:

- Firefox Focus

### Recent Examples of Feedback

It is also worth noting that when notable figure Kevin Rose [mentioned](https://twitter.com/kevinrose/status/1389221109103357953) his recent appearance on the Brave podcast, the first two responses from his community regarding Brave were from iOS users ([Steve Campbell](https://twitter.com/Steve_Campbell/status/1389221511014219779) and [BeholdObscurity](https://twitter.com/beholdobscurity/status/1389222611394056193)) who expressed some difficulty with copying URLs:

![krosethread](https://user-images.githubusercontent.com/815158/116893604-c9bf6400-abf6-11eb-91fc-365e31b6927e.png)

### Workarounds, and their Discoverability

#### Share With

Users can click the … at the bottom-right of the browser and select _Share with…_ from the menu. The resulting menu lists _Copy_ as the first option. This is not ideal as users may not be copying with the intention of sharing; as such they would not necessarily think to look within this region of the browser.

#### Multi-Tap

Tapping the address bar multiple times (i.e. 4x) in quick succession offers a copy option. This is not ideal as it is far too esoteric; users are not likely (nor should they be expected) to know obscure gestures.

#### Long-Press

Users of Brave on iOS can also currently long-press the address bar (with no initial tap) to reveal an option to copy the URL. This feature was not known to one of the users in the _recent examples_ above, suggesting potential room for improvement in UI/UX on Brave's part.

Users tend to expect Safari-like behavior, where a _tapping on selected text_ reveals options to copy said text. In Brave, tapping on selected text moves the state from _selection mode_ to _caret mode_. The user above who was familiar with this workaround shared that "it's not a default gesture," because "it's not how copying test in other apps work on iOS". As such, even for users who are ultimately familiar with the long-press approach, copying the URL may still involved considerable friction.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.5.3.20)
- Verified test plan from https://github.com/brave/brave-ios/pull/3615
-------
Verification passed on iPhone 7+ with iOS 14.5 running 1.25(21.5.3.20)
- Verified test plan from https://github.com/brave/brave-ios/pull/3615
-------
Verification passed on iPad Prowith iOS 14.5 running 1.25(21.5.3.20)
- Verified test plan from https://github.com/brave/brave-ios/pull/3615
