### ISSUE TITLE
"Set Brave as Default" button should go away after setting Brave as the default

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-ios#3466]
### Description: 
The settings page has a "Set Brave as default" button. After interacting with it and setting Brave as the default, the button still shows, giving the impression that the user has not set Brave as the default yet. 

The button should hide after the user has set Brave as the default.

### Steps to Reproduce 
  1. Go to settings
  2. Tap on "Set Brave as default" and set Brave as default
  3. Return to settings
  4. See that the "Set Brave as default" button is still there.

**Actual result:** 
The "Set Brave as default" button does not go away even though user has set Brave as the default.
![image](https://user-images.githubusercontent.com/2388823/112514878-ff00a880-8d52-11eb-9898-a1fcf401166c.png)

**Expected result:**
The "Set Brave as default" button should be hidden after user has set Brave as the default.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
No other browser hides it, and this is because we can't detect whether we are set as a default browser.
We can only detect that the user tapped on settings, not it the default browser was set.
If the user removed Brave from default app, there would be no place for us to know, and hiding this option would make it hard to re-add us as a default browser

At the moment if user tapped on one of our default browser callout, all other callouts are not going to show anymore,
i think this is good enough.

And settings is not a place users visit often, unlike our other callouts at app launch or on NTP

**Comment by karenkliu** [comment]
@iccub Thanks for the explanation! Perhaps we can re-visit this once we have a way to detect whether the user has set Brave as the default.

**Comment by iccub** [comment]
Definitely, we can keep this ticket open. Apple may provide new api for this in the future,
I'm gonna put `blocked` label on it

Apple and their limitations are always fun :(

**Comment by iccub** [comment]
New iOS 15 version came in and zero improvements regarding default browser detection, I will close this ticket as `wontfix`
