### ISSUE TITLE
Back/Forward list shows "Firefox Home Page"

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#353]
The back forward list is shown when you long-press on the Back or Forward buttons in the toolbar.

Copy should read "New Tab" instead. 

![simulator screen shot - iphone x - 2018-10-23 at 16 41 55](https://user-images.githubusercontent.com/529104/47389444-c2907480-d6e2-11e8-9d07-30524eec3711.png)

**Comment by jhreis** [comment]
Also, raises the question if we should rename the "New Tab" page.

**Comment by jamesmudgett** [comment]
Let's rename to "New Tab"

**Comment by jhreis** [comment]
@jamesmudgett Main concern is that it kind of sounds like it is creating a "New Tab". I was more proposing potentially renaming the "new tab" title to "Home Page" or something. 

Regardless, this label does not need to align with the actual title on the 'new tab' page.

(e.g. page can still say "New Tab", while the label in the screenshot says "Brave Home Page" or whatnot).

---
Otherwise, yeah, we can just rename this label to "New Tab"

**Comment by jamesmudgett** [comment]
Home
