### ISSUE TITLE
Double tap on player interface zooms the video.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3575]
### Steps to Reproduce 
  1. Add video to playlist, open playlist screen
  2. Double tap on 15-sec back or forward button

**Actual result:** 
Video is zoomed

**Expected result:**
Video should not zoom, it should register rapid button taps

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.5 running 1.25(1.4.27.17)
- Verified double tap on 15-sec back/forward seeks the video instead of zooming in

https://user-images.githubusercontent.com/17010094/116363167-c09b5500-a7fa-11eb-93be-18e495cb3eb0.MP4

-------------
Verification passed on iPhone XR with iOS 13.5 running 1.25(1.4.27.17)
- Verified double tap on 15-sec back/forward seeks the video instead of zooming in

https://user-images.githubusercontent.com/17010094/116363115-b416fc80-a7fa-11eb-90ab-e8e396e6a4e2.MP4

------------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(1.4.27.17)
- Verified double tap on 15-sec back/forward seeks the video instead of zooming in

https://user-images.githubusercontent.com/17010094/116362876-71552480-a7fa-11eb-8071-909b178dab5f.MP4
