### ISSUE TITLE
Bottom toolbar does not hide when scrolling on an iPhone X

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#358]
### Description: 

Usually when you scroll down a page, the url bar +toolbar hide. Only the url bar hides on an iPhone X

### Steps to Reproduce 
  1. Open any page that you can scroll (yahoo.com) on an iPhone X
  2. Scroll

**Actual result:** Bottom toolbar doesn't hide
**Expected result:** Bottom toolbar hides
**Reproduces how often:** Always

**Comment by vldmrkl** [comment]
I would like to work on it.

**Comment by danishjafri88** [comment]
Is not related to iPhoneX. This bug is in iPhone 6s as well; perhaps all devices. 
STR: 
1. Open a website with possibility of scroll like youtube.com
2. Verify the tab bar hides on scroll.
3. Tap on either Shield Button on top Right or the hamburger menu button on top left.
4. Close the overlay and tab bar stops hiding on scroll.

Maybe something to do with transition
