### ISSUE TITLE
Add Brave Search as an alternative search

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#3745]
## Test plan
(for Desktop/Android, see https://github.com/brave/brave-browser/issues/15663)

Full test plan below by @iccub in https://github.com/brave/brave-ios/issues/3745#issuecomment-861739421

## Description 
We recently announced having a search (https://brave.com/brave-search/) and this issue is intended to capture adding this to the browser as an alternate search. It would be in the `Standard Tab` and `Private Tab` sections under `Search` in settings.

Desktop and Android can make use of a config flag and the variations server to roll this out. I think on iOS we'll have to either have Brave Search or not (ex: if we wanted to add or remove, we'd need a new build).

This will include having Brave Search listed in onboarding. Some notes from the desktop issue:
- favicon: `https://cdn.search.brave.com/serp/favicon.ico`
- search: `https://search.brave.com/search?q={searchTerms}&source=ios`
- suggest: `https://search.brave.com/api/suggest?q={searchTerms}&rich=false`
________________________________________________

For the Desktop/Android version of this issue, please see https://github.com/brave/brave-browser/issues/15663

**Comment by iccub** [comment]
Test plan

### Naming
- While testing other plans, verify that Brave Search is displayed as ‘Brave Search beta’ everywhere in the app. This does not apply to the website itself.
### Onboarding


1. Eligible regions test
- Set device’s region to Canada or US
- Fresh install 1.27
- Verify that on onboarding ‘Brave Search beta’ is present as a second option
- Set Brave Search as default
- Go to search settings, verify that Brave Search is set for both private and regular mode.


2. Non eligible

- Set device’s region to non CA or US one, Poland for example
- Fresh install 1.27
- Verify that ‘Brave Search beta’ is not present in the onboarding screen.
- Go to search settings, verify that you can choose Brave Search as one of SE options.

3. App upgrade

- Install 1.26
- Open the app, play with it for a minute, choose a SE
- Upgrade to 1.27
- Verify that SE you chose in 1.26 is still set
- Go to search settings, verify that BraveSearch is an option to choose from
- Choose BraveSearch, verify it’s working

### Queries

- Set BraveSearch as default
- Tap on url bar, make a query
- Verify that one of query parameters is `source=ios`, in general the url should go like this
- https://search.brave.com?q=test&source=ios

### Default callbacks
# DRAFT: WEBSITE SIDE NOT IMPLEMENTED YET
1. Happy path

- Fresh install 1.27
- Do not set BraveSearch as default, use Google
- Go to search.brave.com
- Verify that default browser prompt is shown
- Tap on the ‘set as a default’ button
- Go to the search settings screen, verify Brave Search is set for regular browsing mode only.
- Type a query in url bar, verify BraveSearch does the query

2. Private mode

- Fresh install 1.27
- Do not set BraveSearch as default, use Google
- Open private mode
- Go to search.brave.com
- Verify that default browser prompt does NOT show

3. Per session retries

- Fresh install 1.27
- Do not set BraveSearch as default, use Google
- Go to search.brave.com
- Verify that default browser prompt is shown, do not tap on the button
- Reload the page 2 times
- Verify that default browser prompt is shown
- Reload the page third time
- Verify that the default browser does not show anymore
- Try going to search.brave.com in another tab, verify it still does not show
- (logic here it should show the prompt max 3 times per session until you kill and reload the app)

4. Total retries

- Fresh install 1.27
- Do not set BraveSearch as default, use Google
- Go to search.brave.com
- Verify that default browser prompt is shown, do not tap on the button
- Reload the page 3 times
- Kill the app, reopen
- Repeat steps c)-f) until you see the prompt 10 times total
- Next time you go to search.brave.com you should not see the prompt, whether it’s new browsing session or not

5. Brave Search already set via onboarding

- Set device to CA or US region
- Fresh install 1.27
- Set BraveSearch as a default on onboarding screen
- Go to search.brave.com
- Verify that the default browser prompt is not shown.

6. Brave Search already set via SE list

- Fresh install 1.27
- Go to search settings, set BraveSearch as a default for regular mode
- Go to search.brave.com
- Verify that the default browser prompt is not shown.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.17.10)`

STR/Cases used to run through `Naming`, `Onboarding` and `Query` as per https://github.com/brave/brave-ios/issues/3745#issuecomment-861739421.

* ensured that `Brave Search beta` only appears for `Canada` & `USA`
* ensured that `Brave Search beta` didn't appear when device set to either `Japan` or `German` region/language
* ensured that `Brave Search beta` appears under SE settings in every region
  * `Japan`, `Germany` & `France`
* ensured that `Brave Search beta` is being displayed in the following area's:
  * `Onboarding`, `SE Settings`, `Quick Search`, `Search Suggestions via Search Overaly`
  * also went through https://github.com/brave/brave-ios/issues/3811#issuecomment-863416123
* Query when searching from URL bar --> https://search.brave.com/search?q=brave&source=ios
* Query when searching from Quick Search --> https://search.brave.com/search?q=basic%20attention%20token&source=ios
* Query when searching via `search.brave.com` --> https://search.brave.com/search?q=videocard

**`Japan`** | **`Germany`** | **`Canada & USA`** | **`SE Settings`** | **`Quick Search`**
-------------|-----------------|-----------------------|------------------|----------------------
![IMG_3734](https://user-images.githubusercontent.com/2602313/122508026-49e73080-cfcf-11eb-9525-da3560928e16.png) | ![IMG_3735](https://user-images.githubusercontent.com/2602313/122508054-55d2f280-cfcf-11eb-9170-f1ab58199859.png) | ![IMG_3736](https://user-images.githubusercontent.com/2602313/122508121-6c794980-cfcf-11eb-8a19-ecde0ecde135.png) | ![IMG_3737](https://user-images.githubusercontent.com/2602313/122508165-831fa080-cfcf-11eb-94d6-e39828788aa8.png) | ![IMG_3739](https://user-images.githubusercontent.com/2602313/122508304-c5e17880-cfcf-11eb-811d-5a3ff4d10912.png)

-------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.17.10)`

STR/Cases used to run through `Naming`, `Onboarding` and `Query` as per https://github.com/brave/brave-ios/issues/3745#issuecomment-861739421.

* ensured that `Brave Search beta` only appears for `Canada` & `USA`
* ensured that `Brave Search beta` didn't appear when device set to either `China` or `Spain` region/language
* ensured that `Brave Search beta` appears under SE settings in every region
  * `China`, `Spain` & `Taiwan`
* ensured that `Brave Search beta` is being displayed in the following area's:
  * `Onboarding`, `SE Settings`, `Quick Search`, `Search Suggestions via Search Overaly`
  * also went through https://github.com/brave/brave-ios/issues/3811#issuecomment-863416123
* Query when searching from URL bar --> https://search.brave.com/search?q=brave&source=ios
* Query when searching from Quick Search --> https://search.brave.com/search?q=basic%20attention%20token&source=ios
* Query when searching via `search.brave.com` --> https://search.brave.com/search?q=videocard

**`China`** | **`Spain`** | **`Canada & USA`** | **`SE Settings`** | **`Quick Search`**
-------------|-----------------|-----------------------|------------------|----------------------
![IMG_0278](https://user-images.githubusercontent.com/2602313/122511968-1fe53c80-cfd6-11eb-9b07-bd25320bcfa8.png) | ![IMG_0279](https://user-images.githubusercontent.com/2602313/122511977-24a9f080-cfd6-11eb-80b1-ec4c88880277.png)  | ![IMG_3736](https://user-images.githubusercontent.com/2602313/122508121-6c794980-cfcf-11eb-8a19-ecde0ecde135.png) | ![image](https://user-images.githubusercontent.com/2602313/122512090-5458f880-cfd6-11eb-9284-82eee7ae7676.png) | ![IMG_0280](https://user-images.githubusercontent.com/2602313/122512101-5a4ed980-cfd6-11eb-95b9-e460ab2acd7d.png)

-------------

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.27 (21.6.17.10)`

STR/Cases used to run through `Naming`, `Onboarding` and `Query` as per https://github.com/brave/brave-ios/issues/3745#issuecomment-861739421.

* ensured that `Brave Search beta` only appears for `Canada` & `USA`
* ensured that `Brave Search beta` didn't appear when device set to either `Netherlands` or `Poland` region/language
* ensured that `Brave Search beta` appears under SE settings in every region
  * `Netherlands`, `Poland` & `India`
* ensured that `Brave Search beta` is being displayed in the following area's:
  * `Onboarding`, `SE Settings`, `Quick Search`, `Search Suggestions via Search Overaly`
  * also went through https://github.com/brave/brave-ios/issues/3811#issuecomment-863416123
* Query when searching from URL bar --> https://search.brave.com/search?q=brave&source=ios
* Query when searching from Quick Search --> https://search.brave.com/search?q=basic%20attention%20token&source=ios
* Query when searching via `search.brave.com` --> https://search.brave.com/search?q=videocard

**`Netherlands`** | **`Poland`** | **`Canada & USA`** | **`SE Settings`** | **`Quick Search`**
-------------|-----------------|-----------------------|------------------|----------------------
![IMG_0570](https://user-images.githubusercontent.com/2602313/122521459-d818e200-cfe2-11eb-9e9f-0652d103e3b5.png) | ![IMG_0571](https://user-images.githubusercontent.com/2602313/122521476-dc44ff80-cfe2-11eb-8dfc-6d794b620c1e.png) | ![IMG_0573](https://user-images.githubusercontent.com/2602313/122521500-e36c0d80-cfe2-11eb-87fd-b0d4393652d7.png) | ![IMG_0575](https://user-images.githubusercontent.com/2602313/122521520-e961ee80-cfe2-11eb-888c-98c6e8d86ca2.png) | ![IMG_0574](https://user-images.githubusercontent.com/2602313/122521532-ed8e0c00-cfe2-11eb-90af-1c480bdf319c.png)

**Comment by kjozwiak** [comment]
Waiting on more information re: running through the cases for `Default callbacks`. @bsclifton asking the search team if there's any way of getting a `live` test case via staging.

**Comment by kjozwiak** [comment]
**`Quick Note:`**

For the `Default Callback` feature, `search-dev.brave.com` was used rather than `search.brave.com`.

Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.18.13)`

* Went through the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3745#issuecomment-861739421 regarding the `Default Callback` API

**`Default`** | **`Clicked Set Default`** | **`After setting default`** | **`PB (no modal)`**
--------------|----------------------------|-----------------------------|-----------------------
![IMG_3740](https://user-images.githubusercontent.com/2602313/122607304-5c518080-d048-11eb-9f99-c11e915ba482.png) | ![IMG_3743](https://user-images.githubusercontent.com/2602313/122607330-64a9bb80-d048-11eb-8385-2f47963f77a4.png) | ![IMG_3742](https://user-images.githubusercontent.com/2602313/122607348-6b383300-d048-11eb-9db4-72e244c4afa1.png) | ![IMG_3744](https://user-images.githubusercontent.com/2602313/122607367-712e1400-d048-11eb-85c9-7955ffa39f2f.png)

----------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.18.13)`

* Went through the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3745#issuecomment-861739421 regarding the `Default Callback` API

**`Default`** | **`Clicked Set Default`** | **`After setting default`** | **`PB (no modal)`**
--------------|----------------------------|-----------------------------|-----------------------
![IMG_0282](https://user-images.githubusercontent.com/2602313/122632807-1f66a780-d0a3-11eb-8a8b-46a8e4703d04.png) | ![IMG_0283](https://user-images.githubusercontent.com/2602313/122632810-28f00f80-d0a3-11eb-9a20-ef7b2f50074b.png) | ![IMG_0284](https://user-images.githubusercontent.com/2602313/122632814-2e4d5a00-d0a3-11eb-88e1-d91f9ea43b98.png) | ![IMG_0285](https://user-images.githubusercontent.com/2602313/122632820-33120e00-d0a3-11eb-9b8a-0f85702325c4.png)

----------

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.27 (21.6.18.13)`

* Went through the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3745#issuecomment-861739421 regarding the `Default Callback` API

**`Default`** | **`Clicked Set Default`** | **`After setting default`** | **`PB (no modal)`**
--------------|----------------------------|-----------------------------|-----------------------
![IMG_0576](https://user-images.githubusercontent.com/2602313/122633683-ccdbba00-d0a7-11eb-842a-ed9b99b1d017.png) |![IMG_0577](https://user-images.githubusercontent.com/2602313/122633689-d2390480-d0a7-11eb-8bbf-a522d18664b2.png) | ![IMG_0580](https://user-images.githubusercontent.com/2602313/122633696-d82ee580-d0a7-11eb-9e6b-34ccbb9228c7.png) | ![IMG_0579](https://user-images.githubusercontent.com/2602313/122633700-dd8c3000-d0a7-11eb-9e54-0b91307efb61.png)
