### ISSUE TITLE
Browser doesn't show hidden state when app list is opened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3981]
### Description: 
Found while testing #3921. Browser doesn't show hidden state when app list is opened

### Steps to Reproduce 
  1. Clean install or upgrade to 1.29 with browser lock set
  2. Open a tab and load a page
  3. Open app list, browser doesn't hide content
  4. Background app / Open another app and then open app list, browser content is hidden

**Actual result:** 

https://user-images.githubusercontent.com/17010094/127495261-f89a7ba0-5456-4969-949c-cb7c16c36852.MP4

**Expected result:**
Probably hide browser contents even when the app was being used in foreground and app list is opened

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
Easy

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @kylehickinson

**Comment by kylehickinson** [comment]
@srirambv This is on purpose, since if you show it every time the app becomes "inactive" it shows up the second you start dragging it even if you don't fully finish going to the app picker. 

There's no notification for when the user enters the multitasking tray/app list, just "becoming inactive" and "entering background". 

Also becoming inactive happens for other reasons other than user preparing to leave the app.

**Comment by srirambv** [comment]
Sounds good. Going to close the issue as wontfix
