### ISSUE TITLE
Add ability to add new account from within account picker in buy/send/swap

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4315]
Add a `+` button to the top right of the account picker list so that users can create new accounts (or import one) right from buy/send/swap screen

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.8.23)
- Verified new setting for lock wallet is available in wallet menu
- Verified able to change the auto-lock value from default 5 to any of the preset values
- Verified wallet auto-locks after the specified time has passed
- Verified setting auto-lock to 1 min and using the wallet for more than a minute doesn't lock it
- Verified wallet auto-locks after the specified time due to inactivity even if wallet is in focus
- Verified wallet auto-locks after the specified time due to inactivity when not in use
-----------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.8.23)
- Verified new setting for lock wallet is available in wallet menu
- Verified able to change the auto-lock value from default 5 to any of the preset values
- Verified wallet auto-locks after the specified time has passed
- Verified setting auto-lock to 1 min and using the wallet for more than a minute doesn't lock it
- Verified wallet auto-locks after the specified time due to inactivity even if wallet is in focus
- Verified wallet auto-locks after the specified time due to inactivity when not in use
-----------

~~Verification failed on iPhone 7+ with as it crashed every time the wallet is launched [#4676](#4676)~~

-----------
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.9.23)
- Verified new setting for lock wallet is available in wallet menu
- Verified able to change the auto-lock value from default 5 to any of the preset values
- Verified wallet auto-locks after the specified time has passed
- Verified setting auto-lock to 1 min and using the wallet for more than a minute doesn't lock it
- Verified wallet auto-locks after the specified time due to inactivity even if wallet is in focus
- Verified wallet auto-locks after the specified time due to inactivity when not in use
