### ISSUE TITLE
Brave crashes when we share video via Twitter option

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#446]
### Description: 
Brave crashes when we share video via Twitter option

### Steps to Reproduce 
  1. Open `https://theverge.com/` in Private tab
  2. Open any video which has SHARE option
  3. Scroll the page up and down, click on SHARE link and select `TWEET` option

**Actual result:** 
Brave crashes
https://drive.google.com/open?id=1qU4iGFFDs3ZqYBwKH0svTj0Q3clr-alg
**Expected result:**
Brave should not crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 8 (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by danishjafri88** [comment]
@GeetaSarvadnya the issue has no relation with video, rather it happens when you open a pop-up(window.open) while in private mode. Please verify the same. 

Why its crashing?
=> On window.open() the parent WKWebView creates a new configuration for the popup window. This configuration maintains cookies and relationship between parent and popup.
=> On the other hand, when the app is in private mode, any new tab created has its WKProcessPool reinitialised to sandbox cookies.
When the above two happen at same time, the relationship is lost and configuration becomes corrupt. Hence the crash.
QUICKFIX: comment line 12 in BraveWebView.swift. (only for validation purpose, not a fix)

@jhreis @anthonypkeane after speaking with @tmancey on this, we came up with two possible solutions:
1. How FF handles this: Doesn't allow popup while in private mode. (Maybe show an alert to user about this)
2. Override window.open() function and on callback open a new tab with the url received. This way the cookies are not shared and the UX is not blocked. Only drawback would be callback to parent, which can be handled in next releases. 


Tap 'Try it' in Private mode: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open

**Comment by danishjafri88** [comment]
More Info:
The processpool is re initialised here: https://github.com/brave/brave-ios/blob/223768dda21c2e99ca15d132cc362985b90e1217/Client/Frontend/Browser/BraveWebView.swift#L12

**Comment by srirambv** [comment]
* Verification passed on iPhone 7/iPhone 6 and iPad pro. Verified steps from issue
* Verification passed on iPad 5th Gen. Verified steps from issue
* Verification passed on iPhone SE running 1.9 (19.03.27.19)
* Verification passed on iPhone 8 running 1.9 (19.03.28.00)
* Verification **PASSED** with `1.9 (19.3.27.19)` on `iPad Mini 4` using the above STR.
