### ISSUE TITLE
Favourites reorder causes default browser modal to be stretched 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4464]
### Description: 
Favourites reorder causes default browser modal to be stretched 

### Steps to Reproduce 
  1. Clean install so default browser modal is shown on NTP
  2. Long press on a favourite and try to drag it
  3. Default browser modal gets stretched and doesn't allow to reorder favourite

**Actual result:** 

https://user-images.githubusercontent.com/17010094/140314666-e6b7c483-cc9e-4e47-9bed-c55fc4f91751.MP4

**Expected result:**
Do not disturb the default browser modal or mess with it

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.32.5(21.11.2.23)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?  NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Found while testing #3713

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.7.21)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using `1.33 (21.12.7.21)`

This was checked and verified on all platforms via https://github.com/brave/brave-ios/issues/4463#issuecomment-988289255. However, due to https://github.com/brave/brave-ios/issues/4651, this can't be checked on `iOS 14` until the crash has been resolved. As per https://github.com/brave/brave-ios/issues/4651#issuecomment-988477829, the verification for `Favorites` will be done in that issue so labelling this one as completed.
