### ISSUE TITLE
Preloaded favorites are duplicated after upgrade

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#469]
### Steps to Reproduce 
  1. Install brave1.6.6
  2. Let it run for few seconds
  3. Upgrade to 1.7

Preloaded favorites are duplicated. Favorites that user added are not duplicated.

Happened to me 4 times in a row, it's pretty consistent bug.

**Actual result:** 
<img width="544" alt="zrzut ekranu 2018-11-28 o 13 04 52" src="https://user-images.githubusercontent.com/6950387/49150807-4bb45000-f30e-11e8-833b-c667c83b2c9d.png">

### Additional Information 
There were some work done to prevent this on app crashes, I can't find a ticket for it though. Please link it if you know where it is

**Comment by srirambv** [comment]
@iccub default favourites duplicate when browser crashes as well https://github.com/brave/brave-ios/issues/304#issuecomment-442375493

**Comment by kylehickinson** [comment]
This is because isFirstLaunch isn't migrated. 1.6 used DAU.preferenceKey which I'm not sure exists anymore. This just needs to be set somehow. We could technically set it to true if any of the preferences are migrated, basically saying if you have some pref to migrate then its obviously not your first launch

**Comment by iccub** [comment]
I made something similar here https://github.com/brave/brave-ios/pull/474/files#diff-e249a931d8a40b3ee440070fcf2d709c

**Comment by jhreis** [comment]
This was fixed per https://github.com/brave/brave-ios/pull/494. Looks like maybe wrong fix number in commit.
