### ISSUE TITLE
Wallet auto-lock in background sometimes hides unlock screen after coming back to the app

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4694]
### Steps to Reproduce 
  1. Unlock wallet, open buy send or swap
  2. Background the app
  3. Wait until auto-lock activates (depends on what you have set, recommend 1m)

**Actual result:** <!-- Add screenshots if needed -→
Unlock screen is hidden behind the buy/send/swap

**Expected result:**
Unlock screen is visible

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Comment by srirambv** [comment]
This is still not fixed. I run into it on iPad. Before the unlock screen shows up if the biometric prompt shows up then it can cause this issue. Have seen it but unable to record it when it happens, buy/send/swap screen gets removed and potfolio page loads before unlock screen shows up and because of fingerprint prompt showing up it doesn't fully go back to unlock wallet screen. This is more prominent on #4698
![image](https://user-images.githubusercontent.com/17010094/145560039-2ec20d62-279e-4cb6-a467-2834ca17c28f.png)

**Comment by srirambv** [comment]
Marking this as QA/No as #4698 would be sufficient to verify this issue.
