### ISSUE TITLE
Brave 1.32.x unable to join 1.33.x-created desktop chain

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4730]
### Steps to Reproduce 
  1. install Brave 1.32.3 (21.11.17.19) on iOS
  2. install Brave 1.33.105 on desktop
  3. set up a Sync chain on desktop
  4. try to join from iOS

**Actual result:** 

After scanning the QR code, we get stuck on this screen

![Image from iOS](https://user-images.githubusercontent.com/387249/145886050-b6c3123d-d332-4b17-8454-58a690b88e5a.png)

https://user-images.githubusercontent.com/387249/145886058-293f8c3f-9ba9-4846-92a8-59bc1e1023a2.MP4

**Expected result:**

Should join the Sync chain.

https://user-images.githubusercontent.com/387249/145887056-9f0c0a00-2b65-41c1-ad50-a9497cc07512.MP4

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
`1.32.3 (21.11.17.19)`

**Device details:** 
iPhone 6s (iOS 15.0.2 and iOS 14.4.2).

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### Additional Information

cc @fmarier @AlexeyBarabash @diracdeltas

**Comment by fmarier** [comment]
1.33 should be able to join 1.32 Sync chains (until Jan 1st 2022), but the reverse is not true. 1.32 will not be able to join new Sync chains because the QR code in 1.33 is in a different format (i.e. it's invalid as far as 1.32 is concerned).

Ideally, it should display a useful error message when it doesn't work instead of getting stuck, but I believe the absence of an error message when seeing an invalid code is a bug in older iOS versions.
