### ISSUE TITLE
Delete Site-Specific Data

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#4835]
## Problem Description

It is currently not possible to delete data (e.g. localStorage, cookies, cache) for a specific domain. This type of feature is crucial for web-developers who may need to clear such data for continued testing and development (see also https://github.com/brave/brave-ios/issues/3594). It is likely helpful for many general users who may have submitted bad data, or otherwise found a site in an unworkable state.

## Feature Overview 

Offer the user some means of clearing data related to _a specific domain_, rather than clearing data for _all domains_.

**Comment by duaneking** [comment]
I'm the guy who reported this to @jonathansampson 

I critically need the ability to:
* Remove all cookies/data for a specific domain/tld being tested for compatibility with brave
* Remove all cookies/data for a specific domain/tld and all subdomains on that domain, but no other unrelated domains, for the same common scenario.

This gap is officially the reason why engineers I know at companies you know of can’t officially support Brave for the software they develop. Its not testable, because Brave does not support that type of testing, currently.

**Comment by Uni-verse** [comment]
Verification completed using `1.35 (22.1.24.23)`

**PASSED** on `iPhone 12` running `iOS 15.1.1`
**PASSED** on `iPad (7th Gen)` running `iOS 15.2.1`
**PASSED** on `iPhone X` running `iOS 14.4.2`

- Verified user is able to visit Manage Website Data (Settings > Brave Shields & Privacy > Manage Website Data)
- Verified website data appears
- Verified "Remove All" clears all website data
- Verify empty state
- Verified cookie data shows up and is removable
- Verified new data shows when visiting websites after removing all website data 
- Verify tapping the edit button, verify that single selection changes remove button text to "Remove" and selecting more than 1 changes it to "Remove N Records" where N is the number of selected records
- Verify tapping remove on those websites removes them from the list and refresh the web page that was logged in (or had some cookie stored) and verify you are no longer logged in (or cookie is erased)
- Verified using the search functionality to limit the number of items
- Verify tapping "Remove All" while searching only removes visible/filtered records

![IMG_2374](https://user-images.githubusercontent.com/17885425/150893566-dbc65bfc-ef63-4bf0-b154-75595d80a0a8.PNG)
