### ISSUE TITLE
VPN Billing Retry Changes

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4879]
Details can be followed in https://github.com/brave/brave-ios/pull/8040

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.60 (23.11.12.17)
BraveCore: 1.60.114 (119.0.6045.124)
```
---------------------------

**STEPS:**
1. Followed the steps from [Test Plan](https://github.com/brave/brave-ios/pull/8040#issue-1886574766)

**ACTUAL RESULTS:**
- Verified that the `VPN subscription` can be purchased with `Sandbox` account, and VPN is working fine
- Verified that Brave can be placed in a `grace period` by turning off `Auto purchase & renewal` in the App Store
- Verified that `VPN subscription` can't be purchased/renewed again because of a payment method issue

---------------------------

https://github.com/brave/brave-ios/assets/128532965/76b621b9-4b12-448e-966b-748720e0bbaa

https://github.com/brave/brave-ios/assets/128532965/be9183cf-8490-487c-a246-8d42562db3c4

https://github.com/brave/brave-ios/assets/128532965/efa4c0ae-41c7-48db-b963-24095736bfec
