### ISSUE TITLE
Sync QR code scanning error text

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-ios#4908]
Similar to https://github.com/brave/brave-browser/issues/20742

From 
https://www.reddit.com/r/brave/comments/se32k7/how_do_i_go_around_this/ and Slack discussion

when device tries to connect via version 1 QR code, it gets
```
This code has expired. Please generate a new one on your other device and try again.
```

it should be instead 
```
Title: Can’t sync this device
Body:
This sync code was generated by an outdated version of Brave on another device. Please update Brave on all synced devices and try again.”
```
UPD:
if device is trying to connect to the sync QR code where `version` field is greater than current `2`, it should give such error:

```
This sync code was generated by a newer version of Brave on another device. Please update Brave on all synced devices and try again.
```

**Comment by Uni-verse** [comment]
Verification completed using `1.36 (22.3.3.9) BraveCore 1.36.108 (99.0.4844.51)`

**PASSED** on `iPhone 12 Pro | iOS 15.1.1`
**PASSED** on `iPad (7th Gen) | iOS 15.2.1`
**PASSED** on `iPhone X | iOS 14.4.2`

**Scenario:** 
- When device tries to connect via version 1 QR code, it gets 
```
Title: Can’t sync this device
Body:
This sync code was generated by an outdated version of Brave on another device. Please update Brave on all synced devices and try again.”
```
instead of 

`This code has expired. Please generate a new one on your other device and try again.`

- User is able to dismiss error message
- Sync does not occur

iPad | iPhone
-|-
![IMG_0167](https://user-images.githubusercontent.com/17885425/156624273-312aa9dc-5eb2-4984-ae49-800f9a1c9c5e.PNG) | ![IMG_2486](https://user-images.githubusercontent.com/17885425/156624288-304a6a11-02d4-4445-883f-0a58469e0db5.jpg)
