### ISSUE TITLE
Tapping bookmark icon while in landscape mode switches view to portrait

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#4940]
### Description: 
When viewing/using the browser in landscape mode, if you click on the bookmark icon in the address bar, the browser switches to portrait mode. Note that this does not happen when selecting `Bookmarks` from the main menu when in landscape mode. 

Browser should maintain current orientation for both options.

### Steps to Reproduce 
  1. Use browser in landscape mode
  2. Tap bookmarks icon

**Actual result:** 
Browser switches to portrait mode

**Expected result:**
Orientation should stay consistent. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
v1.34.1

**Device details:** 
iPhone

### Additional Information
User thread:
https://community.brave.com/t/brave-ios-1-34-1-bookmarks-icon-shortcut-bug-ignores-display-orientation/334014
Internal conversation: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1643929582295649

**Comment by dooost** [comment]
I started to look into this issue, and I found [the line of code responsible for the transition](https://github.com/brave/brave-ios/blob/94a5baa8f511c32b254ba1cc65e84fa1929a9487/Client/Frontend/Browser/BrowserNavigationHelper.swift#L25-L26), however since the comment above it states `// All menu views should be opened in portrait on iPhones.`, I'm not confident in removing this without more info.
If there is a reason for this, and it's in fact intended, then I think this issue can be closed - otherwise, it's just a matter of removing this line.

I don't have any context about this, but if I were to guess, one possible reason could be that this is because on iPhones the view is displayed as a `.pageSheet` modal, and as a result, the view only partially covers the background (rest of the browser in this case) in portrait mode, but in landscape mode it covers the whole screen. But again, I'm just guessing and someone in the dev team might have the right context. :)
<img width="300" alt="Screenshot 2022-02-16 at PM 11 21 06" src="https://user-images.githubusercontent.com/32017033/154369694-6cf73437-377a-4fbe-87ff-a3458c172fb2.png"> <img width="500" alt="Screenshot 2022-02-16 at PM 11 20 56" src="https://user-images.githubusercontent.com/32017033/154369710-efadc835-7c85-4976-8983-2e2464c824a2.png">


Actually, the same thing also happens with the Rewards button, due to the [same line of code but in a different function](https://github.com/brave/brave-ios/blob/16afe7b78a77c51b0c6ba6d74f79404881de5a86/Client/Frontend/Browser/BrowserViewController/BVC%2BRewards.swift#L57). There's no comments here about the possible reason, but the UI looks fine to me with removing this line as well, so I can't really tell why it's there. I wasn't sure if I should create a separate issue for this, but I thought it'd be good to bring it up. :)

**Comment by soner-yuksel** [comment]
@dooost you are right, good catch. Most of entries related with forcedPortrait is out of date. I will check every single screen and how they react and remove if unnecessary.

**Comment by Uni-verse** [comment]
Verification completed using `1.38 (22.4.25.21)`

Devices:
`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iPadOS 15.2`

- When in landscape mode, using the bookmark shortcut in the URL bar will not switch into portrait view. 

https://user-images.githubusercontent.com/17885425/165627894-6d7da452-42a4-4838-ad43-918e447d761b.mov
