### ISSUE TITLE
NULL deref in updateTextWithURL - TabLocationView.swift

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#510]
### Description: 
NULL deref while opening a punycode URL

### Steps to Reproduce 
  1. Open http://xn--eby-7cd.com/

**Actual result:** 
Crash

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
Dev (commit - 60a82d37c7987162971f1d23bf5a8639131a27b5)

**Device details:** 
Simulator (iOS 12.1 - iPhone XS)

**Comment by jumde** [comment]
Same for:  `http://xn--test-u89x.com` `xn--otel-uff.com`

**Comment by cndouglas** [comment]
The crash happens because the punycode decoder cannot handle URLs with hyphens. Example: `test-😄.com` also results in a crash.

Ultimately, the problem is happening because typing two hyphens (`--`) in the URL bar causes the hyphens to automatically be converted to a dash (`—`). So, `xn--` (the punycode prefix) is changed to `xn—`, which is incorrect punycode syntax. See the screen recording below for an example.

I'll submit a PR shortly that addresses both problems.

![](https://user-images.githubusercontent.com/19424103/49664290-0c28ea80-fa17-11e8-8307-843a56047073.gif)
