### ISSUE TITLE
Update some of the iPad Shortcuts and key combinations

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5136]
Some of the shortcuts are updated to match the common behaviour other browsers are using.

Shortcuts updated:

- cmd + left arrow key                 : Navigating back on webpage
- cmd + right arrow key               : Navigating forward on webpage
- cmd + shift + n                          : Open New private tab
- cmd + alt + right arrow key      : Open next tab
- cmd + alt + left arrow key        : Open previous tab
- cmd + j                                       : Show downloads

Added shortcut:

- cmd + ,                                      : Open Brave Shields

Removed shortcut: 

- cmd + shift + tab                      :Close All Tabs (because of a clash with system keys)

**Comment by Uni-verse** [comment]
Verification completed using version 1.37 (22.3.23.17)

**Shortcuts updated:**

**PASS** - cmd + left arrow key : Navigating back on webpage
**PASS** - cmd + right arrow key : Navigating forward on webpage
**PASS** - cmd + shift + n : Open New private tab
**PASS** - cmd + alt + right arrow key : Open next tab
**PASS** - cmd + alt + left arrow key : Open previous tab
**FAIL** - cmd + l : Show downloads - https://github.com/brave/brave-ios/issues/5154

**Added shortcut:**

**PASS** - cmd + , : Open Brave Shields

**Removed shortcut:**

**PASS** - cmd + shift + tab :Close All Tabs (because of a clash with system keys)

![IMG_0219](https://user-images.githubusercontent.com/17885425/159999151-c665a08b-ae3f-498d-b1ab-e920c0ab23d9.PNG)
