### ISSUE TITLE
Add platform type to the vpn contact form

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5260]
iOS/iPadOS

**Comment by tzeejay** [comment]
@iccub I am not sure if you had seen it in Slack but we have proposed a different solution to prevent loss of information. May I ask you to instead of including the platform type to change the E-Mail address that the message is sent to to `braveios@guardianapp.com`? The current one will remain in our system so all existing E-Mails will still arrive on our end

**Comment by Uni-verse** [comment]
Verified using 1.40 (22.6.23.15)

Devices: 
iPhone 12 | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.5

- Verified platform field is added to the email draft.
- Verified correct platform type is displayed under platform field (iOS / iPadOS)

iPhone | iPad
-|-
![IMG_3121](https://user-images.githubusercontent.com/17885425/175359796-f18d88b1-d0d3-42da-bd14-6be069bbd8c9.PNG) | ![IMG_0378](https://user-images.githubusercontent.com/17885425/175359793-00cb29da-1b21-4f89-aae8-5391fc8568b0.PNG)
