### ISSUE TITLE
New widget with 4 favorites only

### ISSUE THREAD

**Issue by manfromarce** [brave/brave-ios#5282]
It would be nice if Brave also had a widget which displays 4 favorites rather than 8 to save space on the home screen. iOS probably doesn't allow "shorter" rectangular widgets, so it could be a square widget (2x2) or a search bar + 4 favorites (like the DuckDuckGo app).

**Comment by kylehickinson** [comment]
Hi @manfromarce, unfortunately we cannot do a small widget for favorites with a grid of favorites due to Apple's widget restrictions.

Currently for small widgets we cannot add tappable links like we can in medium/large widgets. 

I'll keep an eye for widget improvements in future versions of iOS and if it becomes doable I will add this feature

Thanks!
