### ISSUE TITLE
Sharing image impossible

### ISSUE THREAD

**Issue by balintbarna** [brave/brave-ios#5390]
### Description: 
Image -> long press -> share
.......................................... -> copy

Both provide the link to the image but there is no way to share the image directly.

### Steps to Reproduce 
  1. Do an image search on brave search
  2. Select any image
  3. Click "view file"
  4. Long press on image
  5. Select "Share"
  6. Select any destination, eg. Note to self on Signal for testing

**Actual result:** 
You get a link

**Expected result:**
I would expect to get the image. There should be a way to do both anyways.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
always

**Brave Version:** 
1.38 (22.5.13.17)

**Device details:** 
iPhone SE:latest

**Comment by soner-yuksel** [comment]
Long-press on direct image inside `WKWebView` doesnt trigger `WKUIDelegate` delegate method `contextMenuConfigurationForElement` so to achieve this behaviour needs another script injection.

Closing the ticket since since we need a special injection for context menu for direct images inside `WKWebView`. We should consider trade-off for another injection for this edge case.

However @balintmaci the good part is this behaviour already can already be achieved using Share with.. under .3dot ... menu.
So we have a way to achieve both of the desired behaviours. 

![shareimageitselfdata](https://user-images.githubusercontent.com/6643505/184719233-8f83432e-5a3a-4815-a199-458732c73387.png)

**Comment by balintbarna** [comment]
It’s good to know that it’s possible through the … menu but as a user I had no idea to look there. For me it would make a lot more sense the other way around, when I click on the image it shares the image and when I use the generic menu it applies to the page I’m visiting, that seems intuitive to me.
