### ISSUE TITLE
Entering https:// shows blank page with tab title as https://localhost:6571

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#540]
### Description: 
Entering https:// shows blank page with tab title as https://localhost

### Steps to Reproduce 
  1. Open a new tab
  2. Just enter `https://` and tap on go
  3. Shows blank page with tab title as `https://localhost:6571`

**Actual result:** 
https://drive.google.com/open?id=1WVo6LIv7l4tN1AOcoLMYnlzMh18IGbU8

**Expected result:**
Should not load anything and time out error page should be shown

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.30.3)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?  
FF loads time out error page

**Comment by kylehickinson** [comment]
This is actually a bit interesting, because its supposed to be showing an error page :) But instead it shows a blank page instead…

`http://localhost:6571/errors/error.html?url=https://&code=101&domain=WebKitErrorDomain&description=The%20URL%20can%E2%80%99t%20be%20shown`

With the console error: `[Error] Failed to load resource: http://localhost:6571/errors/error.html?url=https://&code=101&domain=WebKitErrorDomain&description=The%20URL%20can’t%20be%20shown the server responded with a status of 404 (Not Found) (error.html, line 0)`
