### ISSUE TITLE
Do not hide address bar on navigation

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#553]
### Description: 
Hiding URL bar on navigation can be used by phishing actors. 

See here: https://www.securitee.org/files/hindsight_ccs2017.pdf (ABB 15-16)

### Steps to Reproduce 
  1. Navigate to reddit.com
  2. Scroll

**Actual result:** 
Scrolling hides the address bar

**Expected result:**
URL bar should be visible at all times

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Everytime

**Brave Version:** 
1.7 (18.11.30.03)

**Device details:** 
iPhone SE | iOS 12.1

**Comment by tildelowengrimm** [comment]
In Chrome and Safari, scrolling causes the URL bar to shrink and change styles. When scrolling, it just shows the ETLD+1 and security indicator. Brave's behavior should match.

**Comment by danishjafri88** [comment]
@jamesmudgett need design for this.

**Comment by hennrynusasatria** [comment]
Hi All,

It has been two years, do you have any update on this subject?

Thank you.

**Comment by Uni-verse** [comment]
Verification in Progress using 1.41 (22.7.11.19)

Test Devices: 

iPhone 12 | iOS 15.5
iPhone X | iOS 14.4
iPad (7th Gen) | iPadOS 15.5

Following STR in https://github.com/brave/brave-ios/issues/553#issue-386983656

- Verified URL bar is always visible when scrolling in portrait and landscape orientation.
- Verified bar will transition to collapsed state when scrolling from the top.
- Verified disabling tab bar doesn't alter the URL bar state when scrolling.
- Verified URL bar will change state and URL box with icons will display when user taps on bar in "collapsed" state.

<table><tr><td> 1.40.1 </td></td><td> 1.41 </td><td> 1.41 (iPad)</td></tr>
<tr>
<td>

https://user-images.githubusercontent.com/17885425/178855462-8708b7c6-282a-4964-9f18-88a727207207.MP4

</td>
<td>

https://user-images.githubusercontent.com/17885425/178855477-fb2aaa49-9147-44ec-a90c-c6cb174f9f24.MP4


</td>
<td>

https://user-images.githubusercontent.com/17885425/178855483-cfaff117-9619-449a-81c1-a6adf9b4ac2a.mov

</td>
</tr></table>

Following Test Plan on https://github.com/brave/brave-ios/pull/5659#issue-1297848390

- Verified URL bar when collapsed displays the correct secure content state (lock for secure/https, warning icon when http/otherwise not secure such as certs)
- Test extremely long URLs to ensure that you are always able to see the eTLD+1
 eTLD+1 
- Verified loading URL via share link will not change the toolbar behavior

iOS | iOS | iOS | iOS
-|-|-|-
![IMG_3251](https://user-images.githubusercontent.com/17885425/179051213-2a9e1419-d04e-4e6a-8e8d-41bd9fdce398.PNG) | ![IMG_3252](https://user-images.githubusercontent.com/17885425/179051226-fa6d3529-5a55-47a5-940b-1e6038365ba8.PNG) | ![IMG_3253](https://user-images.githubusercontent.com/17885425/179051232-05d699c1-287b-48ba-ac10-7b167a463b93.PNG) | ![IMG_3254](https://user-images.githubusercontent.com/17885425/179051234-6a8c1f34-d6c2-4036-9ffd-4f746565276d.PNG)
![IMG_0437](https://user-images.githubusercontent.com/17885425/179051482-6c284c61-0669-4d75-83eb-66fb3b08e515.PNG) | ![IMG_0438](https://user-images.githubusercontent.com/17885425/179051488-12f95d83-b719-455c-802f-f0bc96347670.PNG) | ![IMG_0439](https://user-images.githubusercontent.com/17885425/179051490-0994e4b0-0776-4652-93f4-87d9e0dbce36.PNG) | ![IMG_0440](https://user-images.githubusercontent.com/17885425/179051493-d0c21044-40cc-429c-b7f7-99810f6216da.PNG)
