### ISSUE TITLE
Dapp interaction notification is shown twice when trying to connect to Wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5581]
### Description: 
Dapp interaction notification is shown twice when trying to connect to Wallet

### Steps to Reproduce 
  1. Clean install 
  2. Create Wallet
  3. Visit `https://app.1inch.io` and trigger Dapp interaction
  4. Close the panel so the notification dot is shown on wallet
  5. Click the wallet icon, brings up the connect wallet message
  6. Close the panel, wallet still has the notification dot
  7. Click the wallet icon again, brings up the connect wallet message second time

**Actual result:** 

https://user-images.githubusercontent.com/17010094/175531502-7497fcd3-858f-48e8-bd87-e12b4cd0cb29.MP4

**Expected result:**
Should only have interaction once.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40 (22.6.23.15)

**Device details:** 
iPad Pro (iOS 15.63 Beta)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
This one appears to be the 1inch.io dapp sending an [`enable` method](https://docs.metamask.io/guide/ethereum-provider.html#ethereum-enable-deprecated) after we reply with a rejection to the initial `eth_requestAccounts` which prompts us to show the permissions request a second time (because no permissions we granted for this dapp site yet, we show a permissions request).

ex.
We receive a `eth_requestAccounts` request -> we show permissions request to connect accounts to `1inch.io`.
User taps 'cancel' -> we reply with a rejection response to the permissions request.
We receive a `enable` method -> we show permissions request to connect accounts to `1inch.io`.

This behaves the same as desktop currently.

https://user-images.githubusercontent.com/5314553/175547479-8b82fc38-4669-4d5c-b546-755660b682c6.mov
