### ISSUE TITLE
Sign using wallet fails immediately after connecting to wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5582]
### Description: 
Sign using wallet fails immediately after connecting to wallet

### Steps to Reproduce 
  1. Create a wallet on clean install
  2. Connect wallet to `https://metamask.github.io/test-dapp`
  3. Scroll down and click on `Sign` under `Eth Sign`, throws error
  4. Click on `Sign` under `Personal Sign`
  5. Reload the page and try to `Sign` under `Eth Sign`, works this time
  6. Click on `Sign` under `Personal Sign` again, still fails
  7. Reload the page second time and `Sign` under `Personal Sign`, this brings up the modal correctly 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/175532125-54a324a3-0c4a-4553-9b88-bd4a22fb269f.MP4

**Expected result:**
Should be able to sign without reloading the pages

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy 

**Brave Version:** 
1.40 (22.6.23.15)

**Device details:** 
iPad Pro (iOS 15.6)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
Still debugging this issue but adding some more information.

After initially connecting to the MetaMask test dapp site and then (without refreshing the page) tapping 'Sign' for 'Eth Sign' we receive the `eth_sign` request with the following parameters: `["0","0x879a053d4800c6354e76c7985a865d2922c82fb5b3f4577b2fe08b998954f2e0"]`.

This signature request is _supposed_ to have the currently selected account address as the first value in the array (the second value is the message). We fail this request due to invalid parameters.

After reloading the page, seeing we are still connected to this dapp site (wallet is unlocked + ethereum permissions still granted), then tapping 'Sign' for 'Eth Sign' we receive the `eth_sign` request with the following parameters: `["0x882F5a2c1C429e6592D801486566D0753BC1dD04","0x879a053d4800c6354e76c7985a865d2922c82fb5b3f4577b2fe08b998954f2e0"]`

This signature request now correctly provides the right selected account address as the first value in the array. We successfully display this request.

So we are emitting the `accountsChanged` event with the newly connected account after the user connects. The site correctly displays this account address below the 'connect' button. But we are missing _some_ step that updates the address used for the `eth_sign` and `personal_sign` requests on this dapp site (this flow is working on desktop without a refresh).

**Comment by StephenHeaps** [comment]
Resolved with https://github.com/brave/brave-ios/pull/7029

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.15.17)
- Verified steps from issue description
- Verified able to submit Sign transactions without issues 

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/225562410-2010d5e4-3013-4734-80be-b2d866d9e520.MP4> | <video src=https://user-images.githubusercontent.com/17010094/225562710-42b46699-ff70-4436-841a-26deb980dbc3.MP4> | <video src=https://user-images.githubusercontent.com/17010094/225563672-b7da514d-aedd-4b72-9c62-657c2d773466.MP4>
