### ISSUE TITLE
Wallet panel should be closed when wallet icon is removed from URL bar during page reload

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5616]
### Description: 
Wallet panel should be closed when wallet icon is removed from URL bar during page reload

### Steps to Reproduce 
  1. Connect to a `app.1inch.io`
  2. Select notification so Panel opens up 
  3. Connect wallet
  4. Change network on Dapp
  5. Triggers wallet notificaiton
  6. Click on notification so wallet panel opens up
  7. Page reloads in background while panel is still open
  8. Panel remains open but wallet icon moves around causing the anchor to show in different place and when wallet icon is removed during page load wallet panel is still shown 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/176249021-1f0ecbea-d418-475d-88e1-3c1dce1cc6f8.MP4

**Expected result:**
Close panel when wallet icon is removed in URL bar during page load

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40

**Device details:** 
iPad Pro (iOS 15.6)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
As part of this fix, the wallet icon will no longer be hidden during a page reload so the wallet panel should no longer point to an empty position.

The anchor point is only off-centre of the wallet button by ~6pts during reload (due to size difference of reload/stop buttons). I think this is now a more minor issue than shown in the video above pointing to an empty position, and @kylehickinson is currently working on some UI updates to the top toolbar that may inadvertently fix this centring issue.
<img width="584" alt="Screen Shot 2022-07-08 at 1 04 16 PM" src="https://user-images.githubusercontent.com/5314553/178054282-a5cf23bb-5c47-4ccc-9c2a-6fd70fe65cdc.png">

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 16 running 1.41 (22.7.11.19)
- Verified steps from issue description & [#5667](https://github.com/brave/brave-ios/pull/5667)
- Verified wallet icon is not remove during page reload and hence doesn't cause the panel to be open without a wallet icon
- Still see the anchor position to be off as per [#5616 (comment)](https://github.com/brave/brave-ios/issues/5616#issuecomment-1179286539)

https://user-images.githubusercontent.com/17010094/178997921-678fc498-3522-45e4-bb7e-5110ca825bed.MP4
