### ISSUE TITLE
Saved passwords are not auto populated on desktop sites

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#571]
### Description: 
Saved passwords are not auto populated on desktop sites
### Steps to Reproduce 
  1. Visit https://mobile.twitter.com/
  2. Chang it to Desktop site
  3. Login to twitter in Desktop site
  4. A pop up displays to store password
  5. Click on Yes option
  6. Switch to mobile site, you can see twitter is already logged in
  7. Log out twitter in mobile site, login page is displayed with auto populated login credentials
  8. Switch to Desktop site, you can see login page with no autopopulated credentials
  

**Actual result:** 
Saved passwords are not auto populated on desktop sites

**Expected result:**
Saved credentials should auto populate for desktop site as well

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.7 (18.12.04.23)

**Device details:** 
iPhone 8 (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by kylehickinson** [comment]
This is due to the fact when saving passwords, the host includes any subdomains (in this case `mobile.`), so when you query saved login information for `twitter.com` it finds nothing as we only have login information for `mobile.twitter.com`.

To fix this we would either have to:
1. Save all logins with normalized hosts which don't include extra info such as subdomains & port if applicable
2. Query for partial host if nothing is found for the exact host

We could also put this behind a preference to allow the second option

Considering the nature of the ticket, it'd probably be best to get security to give a decision on this, I myself leaning towards not fixing this (especially given that passwords auto-fill)

**Comment by tildelowengrimm** [comment]
We talked about this at the security meeting. It would be totally fine to index passwords by scheme & eTLD+1 — like `https://*.twitter.com/*`. But if this change is made, it'll be really important to make sure that the eTLD+1 part is parsed right. Don't want to end up binding to `https://*.co.uk/*`.
