### ISSUE TITLE
Office.com becomes practically unusable on iPad (and maybe other devices)

### ISSUE THREAD

**Issue by nadav-bar-lev** [brave/brave-ios#6052]
### Description: 
Office.com becomes practically unusable on iPad (and maybe other devices)

### Steps to Reproduce 
  1. Browse to Office.com
  2. Login with a Microsoft account
  3. Click on Word/Excel/PowerPoint
  4. Repeat step 3 for 4-5 times

**Actual result:** 
The page becomes unresponsive and the UI freezes for a decent amount of seconds.
The page becomes laggy, freezes the UI for a few seconds and makes the use of Office.com practically impossible.

**Expected result:**
As per my comparison to other browsers, Google Chrome and Microsoft Edge (both Chromium based browsers) are able to render this webpage perfectly fine, providing the smooth and expected user experience I expected Brave to provide.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
App store version and local build from https://github.com/brave/brave-ios/commit/ef4650b888888dc6718a70c0cd999b51fbb30664 commit

**Device details:** 
Device: iPad Air and iPad Pro 3rd Generation / Simulator - iPad 9th Generation 
iOS: 15.6.1

**Website problems only:**
Also on Firefox
In Safari, however, the site loads after a few seconds and some components don't appear to be clickable or take a long time to respond (still better than Firefox and Brave but not good enough).

**Comment by Brandon-T** [comment]
**Hi** @nadav-bar-lev 

All browsers on iOS use `WebKit/Safari` engine, including Chrome and Edge, so they aren't doing anything that we aren't doing.

I have investigated and came the to the conclusion that this is not a Brave-iOS issue since it affects every browser except those using Chromium's User-Agent. 

This is a Microsoft issue.

---

**Tested on (4th Generation, iPad Pro, 15.5):** Safari, Brave, Firefox, Opera, etc. 
All of these browsers do NOT use `Chrome`'s `User-Agent`.
Every single one of them `freezes`.

If we set our User-Agent to be:
> Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) **CriOS**/106.0.5216.0 Mobile/15E148 Safari/604.1

Instead of:
> Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) **Version**/106.0.5216.0 Mobile/15E148 Safari/604.1

or Instead of:
> Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) **Brave**/106.0.5216.0 Mobile/15E148 Safari/604.1

The website will work just fine. In other words, the website is actually checking for `*CriOS*` and if it isn't, it's doing something it really shouldn't be doing!

I'll see what we can do to remedy the issue.

**Comment by nadav-bar-lev** [comment]
Hi @Brandon-T and thank you very much for the quick response.

I am trying to solve the problem at least for now.
I changed the mobile user-agent under UserAgentBuilder as you suggested, but my site still freezes. 
Would you be able to provide me with more details so I can, at least, temporarily avoid this issue?

Thanks!

**Comment by Brandon-T** [comment]
> I changed the mobile user-agent under UserAgentBuilder

**Hi** @nadav-bar-lev

You need to change the desktop user agent when on iPad. This is because pages on iPad load with the Desktop User-Agent by default, not the mobile one (same behaviour as Safari).

Alternatively you can change the mobile one, but then "Request Mobile Site" from the 3-dot menu when visiting the website.

**Comment by iccub** [comment]
I'm going to close this as there's not much we can do about it except for faking UA for this particular site.
We will try to contact Microsoft and tell them to not rely on user agent for their office suite website
