### ISSUE TITLE
Recent Search Auto-Fill should populate the text not the URL

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6109]
### Description: 

When a search is performed using quick search bar and recent search is populated with it. The Recent Search accessory icon should populated the URL bar with the search text not the url itself.

### Steps to Reproduce 
  1. Write test on URL bar
  2. Press one of the quick search engines from search bar
  3. Press arrow icon(accessory view to recent search)
  4. URL is populated in URL bar

**Actual result:** 

The url is populated in URL bar

https://user-images.githubusercontent.com/6643505/194124659-d6e65ac2-bf62-428c-a21d-59137fc36e98.MP4

**Expected result:**

The text of search keywords should be populated not the url

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easily reproduced

**Brave Version:** 

Any

**Device details:** 

Any

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by Uni-verse** [comment]
Verified on `1.45 (22.11.3.16)` using the following device(s):

iPhone 12 - iOS 16.1
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x & 15.x

Using STR from https://github.com/brave/brave-ios/issues/6109#issue-1398135515

- Verified tapping on the arrow icon in recent search history will populate search term rather than URL
- Verified using search history with bottom and top tab bar configuration

<table><tr><td>iPad</td><td>iPhone</td><tr>

<td>

https://user-images.githubusercontent.com/17885425/199779971-4bb723f1-b378-439c-af0a-6fadd7b8bc38.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/199779984-9775cc64-2a02-4b1c-a783-0fc862071ddc.mov

</td></tr></table>
