### ISSUE TITLE
With bottom bar & tab bars enabled, deleting tabs so that one remains creates a small gap at the bottom of NTP

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6124]
### Steps to Reproduce 
  1. Enable Tabs Bar visibility & Bottom bar
  2. Open 2 tabs
  3. Open tab switcher via tabs toolbar button and remove all but 1 tab
  4. Open the remaining tab

**Actual result:** There is a white gap where the tab bar used to be
**Expected result:** No gap
**Reproduces how often:** Easy
**Brave Version:** 1.44 Brave Dev

https://user-images.githubusercontent.com/529104/194596929-25fb8d12-4eef-40d9-93af-f01431a18b2d.mov

**Comment by Uni-verse** [comment]
Verified using `1.44 (22.10.13.13)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x

Using STR in https://github.com/brave/brave-ios/issues/6124#issue-1401389789

- Verified deleting tabs so that one remains will not leave gap at the bottom of NTP.

https://user-images.githubusercontent.com/17885425/195654843-965576a2-5c7f-4540-ab4d-4402cf691df1.MP4
