### ISSUE TITLE
Tab restores with a light grey / disabled close button

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6157]
### Description: 
- When restoring a tab on iPad, most of the time the tab will restore with a light grey / disabled color 'x' button to close the tab. The button still works as expected, but shows in disabled state.

### Steps to Reproduce 
  1. Open some website on iPad
  2. Fully close the app via app switcher
  3. Re-open Brave, observe light grey close button on the tab

**Actual result:** 

https://user-images.githubusercontent.com/5314553/195362906-0a218064-694d-4e9b-b274-ca0e389e9d85.mov

**Expected result:**

Correct color for tab close button

**Reproduces how often:** 

Easily reproduced

**Comment by soner-yuksel** [comment]
Did some tests on this so interestingly the problem is not with the tab close button it is related with the indicators that are used for overflowing.

And this is happening when no overflow is necessary and plus button is used (iPAD)


https://user-images.githubusercontent.com/6643505/197245636-bc530742-e2a5-4fe4-9642-db07dd37fdf1.mp4

**Comment by Uni-verse** [comment]
Verified using `1.45 (22.10.28.19)` on iPads running iPadOS 16.x & 15.x

- Confirmed unable to reproduce issue using STR from https://github.com/brave/brave-ios/issues/6157#issue-1406274026
- Ensured button button on tab is not grayed out/disabled after restoring tab.

![IMG_0739](https://user-images.githubusercontent.com/17885425/199770814-5e1ed83f-1373-4105-8c1b-8dcd02dacda0.PNG)
