### ISSUE TITLE
Trackers are not blocked with farbling enabled

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6192]
### Description: 
Trackers are not blocked with Farbling enabled. 1.44 adblock/farbling is behaving differently than on 1.43 when loading the browserleaks canvas farbling test page. 1.43 shows 2 blocked while 1.44 has 0 for some reason. 

URL: https://browserleaks.com/canvas

1.43.x | 1.44 (22.10.14.13)
-|-
![IMG_0133 2](https://user-images.githubusercontent.com/17885425/195955486-768e40f0-7618-449f-a00b-c6c1041091f1.PNG) | ![IMG_0135](https://user-images.githubusercontent.com/17885425/195955487-e6c5a4f6-279c-4754-a25c-fb35967a9caf.PNG)

### Steps to Reproduce 
  1. Clean install 1.44
  2. Navigate to https://browserleaks.com/canvas
  3. Open shields to monitor trackers

**Actual result:** 
0 Blocked

**Expected result:**
2 Blocked (1.43)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.44.x

**Device details:** 
iPhone
iOS 16, 15

**Comment by cuba** [comment]
It does't look like an issue with the fingerprinting code rather with the stats tracking. The same 0 is returned with fingerprinting on or off. However, things ARE being blocked but the stats don't show this.

<img width="948" alt="Screenshot 2022-11-24 at 5 42 28 PM" src="https://user-images.githubusercontent.com/909331/203833498-3e72651f-186e-4ba0-b6f4-cf26b4377724.png">

That being said, there are known mismatches between the stats and what we block sometimes because the stats and blocking are done using different mechanism due to iOS limitations (iOS content blocking system for the former and ad block rust engine for the latter)

**Comment by cuba** [comment]
Found the issue. The tracking stats handler is not communicating back with the iOS side. So we only show stats for a small subset of blocked trackers. Should have a fix relatively soon.

**Comment by xSuave** [comment]
I'm experiencing the same issue on IOS

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.13.0)` on the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x

- Verified trackers are blocked with farbling enabled on test page `browserleaks.com/canvas`
- Verified shields are showing trackers/ads blocked across the web

Example | Example
-|-
![IMG_4227](https://user-images.githubusercontent.com/17885425/207465891-7debde8a-1949-47cb-ab60-b3c5f5841e5a.PNG) | ![IMG_0869](https://user-images.githubusercontent.com/17885425/207465908-0b369b3f-d5c9-4009-9066-b369429feafb.PNG)
