### ISSUE TITLE
Misleading Signing Request Message (BRA-Q322-7)

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6277]
ref: 
https://github.com/brave/brave-browser/issues/24816

**Comment by srirambv** [comment]
Verification passed on iPhone 14 Pro simulator running development build. Note verification is done on simulator since it is not possible to pass JS commands on a TF build
- Verified when non-ASCII code is passed in Sign transaction, a warning message is show 
- Verified clicking on `View message in ASCII encoding` shows the ASCII code in message
- Verified clicking on `View original message` shows the encoded message

https://user-images.githubusercontent.com/17010094/201599370-0c291ea8-45bd-43dd-8108-e59d7c755431.mp4
