### ISSUE TITLE
Partner search + Browser lock popup appear on settings after turning on "Private Browsing Only" mode

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#637]
- Fresh install
- Open settings
- Turn on PBO

![simulator screen shot - iphone x - 2018-12-14 at 16 06 18](https://user-images.githubusercontent.com/529104/50093959-08981f00-01e0-11e9-8e76-9059f6d7293c.png)

Private mode popups are showing up even in settings

**Comment by LaurenWags** [comment]
@jhreis @kylehickinson I don't get the DDG or Pin modals until I open a second tab in PBO mode. Is that expected? Using an iPad for reference.
Steps to Reproduce:
Clean install of 1.7.2 (19.1.15.15)
Open Settings
Enable Private Browsing Only.
Close Settings by tapping on Done --> no modals observed on Settings or Private tab.
Navigate to a site in the existing tab, navigation to site occurs without issue.
Open a new tab --> Modals display (DDG modal then Pin modal)

For contrast, this is what happens when I open Private mode for the first time:
Clean install of 1.7.2 (19.1.15.15)
Tap on Tab count icon
Tap on Private
Tap on + to open a Private tab --> DDG modal is displayed followed by PIN modal
cc @srirambv

**Comment by kylehickinson** [comment]
> Close Settings by tapping on Done --> no modals observed on Settings or Private tab. 

Hmm, no this isn't expected. I did test in the past and got the modal to appear when tapping done. It may an iPad only bug, I'll double check.

**Comment by srirambv** [comment]
Issue reproduced on my iPad as well. Enabling PB only mode from setting doesn't show the DDG modal. Opening a new tab shows it. Opening private tab from tab tray shows DDG modal instantly.

**Comment by GeetaSarvadnya** [comment]
Verified the issue on iPhone 8 (12.1.2). I am getting the DDG modal after tapping Done. Here is the recorded file.

https://drive.google.com/open?id=1kYZV7YXMOXJLRuVpa3ryJLAAKTLxdacg

Verified issue on iPad 5th Gen using 1.7.2 (19.1.16.16)

**Comment by srirambv** [comment]
Verification passed on iPhone 6 
* DDG/Pin modal shows up when a link is opened in a new private tab for the first time
* DDG/Pin modal shows up when a private tab is opened via tabs tray
* DDG/Pin modal shows up when PB only mode is set and settings page is closed
