### ISSUE TITLE
Custom Tokens shown in Portfolio when deselected in Edit User Assets

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6386]
### Description: 

Custom tokens are always displayed in Portfolio, regardless of Visible state / selected in Edit User Assets

### Steps to Reproduce 
  1. Add custom token that is not in our token registry (entering contract address shouldn't pre-fill). Ex. https://www.coingecko.com/en/coins/meta-space-2045
  2. Open Edit User Assets modal and deselect the token (ex. Meta Space 2045 / MTW)
  3.Observe token is still displayed in Portfolio

**Actual result:** 

Token is displayed in Portfolio after deselecting in Edit User Assets

**Expected result:**

Token is not displayed in Portfolio after deselecting in Edit User Assets

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.6.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6388](https://github.com/brave/brave-ios/pull/6388)
- Verified unchecking the token from visible asset list hides the token in portfolio

https://user-images.githubusercontent.com/17010094/204006874-a564c704-9ed4-46f1-a497-23b1a72dbe8d.MP4

-------------
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6388](https://github.com/brave/brave-ios/pull/6388)
- Verified unchecking the token from visible asset list hides the token in portfolio

https://user-images.githubusercontent.com/17010094/204006915-8e5675b0-f1e7-4116-8e29-7329face01a7.MP4

------------
Verification on iPad failed due to #6491
