### ISSUE TITLE
Search results links from Bing.com are not opening in Private and Normal mode

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#648]
### Description: 
Search results links from Bing.com are not opening in Private and Normal mode

### Steps to Reproduce 
  1. Open Brave 
  2. Navigate to bing.com and do a search
  3. Try and open a search result

**Actual result:** 
Error page

**Expected result:**
User should link to the correct page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:**
1.7

**Device details:** 
all iOS

**Website problems only:**
When shields are down the links open fine

### Additional Information 

<img width="437" alt="screen shot 2018-12-18 at 11 15 19 am" src="https://user-images.githubusercontent.com/7606853/50177330-9cd4b580-02b6-11e9-807d-d86440db7c0f.png">

![links](https://user-images.githubusercontent.com/7606853/50177349-a2ca9680-02b6-11e9-960e-b5021746e803.gif)

**Comment by kylehickinson** [comment]
This is due to the rule: `||bing.com/fd/ls/$~ping` which is converted to this content blocker:

```json
[{
    "trigger": {
        "url-filter": "^[^:]+:(//)?([^/]+.)?bing\\.com/fd/ls/",
        "resource-type": [
            "document",
            "image",
            "style-sheet",
            "script",
            "font",
            "raw",
            "media"
        ]
    },
    "action": {
        "type": "block"
    }
}]
```

Content blockers don't support the `$ping` option but since its negated it technically enables all resource types. This may not be entirely correct, `document` may need to be removed from the generated output as `document` considers the actual page and `subdocument` doesn't exist in Safari Content Blockers... Needs a bit more investigation but a workaround is to remove `document` from the list of content types blocked.
