### ISSUE TITLE
Wallet: NFT detail copy updates and disclaimer for SVG image

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6553]
1. change the copy of the button from `Send NFT` to `Send`
2. add a disclaimer at the bottom of the screen when image is in svg format. "The image rendered above may not exactly match the NFT"

![simulator_screenshot_4ED3CF7D-3694-49F2-92A0-8DAC6A4B7DCB](https://user-images.githubusercontent.com/1187676/205757523-9e51346c-54e7-4d6c-8371-3d7a7f95abc0.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46 (22.12.7.22)
- Verified steps from [#6555](https://github.com/brave/brave-ios/pull/6555)
- Verified SVG image in NFT shows message at the bottom NFT details screen
- Verified button now says `Send` instead of `Send NFT` 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<img width=300 src=https://user-images.githubusercontent.com/17010094/206483791-1b8e9fa8-6f47-4b59-ac86-bf466a1f1d36.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/206483758-06d244f8-c02b-4b80-9e67-25a70edad41f.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/206483705-fdec510e-21e6-4c2a-b2d2-d229d978c149.png>
