### ISSUE TITLE
Implement Solana support for "The Wallet Standard" 

### ISSUE THREAD

**Issue by bbondy** [brave/brave-ios#6638]
Mirror issue for brave-core's https://github.com/brave/brave-browser/issues/27340
I'd wait for the brave-core implementation before doing it on iOS.

This is needed by the end of Q1. 

cc @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
Closed with BraveCore v1.47.179 bump: https://github.com/brave/brave-ios/pull/6812

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.7.1 running 1.47 (23.1.30.21)
- Verified test plan from [#6852](https://github.com/brave/brave-ios/pull/6852)
- Verified Brave Wallet is not displayed in 'Select Wallet' drop down when wallet is not created
- Verified after creating wallet and running through it again lists Brave Wallet
- Verified Legacy Transaction and V0 transaction buttons are greyed out since its not supported
- Verified  able to submit `SignTransaction`, `SignMessage` and `SendTransaction`

https://user-images.githubusercontent.com/17010094/216067271-77547301-5446-48b8-837f-e85e312d8119.mp4
