### ISSUE TITLE
Allow users navigate to .sol domains

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6706]
### Description: 

iOS version of https://github.com/brave/brave-browser/issues/26652

Complete the native resolution of SNS records inside Brave’s browser. There should be a preference in settings for `Resolve Solana Name Service (SNS) domain names` with `Ask` (default) / `Enabled` / `Disabled` options. `Ask` should show interstitial page:

<img width="685" alt="Screenshot 2023-01-05 at 3 21 45 PM" src="https://user-images.githubusercontent.com/5314553/210872846-7bdfd498-d658-47aa-b172-30b644c02ad8.png">

ref: https://github.com/brave/brave-ios/issues/6639

**Comment by ozyman42** [comment]
Where does the DNS config of these sol domains live?

**Comment by rmcfadden3** [comment]
@jamesmudgett — you mean something like this?

Header: `Enable support of Solana Name Service (SNS) in Brave?`

Body: `Brave will use a third-party provider to resolve .sol domains, but will still hide your IP address. If you enable Solana Name Service (SNS), our third-party provider will see that someone is trying to visit these .sol domains, but nothing else.`

CTA: `Proceed using third-party provider`

Removed mention of CB ToU and Privacy Policy, since seems like that would no longer apply. But LMK if we have our own pages we'd want to link there instead.

**Comment by nuo-xu** [comment]
new copies and links can be followed here https://github.com/brave/brave-browser/issues/28282

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.3.16)
- Verified steps from [#6906](https://github.com/brave/brave-ios/pull/6906)
- Verified new setting for resolving `.sol` domain is available under Web3 settings
- Verified setting is defaulted to `Ask` 
- Verified visiting a `.sol` domain shows an interstitial page
- Verified selecting `Proceed using Syndica Server` on interstitial page loads the page and sets the setting to `Enabled`
- Verified selecting `Disable` on interstitial page loads the page and sets the setting to `Disabled`

iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 2)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/223110380-00832c19-5b7e-44fc-9ead-4bd7fd7dd636.MP4> | <video src=https://user-images.githubusercontent.com/17010094/223112459-ac4b0ba1-babe-4a82-8ced-51d0919d5340.MP4>
