### ISSUE TITLE
Show only supported provider per selected coin to buy

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-ios#6712]
### Description: 
Ramp is being shown to buy assets from other networks. e.g. Selecting "WBTC" showing "Ramp" as an option to buy, but selecting Ramp leads to error page on Ramp network site.

### Actual result: 

https://user-images.githubusercontent.com/11755381/210980421-ed77e739-bbd0-48ee-905b-0cbc3330b3ad.MP4

### Expected result:
Show only supported networks.

### Version
1.47 (23.1.4.10)

### Additional info
It could be resolved with the implementation of [wyre removal](https://github.com/brave/brave-ios/issues/6683) but other provider can affect.

Updated example: Tether USD is not supported by Sardine on Solana and selection of Sardine with Tether will show infinite loading.

**Comment by nuo-xu** [comment]
Update:
the initial repro steps are no longer valid since we have removed wyre provider.
But bug still persists as TUSD token in solana selected network would give user Sardine provider option which is wrong. 
steps:
1. make sure device region is US to enable Sardine provider
2. open wallet and go to buy 
3. make sure selected network is solana
4. open available token list
5. select TUSD
6. click select purchase method button 
7. observe sardine is available 
8. continue click on sardine
9. observe it will redirect user to a new tab with sardine webpage. but the token is eth since TUSD is not supported on sardine.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48 (23.2.22.16)
- Verified steps from [#6712 (comment)](https://github.com/brave/brave-ios/issues/6712#issuecomment-1412792533)
- Verified only supported tokens are shown

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (iOS 16.3)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/220706491-be6d3133-e395-4ab0-a285-c7b6750409dc.MP4> | <video src=https://user-images.githubusercontent.com/17010094/220706940-cb2e9a5b-ece0-4dc6-b219-b87db455873b.MP4> | <video src=https://user-images.githubusercontent.com/17010094/220708890-100f4fe3-b416-453c-a536-3509e9f46b5f.MP4>
