### ISSUE TITLE
Blocking search URL's that are served Ads

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#675]
### Description: 
We are blocking search ads that users may click on. 

Example, a user may search for an iPhone 8 case. Many results are displayed. Some are ads. If a user clicks on the ad link the page won't open  

### Steps to Reproduce 
  1. Open Brave
  2. Go to google.com or any search engine 
  3. Search for an item and click on the results

**Actual result:** 
see video attached

**Expected result:**
-> I think these links should open. They users requested it and should get it. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
always

**Brave Version:** 
1.7.1

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
 Yes

### Additional Information 

![bug](https://user-images.githubusercontent.com/7606853/50710159-12fb4b00-101f-11e9-95bc-4e83a60b5618.gif)

**Comment by kylehickinson** [comment]
**Offending URL**: `https://www.google.com/aclk?sa=l&ai=DChcSEwiw2p6G9tvfAhUKhMgKHU2GCO4YABABGgJxdQ&sig=AOD64_1MWfi8v_swZGNoOIsjKYSqtSZiXw&ctype=5&q=&ved=0ahUKEwjWj5uG9tvfAhWynuAKHXSSAFYQrkMIHA&adurl=` 
**which redirects to:** `https://www.googleadservices.com/pagead/aclk?sa=L&ai=CtFxhrmczXLDLA4qIogbNjKLwDrGev89NrdHs9rcCloOjs_QBCAkQASCrr_ocYP2gmYHoA6ABsMC74wPIAQeqBDdP0C1AxyWRTFSjjR6yfid1NHlEp8-NqsIy1lCSXt5uhZdbGSUkWI4rQD27YRkcfdd7MmNfsy9vwAS11OjfVogF9Zu4oAHABQWgBibYBgKAB7W-9UGQBwOoB6a-G6gH2csbqAfPzBvYBwGgCICwpQSwCAHACAH4CQHgEsSy2N_W_Ki5W4IUBAgAEgA&ctype=5&ved=0ahUKEwjWj5uG9tvfAhWynuAKHXSSAFYQrkMIHA&dblrd=1&val=Ggj3c1YleBJwCiABKAAwis2764HzqYusATjyzs3hBUCHz83hBQ&sig=AOD64_1D4s8OgUz6WDbj4S2pQsxpuTKwdw&adurl=https://www.groupon.com/deals/gg-ca-parliament-st-slim-iphone-8-case%3Fdeal_option%3D54d19370-6e66-4fdf-8534-79d0bc939302%26utm_source%3DGoogle%26utm_medium%3Dcpc%26utm_campaign%3DCA_DT_SEA_GGL_TIM_TTT_PADS_CBP_CHP_NBR_g*gg-ca-xtreme-two-outlet-dual-usb-wall-charger-1_c*83720971237_k*_m*_d*Goods-Product-Ads_mobile*true_keyword*_target*_adposition*1o1_prodtarget*65605779862_adtype*pla_merchantdid*10018412_productid*65556675_productpartitionid*65605779862_campaignid*336465397_adgroupid*23286393397%26mr:trackingCode%3D3C3B3B68-83B0-E711-8101-005056944E17%26mr:referralID%3DNA%26mr:device%3Dm%26mr:adType%3Dplaonline%26mr:ad%3D83720971237%26mr:keyword%3D%26mr:match%3D%26mr:tid%3Dpla-65605779862%26mr:ploc%3D9000960%26mr:iloc%3D%26mr:store%3D%26mr:filter%3D65605779862`

**Offending rule**: `&adurl=`

**Converted rule**:
```json
{
    "trigger": {
        "url-filter": "&adurl="
    },
    "action": {
        "type": "block"
    }
},
```

The reason why disabling shields does not work is due to the redirecting. The initial load is `google.com`, which even if succeeding due to disabling shields for `google.com` fails at loading `googleadservices.com` which you can't disable shields for from the error page.

**Comment by kylehickinson** [comment]
Further investigation shows that it is the iOS SDK which is giving us the incorrect failing URL: 

https://github.com/brave/brave-ios/blob/12ddacc49dd765f089c4aa7298dda8168048e9db/Client/Frontend/Browser/BrowserViewController.swift#L2195-L2196

The original load of `google.com` fails because its redirect fails.

**Comment by srirambv** [comment]
Verification passed on iPhone 7
![ezgif com-gif-maker](https://user-images.githubusercontent.com/17010094/53079733-15592c00-351d-11e9-8468-c8fc6c8f658e.gif)
