### ISSUE TITLE
Browser chrome for dark theme needs to be darker

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-ios#6839]
Dark theme base color is still too bright. We're investigating the color. @kylehickinson please confirm what % of alpha channel we currently apply to the chrome so we can select the right one to produce the desired resulting chrome color.

*non-critical but low hanging fruit issue.  if we can make the change quickly, let's do it. 

cc @aguscruiz  @anthonypkeane  @timchilds

**Comment by kylehickinson** [comment]
@jenn-rhim Can you confirm what dark theme base color you are referring too? 

We have 3 background colors from the original design system: `#17171F`, `#1E1F29` and `#3B3E4F`.

We use the last one (`#3B3E4F`) for the URL bar/toolbar backgrounds because it most closest matches desktop but the rest use the first 2 for backgrounds
