### ISSUE TITLE
Changing network auto  closes the buy screen and shows pending tx

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-ios#6860]
### Description: 
Changing network auto closes the buy screen and shows pending tx

### Steps to Reproduce:
1. Have a pending transaction on an EVM like Goerli Test Network (Goerli must be the last selected Ethereum network).
2. Have a Solana Mainnet selected (you may have to close wallet after selecting Solana Mainnet to 'reset' wallet state). This network should appear in buy/send/swap (not Goerli, which is selected for Eth coin type).
3. Re-open Wallet if not open
4. Dismiss the pending transaction on Goerli Test Network (don't reject / confirm).
5. Open Buy token view.
6. Change network from Solana to Sepolia Test Network (not the EVM you have pending tx on in step 1).
7. Buy token view is automatically dismissed

https://user-images.githubusercontent.com/11755381/216331259-5a35a33e-5895-4441-b0e3-ecc49f8788a0.MP4

### Expected result:
 Buy screen should stay open

@nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
I found a directly related issue that will be resolved with this fix. The bug results in the user being unable to open buy/send/swap and/or pending transactions until they close and re-open wallet.

1. Have a pending transaction on an EVM like Goerli Test Network
2. Have a Solana Mainnet selected (you may have to close wallet after selecting Solana Mainnet to 'reset' state)
3. Re-open Wallet if not open
4. Dismiss the pending transaction on Goerli Test Network (don't reject / confirm).
5. Open Buy token view.
6. Change network from Solana Mainnet to Goerli Test Network.
7. Verify buy/send/swap is not dismiss. Verify you can swipe to dismiss buy/send/swap and open the pending transaction and/or re-open buy/send/swap

These are the same as above steps, but selecting the Ethereum network **with** the pending transaction, rather than a different network.

https://user-images.githubusercontent.com/5314553/216721403-d02d1cd9-87f9-4de2-8022-2da7056c6587.mov

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.7.1 running 1.48 (23.2.16.18)
- Verified steps from [#6878](https://github.com/brave/brave-ios/issues/6878)
- Verified buy button is not dismissed when changing network 
- Verified able to swipe to dismiss buy/send/swap and open the pending transaction and/or re-open buy/send/swap

<video src=https://user-images.githubusercontent.com/17010094/219720217-956c1daa-e1b3-4fc7-9667-d5679c76810c.MP4> | <video src=https://user-images.githubusercontent.com/17010094/219720295-0bad177b-515c-4e34-9c34-cff45cd6a58a.MP4> | <video src=https://user-images.githubusercontent.com/17010094/219720365-586492a2-6a73-4d85-b4c4-f1d1b6d40095.MP4>
-- | -- | --
