### ISSUE TITLE
Cannot paste in Find in Page

### ISSUE THREAD

**Issue by HyperLemons** [brave/brave-ios#6920]
### Description: 
This has been going on for quite a while but it reached my breaking point today, and I'm not eager to go download some "paste keyboard" app made just to mitigate this anymore.

### Steps to Reproduce 
  1. Open any website with text
  2. Open the options tab (the three dots on the bottom right)
  3. Open Find in Page
  4. Attempt to paste anything in the text box

### Expected result:
Should just be able to paste like normal

### Brave Version: 1.47 

- Can you reproduce this issue with the most recent build from TestFlight? **I don't have the TestFlight but I don't see any issues or fixes for this in the repository**
- Can you reproduce this issue with the previous version of the current build from TestFlight? **Same answer to previous question**
- Can you reproduce this issue with the current build from AppStore? **Yes**

### Website problems only:
- did you check with Brave Shields down? Yep
- did you check in Safari/Firefox (WkWebView-based browsers)? Works quite perfectly on latest Firefox AppStore build (version 109)
### Additional Information
I've tried this on other webpages, and I know this has existed for a few updates like I said earlier, just no idea when it broke.

**Comment by soner-yuksel** [comment]
This is a Intermittent Pasteboard bug started with iOS 15, this problem is happening in various of apps and even in Safari. there is a radar created for this problem and it is reported to Apple. This is bug in OS itself. Pasting sometimes is giving unauthorized errors and the pasteboard will LOSE the text, and it will be empty. In that case, both the URL and String API fails.

@HyperLemons as an alternative you can use “Find in Page” menu item. The action menu when you long press inside a text in webview. There are arrows on the side If you check the item you can find "Find In Page", it will do copy properly.

cc @iccub
