### ISSUE TITLE
Playlist Folder reordering does not work

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6961]
### Description: 
Reported here https://community.brave.com/t/bug-rearranging-playlist-folders-no-longer-possible-on-ios-and-ipados/464411/3

### Steps to Reproduce 
  1. Create few custom folders
  2. Reorder them
  3. Close playlist and go back to the playlist again

### Actual result: 
Folders did not move

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using `1.49 (23.3.21.15)` on the following device(s):

`iPhone XR`, `iOS 15.5`
`iPad (7th Gen)`, `iPadOS 16.3.1`

Based on STR in https://github.com/brave/brave-ios/issues/6961#issue-1588177701

- Ensured reordering Playlist folders is working

https://user-images.githubusercontent.com/17885425/227246506-04c17428-a33d-4c84-a4db-edc9b6d498d9.MP4

**Comment by oldmanlarsson** [comment]
@Uni-verse @iccub @Brandon-T 

Just wanted to let you know this issue was not resolved properly. 

The fix for this bug replaced the position of the folder below the position where you drag-and-dropped your folder to. 
So instead of rearranging the folders, 2 folders switch positions.
![image](https://user-images.githubusercontent.com/96598132/232768424-5d10c324-1d94-4a48-9513-24641f6ac235.png)

-------------------------------------------------

**I see 2 bugs here**
Bug 1. The rearrangement does not work as intended. 
Bug 2. When you drag-and-drop the folders is not updated on screen. You have to exit playlist or scroll the new folder position out of view to see the updates.

-------------------------------------------------

**Tested on**
iPhone XR, iOS 15.5
iPad (7th Gen), iPadOS 16.3.1

-------------------------------------------------

**How to reproduce**

1. Create folders named 1, 2, 3, 4, 5, 6, 7, 8, 9 and 10 in order. (I recommend thet you create as many folders that is needed for you to require to scroll to see the all)

2. Drag folder "5" above folder "1"

3. Now you should see that the folder names is not updated properly on screen (Bug 2)

4. Now exit playlist and open it again OR scroll the updated folder of view and in to view to see the updates in folderposition

5. You should now also see (Bug 1). The folder switches position instead of rearranging them.

Kind regards
PL
