### ISSUE TITLE
Don't show Solana account creation after onboarding from Solana dapp request

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7092]
### Description: 

When a user tries to connect to a Solana Dapp without a wallet setup, we should not show Solana account creation after onboarding (a Solana account is created during onboarding).

### Steps to Reproduce 
  1. Start with device without wallet setup or reset your wallet 
  2. Visit `jup.ag` or another Solana DApp site
  3. Tap 'Connect Wallet' and setup a wallet
  4. Observe prompt to create Solana account. Shouldn't be shown when Solana account is created with onboarding.

### Actual result: 

https://user-images.githubusercontent.com/5314553/225100883-f8d9b395-4a2d-4076-87ff-5601dd6f98e5.mov

### Expected result:

Does not show 'Add Solana Account' modal after onboarding

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.23.15)
- Verified steps from [#7097](https://github.com/brave/brave-ios/pull/7097)
- Verified Account creation is shown only on an upgrade profile where Solana account was not created
- Verified on clean install shows onboarding rather than add account 

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 4)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/227571386-43e02868-2cbe-459f-b38b-68f014410ad2.MP4> | <video src=https://user-images.githubusercontent.com/17010094/227571488-f2089973-b6e5-4f7f-9256-36b46e74552f.MP4> | <video src=https://user-images.githubusercontent.com/17010094/227571286-2205867d-2345-468b-924b-ac22ed60e1f8.MP4>
