### ISSUE TITLE
Show network logo over asset icon instead of coin logo

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7123]
### Description: 

iOS version of https://github.com/brave/brave-browser/issues/29166

We should update to show the network logo in the corner of asset icons instead of the coin logo.

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Version: 1.51 (23.5.8.16) 
BraveCore: 1.51.110 (113.0.5672.77)
```

**STEPS:**
1. Launch Brave > Three dot Menu > Wallet
2. Enter Wallet password > Unlock
3. Tap  `All Networks` > Change it to `Solana` > Verify 
4. Repeat Step 3 and change it to a few different Networks > Verify

**ACTUAL RESULTS:**
- Verified that the Network logo is shown in the corner of asset icons instead of the coin logo


https://user-images.githubusercontent.com/128532965/236936552-3426ead4-c2fb-4a20-89c9-8312410f3fe8.mov
