### ISSUE TITLE
Brave Search fallback encoding bug

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7170]
### Steps to Reproduce 
  1.
  2.
  3.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified, the issue is not reproducible in build 1.50. When "Google fallback mixing" is On, both search results from app search bar and website search bar are the same.

------------------

```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Brave build: 1.50 (23.4.19.20)
```

Screenshot/Screencast:

https://user-images.githubusercontent.com/128532965/233210587-5e1bf29a-67fb-4d00-bf2a-15a03af33079.mov
