### ISSUE TITLE
Sync UI Updates

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#719]
Update Sync UI and strings
![sync](https://user-images.githubusercontent.com/318119/51150468-45752700-181b-11e9-9424-d01526da69f5.png)
[sync_ios.zip](https://github.com/brave/brave-ios/files/2757614/sync_ios.zip)

Specs - 
[Mobile Sync Updates.pdf](https://github.com/brave/brave-ios/files/2770209/Mobile.Sync.Updates.pdf)

**Comment by jamesmudgett** [comment]
Paste icon - 
[paste.zip](https://github.com/brave/brave-ios/files/2766637/paste.zip)

**Comment by LaurenWags** [comment]
@jamesmudgett Settings shows Sync, not Brave Sync, expected? Generally there are inconsistencies with the screenshots above, are there more updated screens somewhere?

**Comment by iccub** [comment]
You are right @LaurenWags, I talked to the designers team and we will change it to `Brave Sync`
However this will go out after 1.9 release, as this string needs to be translated

Added a ticket here https://github.com/brave/brave-ios/issues/973

**Comment by GeetaSarvadnya** [comment]
@iccub There are few discrepancies between the above-proposed screenshots and sync screens in 1.9 (19.03.25.21) - which are listed below, will these be addressed in #973?

![QR Scan screen](https://user-images.githubusercontent.com/38657976/55000598-db39e900-4ff8-11e9-8085-32b07777198e.png)
![enter sync code word screen](https://user-images.githubusercontent.com/38657976/55000604-dffe9d00-4ff8-11e9-8b2b-66da7b356e00.png)
![brave sync setup screen](https://user-images.githubusercontent.com/38657976/55000614-e3922400-4ff8-11e9-9168-0002cf683471.png)
![Settings page](https://user-images.githubusercontent.com/38657976/55000620-e725ab00-4ff8-11e9-9f84-06343a23b186.png)

**Comment by iccub** [comment]
@GeetaSarvadnya I will let @anthonypkeane to answer this

**Comment by iccub** [comment]
Strings with `Sync/Sync beta` will be fixed in https://github.com/brave/brave-ios/issues/973
`I have a sync code` string is correct, please look at updated version of spec here https://github.com/brave/brave-ios/files/2770209/Mobile.Sync.Updates.pdf

Remaining strings are wrong and will be fixed in this PR https://github.com/brave/brave-ios/pull/1003

**Comment by kjozwiak** [comment]
@iccub assuming these changes haven't made it into `1.9 (19.03.25.21)` as https://github.com/brave/brave-ios/pull/1003 is still opened? Are we going to be getting another RC build that will include the changes from https://github.com/brave/brave-ios/pull/1003?

**Comment by iccub** [comment]
@jhreis please decide on that ^

**Comment by srirambv** [comment]
String changes can be put in 1.10. Don't want to hold on the release for text changes.

**Comment by srirambv** [comment]
Blocked on #973

**Comment by LaurenWags** [comment]
@jamesmudgett @jhreis @iccub a few questions about this:
1. noticing some inconsistencies in strings/wording in various places. is this expected? not sure if the image from the original description has been changed intentionally. Happy to log follow up issues if desired.
2. the two images at the bottom of the original description - are they supposed to be how these screens display on an iPad? because that's not currently the case. (see below, I put blue rectangles around the images I'm asking about) again - can log follow ups, just wasn't sure if original design had changed.
![Screen Shot 2019-07-16 at 3 33 08 PM](https://user-images.githubusercontent.com/28145373/61324080-90c6bd00-a7df-11e9-9191-885571fa50b4.png)

**Comment by jamesmudgett** [comment]
@LaurenWags since iPad is currently displaying sync modally (smaller window) it will appear similar to iPhone which is OK.

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.16.23)
   - Verified Sync UI per image in description (making exceptions for changes noted in this release).
   - Logged two follow up issues for minor inconsistencies in wording and tagged @anthonypkeane to review the issues: #1273 and #1274
* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`

**Comment by kjozwiak** [comment]
@jhreis @jamesmudgett should this be placed into the `1.10` ZenHub release rather than the `Sync` release?

**Comment by kjozwiak** [comment]
@EyanGoldman @anthonypkeane mind quickly going through this on a `iPhone X` to make sure the UX/layout looks correct?

**Comment by EyanGoldman** [comment]
No issues regarding notch compatibility. Looks good on the iPhone X
