### ISSUE TITLE
Wallet: Tweak transaction UI for Solana versioned transactions

### ISSUE THREAD

**Issue by yrliou** [brave/brave-ios#7211]
Please refer to https://github.com/brave/brave-browser/issues/29543 for all the details, thanks.

**Comment by StephenHeaps** [comment]
We will also need to update parts of the DApp communication layer for Solana on iOS.

The Solana Provider now returns a `version` / `versions` for `SignTransaction()` / `SignAllTransactions()` respectively, which should be initialized with the `solanaWeb3.VersionedTransaction` instead of `solanaWeb3.Transaction`.

On iOS, the brave-core Solana Provider is used in `SolanaProviderScriptHandler`:
https://github.com/brave/brave-ios/blob/brave-core-1.52.x/Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/SolanaProviderScriptHandler.swift#L254

We will need to pass the returned `version` / `versions` to the javascript and initialize as `solanaWeb3.VersionedTransaction` when the version is not legacy:
https://github.com/brave/brave-ios/blob/brave-core-1.52.x/Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/WalletSolanaProviderScript.js#L82-L84

Relevant desktop commit:
https://github.com/brave/brave-core/commit/e5c91186d07d55e6852db4e5ba9ed5676150f6aa

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.52 (23.6.1.15)
- Verified steps from [ #7508](https://github.com/brave/brave-ios/pull/7508)
- Verified All cases with v0 keyword in `https://pwgoom.csb.app` worked as expected
- Verified all three Send Transactions cases in the bottom row in `https://solana-labs.github.io/wallet-adapter/example/` worked as expected

https://github.com/brave/brave-ios/assets/17010094/f96eedd6-5b0a-4295-9af3-37754c9a4e1b
