### ISSUE TITLE
Some images/thumbnails not displaying with Shields up

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#7215]
### Description: 
It looks like Shields is breaking some images on certain sites for users on iOS 16.4 and Brave v1.48.1 — seeing this on [Mastodon.nl](http://mastodon.nl/) (images/preview images), [airbnb.com](http://airbnb.com/) (thumbnails) and a similar issue with this [Japanese Kanji site](https://www.kanshudo.com/collections/vocab_usefulness2021/UFN2021-1-101) (Kanji icons not appearing).

![image](https://user-images.githubusercontent.com/3299098/230447069-7f2a7202-7d28-41c7-af14-1b7f6e17ecdd.png)
![image](https://user-images.githubusercontent.com/3299098/230447265-3bba7e28-b499-4346-979b-873714edddcf.png)
![image](https://user-images.githubusercontent.com/3299098/230447566-4253e2d1-1f71-47cc-b919-075804a51194.png)

Note that the images do seem to display when Shields are turned off and there likely are other sites being affected by this.

### Steps to Reproduce 
  1. Visit site listed above 
  2. Observe images not displaying
  3. Turn Shields off and images appear

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced 

### Brave Version: 
v1.48.1
- Can you reproduce this issue with the most recent build from TestFlight? Y
- Can you reproduce this issue with the previous version of the current build from TestFlight? Y
- Can you reproduce this issue with the current build from AppStore? Y

### Device details: 
iPadOs and iOS 16.4

### Website problems only:
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes

### Additional Information
Initial threads:
https://community.brave.com/t/brave-doesnt-show-images-anymore-in-mastodon-since-today/480533/9
https://community.brave.com/t/brave-browser-ios-will-not-display-icons-text-email-bodies/480523

**Comment by Brave-Matt** [comment]
Update — it looks like allow cross-site trackers resolves the issue. cc @ryanbr

**Comment by Saoiray** [comment]
Want to advise that it's continuing even after update to 1.49 as well.

**Comment by iccub** [comment]
Should be fixed

**Comment by hffvld** [comment]
Verified, the issue is not reproducible in build 1.50. Checked with Shields On and Off.

------------------

```
Device/OS: iPhone 14 [iOS 16.41] and iPad Air [iPadOS 16.4.1]
Brave build: 1.50 (23.4.17.16)
```

<img width="473" alt="Screenshot 2023-04-17 at 16 41 28" src="https://user-images.githubusercontent.com/128532965/232636019-f424ae09-e3b1-49b7-8d75-a28ba8eaa5ec.png">
<img width="473" alt="Screenshot 2023-04-17 at 16 41 18" src="https://user-images.githubusercontent.com/128532965/232636030-ee758070-d926-4209-abf2-c9c38ef1d20b.png">
<img width="473" alt="Screenshot 2023-04-17 at 16 41 10" src="https://user-images.githubusercontent.com/128532965/232636047-e94c1c00-4eec-4812-8ee2-a3a59d901d75.png">
