### ISSUE TITLE
Device doesn't join sync chain

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#723]
### Description: 
Device doesn't join sync chain

### Steps to Reproduce 
  1. Clean install new beta build
  2. Create a sync chain on Desktop
  3. Scan QR code/Enter code words to join the sync chain
  4. Device shows the correct code words but doesn't list other devices in the chain and neither gets listed on other device

**Actual result:** 
Only iOS device is shown on the sycn chain 

**Expected result:**
iOS device should get listed on other devices on the chain and iOS should also list other devices on the chain 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7.3(193..01.14.19)

**Device details:** 
iPhone 7+ 
Linux 0.59.21
Android Sync build

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
This is because desktop and iOS use different endpoints for Sync server. This will get fixed in next beta build

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen using STR above
* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verified passed with 1.9 (19.3.9.1) on iPhone 8
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.

**Comment by changemenemo** [comment]
Hi, 
I don't know if it's totally related to this bug, but one of my iphones did join the sync chain but then it gave me an error message that the sync server or something wasn't available at the moment so I had to try later. 
On the other devices I did see the new phone. 
The only thing I could do (since there was no way to unsubscribe to the chain because of this error, and the removal of this devices from other devices didn't work, 
So the only thing I could do was to uninstall brave from the phone.
then I sync it up again and now it works.

The only problem is that I lost 70 tabs in the process. That would have been nice that there would have been a feature to export the tab list or the history. That would have been nice.... 

the build is and was 1.11.3(19.08.16.20) on iphone XR
