### ISSUE TITLE
Playlist plays a 1s (short chime) instead of the actual video that was added

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7345]
### Description: 
- When adding an item to Playlist, sometimes it adds a small "1s" audio instead of the actual video.

### Steps to Reproduce 
  1. Visit Youtube.com (easier to reproduce on iPad afaik)
  2. Add a video to Playlist
  3. Kill the app
  4. Launch playlist

### Actual result: 
- Video is replaced with a small audio clip

### Expected result:
- Should not replace the video with an audio clip. Video must be > 1s in time.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Intermittent Issue

### Brave Version: 

- 1.49.x

### Device details: 
- Any (but easier to reproduce on iPad)

### Website problems only:
- Youtube

**Comment by Uni-verse** [comment]
Verified on iPhone X running iOS 16.3.1 using version 1.50 (23.4.27.16)

Using STR in https://github.com/brave/brave-ios/issues/7345#issue-1687021684

- Ensured that short chime is not added instead of videos in playlist
- Ensured that short chime is not seen in playlist when adding videos on upgraded profile

Example | Example
-|-
![IMG_3058](https://user-images.githubusercontent.com/17885425/235180963-fca5e620-3716-4796-865f-0c91b8960c1b.PNG) | ![IMG_3057](https://user-images.githubusercontent.com/17885425/235180950-faf678ef-9df9-4a70-878b-23e6d5444d72.PNG)
