### ISSUE TITLE
Fix Ethereum DApp error response formatting

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7392]
### Description: 

WebKit prefixes `Error: ` when responding to script messages with an error. Similar to Solana, we need to strip this prefix so the json formatting is preserved.

ref: https://github.com/brave/brave-talk/issues/882

### Steps to Reproduce 
1. Visit Brave Talk with a Premium account
2. Connect your wallet to Brave Talk
3. Tap `Host a Web3 Call`
4. Tap cancel on the signature request
5. Observe poorly formatted error message as the DApp could not parse the response.
  
Alternative steps without Brave Talk:
1. Visit https://metamask.github.io/test-dapp/
2. Connect your wallet to the test DApp
3. Tap `Sign` under `Personal Sign`.
4. Tap cancel on the signature request
5. Observe `ERROR: ("CODE": 4001, 'MESSAGE": "THE USER REJECTED THE REQUEST.)`.
    - Expected: `ERROR: THE USER REJECTED THE REQUEST`

### Actual result: 

https://user-images.githubusercontent.com/5314553/236291431-09850d6b-cfb9-4b34-8fc7-b31c65026bd1.mp4

### Expected result:

Screenshot from Android when correct error response is given for cancel/reject:
![Screenshot_2023-05-04-12-13-13-44_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/5314553/236291673-f674ef98-b64f-4afe-8dd4-c03a7d7ba24e.jpg)

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.51 (2.5.5.18)
- Verified steps from [#7393](https://github.com/brave/brave-ios/pull/7393)
- Verified cancel sign message shows proper response message instead of json response

iPhone 7+ (iOS 15.7.3) | iPhone 13 (iOS 16.4.1) | iPad Pro (16.4 Beta 4)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/236746425-59770391-faef-41ad-baa1-aa630901f28b.MP4> | <video src=https://user-images.githubusercontent.com/17010094/236746449-e3f32524-d095-477e-b8c7-70b1c47d35d3.MP4> | <video src=https://user-images.githubusercontent.com/17010094/236747290-8f2446b9-71ab-4942-81ea-fae30f7bdf82.MP4>
