### ISSUE TITLE
Brave incorrectly reports HTTP connection as secure (shows lock icon)

### ISSUE THREAD

**Issue by taoeffect** [brave/brave-ios#7403]
### Description: 

When visiting an HTTP website, for example ~~http://www.newlispfanclub.alh.net/forum/~~ http://www.newlispfanclub.alh.net/forum/viewtopic.php?p=22253#p22253 , Brave shows the connection as secure even though it's not an HTTPS connection.

### Steps to Reproduce 
  1. Visit ~~http://www.newlispfanclub.alh.net/forum/~~ http://www.newlispfanclub.alh.net/forum/viewtopic.php?p=22253#p22253

### Actual result: 

![IMG_7464](https://user-images.githubusercontent.com/138706/236684938-956ce3d4-39a5-46ed-9cdf-31fcd60748ac.jpg)
![IMG_7465](https://user-images.githubusercontent.com/138706/236684951-c63c278a-6c9d-4e83-a8bf-bbbba118db05.jpg)

### Expected result:

For the lock icon to be replaced with some sort of not-lock icon and a clear warning shown either in the URL bar or somewhere else.

### Reproduces how often:

Easily reproduced.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight?  Don't know.
- Can you reproduce this issue with the previous version of the current build from TestFlight?  Don't know.
- Can you reproduce this issue with the current build from AppStore?  Yes.

### Device details: 

iOS 16.4.1 (a)

### Website problems only:
- did you check with Brave Shields down? Irrelevant
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes, Safari shows "Not Secure"

**Comment by diracdeltas** [comment]
cc @Brandon-T @iccub - i feel like i've run into this before

**Comment by Brandon-T** [comment]
![image](https://user-images.githubusercontent.com/1530031/236935373-a4c3be7d-a7fe-4937-868b-8e1cd85ed51d.png)

Hmm weird. The lock icon is definitely the red warning icon for me.

I'll try to reproduce it some more and see what's going on.

**Comment by taoeffect** [comment]
Oops, I also get the red circle when visiting http://www.newlispfanclub.alh.net/forum/

Try visiting this instead: http://www.newlispfanclub.alh.net/forum/viewtopic.php?p=22253#p22253

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Version: 1.51 (23.5.10.20)
BraveCore: 1.51.110 (113.0.5672.77)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to http://www.newlispfanclub.alh.net/forum/ > Verify
3. Go to http://www.newlispfanclub.alh.net/forum/viewtopic.php?p=22253#p22253 > Verify

**ACTUAL RESULTS:**
- Verified "alert" icon is shown instead of a "lock" in the search bar for `http` websites

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/3743b665-9608-4b09-a1cb-cdb321eab5ae) | ![2](https://github.com/brave/brave-ios/assets/128532965/3d4e9d7e-8c13-4081-a19c-d9f85449cf3f) |
