### ISSUE TITLE
Use page color under status bar when using bottom bar

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7479]
### Description: 

Feature request from Anthony. The little gray bar at the top of the screen under the status bar should match page headers as a nice bit of polish.  Safari has a similar feature when you enable "Allow Website Tinting" (from Settings.app > Safari) but they also tint the toolbars which we will not do in Brave

![Brave](https://github.com/brave/brave-ios/assets/529104/335029c2-2730-4480-88a5-3c725b7c271b)

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5]
Version: 1.52 (23.6.1.16)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Three-dot Menu > Settings > Enable `Top Bar`
3. Open different websites with different background color > Verify
4. Three-dot Menu > Settings > Enable `Bottom Bar`
5. Open different websites with different background color > Verify

**ACTUAL RESULTS:**
- Verified that visiting certain pages update the status bar background color to match headers
- Verified that going back to NTP goes back to the toolbar color
- Verified that switching between tabs switches the colors accordingly
- Verified that when the top bar changes to a dark color that the status bar (time/wifi/etc.) shows white text (and that going to other places like tab switcher reverts back)
- Verify that none of the above happens when not using `Bottom bar` or `Landscape Mode`

<details>
<summary> Bottom Bar is ON. Portrait Mode - PASS </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/e3ec85f7-8f58-481b-a350-895952c60f0e) | ![2](https://github.com/brave/brave-ios/assets/128532965/85ff9c17-88ca-4882-a744-1dffce92673c) | ![3](https://github.com/brave/brave-ios/assets/128532965/2aeffcd5-ac8a-4e84-9e96-d69b1751dcaa) | ![4](https://github.com/brave/brave-ios/assets/128532965/3bcff3ae-512b-49cb-82fc-a44e63b3c5fe) |
</details>

<details>
<summary> Bottom Bar is ON. Landscape Mode - PASS </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/831fed76-0563-4f13-826e-8afa492b0338) | ![2](https://github.com/brave/brave-ios/assets/128532965/4c8e1bc6-a3ab-4fe7-a34f-52cc133a9284) | ![3](https://github.com/brave/brave-ios/assets/128532965/46ce1efe-b5bc-4bc5-a8ed-825ec0a5a451) | ![4](https://github.com/brave/brave-ios/assets/128532965/3f16f41c-c0fc-41aa-b8c7-a073ca6d3818) |
</details>

<details>
<summary> Bottom Bar is OFF. Portrait Mode - PASS </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/b0165708-e86c-4600-866c-bd7d49119d67) | ![2](https://github.com/brave/brave-ios/assets/128532965/32b1b5b3-c27c-4394-a043-51cbda64383a) | ![3](https://github.com/brave/brave-ios/assets/128532965/adfab733-1add-429e-8454-1ba8b0ba62cc) | ![4](https://github.com/brave/brave-ios/assets/128532965/df4de31b-c02a-4b64-b5bc-398a346f7187) |
</details>

<details>
<summary> Bottom Bar is OFF. Landscape Mode - PASS </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/e6eb8b58-c457-447d-a499-5fee16895cb3) | ![2](https://github.com/brave/brave-ios/assets/128532965/0a584b3f-1789-488a-b8d6-e073637ad0db) | ![3](https://github.com/brave/brave-ios/assets/128532965/7b2563d4-68be-4682-b80d-c69a663897c6) | ![4](https://github.com/brave/brave-ios/assets/128532965/3358e86e-7c1b-464c-a110-292c4bbd3088) |
</details>
