### ISSUE TITLE
Fix bug where New Tab Page ad viewed events fail on iOS

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#7566]
### Description: 
NTP-SI ad events are failing

### Steps to Reproduce 
  1. Join Rewards
  2. View an NTP-SI ad

### Actual result: 
NTP-SI ad viewed event fails because a served event is not triggered

### Expected result:
NTP-SI ad viewed should succeed

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Temporary fix until 1.53.x which changes how these events are triggered

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 16.5` & `iPad Air (3rd Gen)` running `iPadOS 16.5` using the following build(s):

```
1.51.2 (23.6.5.21)
```

We needed to verify the above via a call with @tackley @tmancey & @vlad-hoff as we couldn't verify the above on `Dev` builds due to the following:

* `Dev` builds are not displaying any NTP SI but have the ability to enable deeper logging for rewards/ads
* `Production` builds are displaying NTP SI but don't have the ability to enable deeper logging for rewards/ads

Because the above started happening on `1.49 (C111)`, we were able to monitor the back-end and confirmed that `viewed`, `clicked` and `landed` were working from a device from `Canada` running `C113`. Because this was broken via `C111`, there was no traffic coming from `C113` builds so it was easy to verify it was my requests.

![iOSVerification](https://github.com/brave/brave-ios/assets/2602313/3c595723-ff14-4db6-82a1-2a05d92010af)
