### ISSUE TITLE
Investigate app startup time

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#758]
### Description: 
Current app is too slow on startup. After launching the app it takes about 10-12secs for the UI to be active before you can use the app. 

### Steps to Reproduce 
  1. Remove app from memory if in background
  2. Launch the app 
  3. Wait for the UI to be active and then search for anger management class because of its slow startup 

**Actual result:** 
Too slow startup time

**Expected result:**
App should be active instantly its launched and you attain zen state 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7.1/1.7.2

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by cisclub** [comment]
@srirambv Does this issue still exist? I ran the reproduction steps but app responsiveness seems ok 🤔 
Tried on different simulators and iPhoneX.

**Comment by JonKaleidoscope** [comment]
@cisclub I know some performance issues are hard to track down using the simulator because they have difference resources than an actual devices compared to phones in the wild. Oddly enough, I have also seen strange issues where if you are testing on an actual device, build from Xcode, and still have the device connected to the computer the computing resources are still a little off. 
With that being said I haven’t noticed anything oddly strange about startup times either.

@srirambv I am curious to know other characteristics about your device if it is not asking too much. Ie. Did you have multiple tabs open, if so how many. How many bookmarks would you say you have on average. What OS version do you have on your phone? (Rarely, I have seen different issues specific link to a certain dot versions in another app). How much overall available storage do you have on your phone?

**Comment by srirambv** [comment]
@JonKaleidoscope This is on a clean install so no tabs at all. Device has plenty of free space so space isn't a problem and there are not backgrounded apps so nothing slowing it down there either. Its running iOS 12.1.2

**Comment by jhreis** [comment]
I am marking this ticket as `investigation`, and who ever picks this up, should identify bottlenecks and refile any as specific, actionable tickets.

**Comment by iccub** [comment]
Closing as stale, we don't see many reports about slow startup, please reopen if you still encounter this.
Could be also a iOS12/older device problem
