### ISSUE TITLE
Audio fingerprint not blocked on OS version 16.5+

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7726]
### Description: 
AudioContext fingerprint not blocked when upgrading to 16.5+ OS version 

### Steps to Reproduce 
  1. Install Brave (any)
  2 Navigate to test site - https://audiofingerprint.openwpm.com/
  3. Tap on 'fingerprint me'

### Actual result: 
AudioContext visualization is shown
![IMG_5063](https://github.com/brave/brave-ios/assets/17885425/82347f56-5c8f-4cfb-a26c-fa553eeafed2)

### Expected result:
AudioContext visualization is blocked
![IMG_0342 3](https://github.com/brave/brave-ios/assets/17885425/2c5d439e-a81c-4762-87ff-cee958e73e02)

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always on 16.5+

### Brave Version: All versions

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone, iPad (version 16.5+)

**Comment by iccub** [comment]
Is this a regression?

**Comment by cuba** [comment]
@iccub I don't understand this issue. But this doesn't seem like a brave issue to me:
1. We don't farble audio (for performance reasons). [Here](https://dev-pages.brave.software/fingerprinting/farbling.html) you can see what we farble in iOS.
2. We don't block anything when we do farbling. The expected result is invalid. Nothing should be hidden here. This looks like an issue with older versions of iOS and fixed in iOS 16.5+. And since we don't farble audio it must be an issue with the website or with webkit.

cc @Uni-verse

**Comment by Uni-verse** [comment]
> 

Thanks for the feedback on this @cuba. We were not sure if this is an issue with OS/webkit version that broke something but since we don't farble audio at all then this is invalid.
