### ISSUE TITLE
[iOS] Opt-out cookie consent notice

### ISSUE THREAD

**Issue by timchilds** [brave/brave-ios#7792]
## Description
Implement the cookie consent notice as opt-out. Same display logic as the old notice before it was disabled.

![image](https://github.com/brave/brave-ios/assets/28269287/720c7827-3656-4fbd-935f-6bd05b8b83be)

- Got it = keep cookie consent filter enabled (it's enabled by default).
- Stop blocking = disable cookie consent filter.

### Figma
https://www.figma.com/file/cL22PpqneTYxJePORxUBKz/Cookie-consent-blocker?type=design&node-id=1242%3A44596&mode=design&t=FSGniL2oAsfIVxUT-1

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 17.0]
- iPad Air [iPadOS 16.5.1]
Brave build: 1.57 (23.8.24.17)
BraveCore: 1.57.53 (116.0.5845.114)
```
---------------------------

<details>
<summary> Upgraded flow. `Block Cookie Consent Notices` is ON </summary>

**STEPS:**
1. Install build 1.56
2. Launch Brave and go through the onboarding flow until you land on NTP
3. Close and relaunch Brave until you see the `Cookie consent notice` pop-up
4. Select `Yes, block cookie consent notices`
5. Three-dot menu > Settings > Brave Shields & Privacy 
6. Confirm that the `Block Cookie Consent Notices` toggle switch is ON
7. Upgrade Brave to build 1.57 and launch it > Verify
8. Three-dot menu > Settings > Brave Shields & Privacy > `Block Cookie Consent Notices` > Verify

**ACTUAL RESULTS:**
- Verified that the `Cookie consent notice` pop-up is not shown again after the upgrade since the user already made a choice in the previous Brave version
- Verified that the `Block Cookie Consent Notices` toggle switch is ON after the upgrade
- Verified that `Block Cookie Consent Notices` is working properly when the toggle switch is ON or OFF

---------------------------

*iPhone*

https://github.com/brave/brave-ios/assets/128532965/9472f2d5-ae95-44cb-b2d6-7f86f1935609

*IPad*

https://github.com/brave/brave-ios/assets/128532965/cf191762-2fa0-42c5-b959-84015a4cdaef

</details>

<details>
<summary> Upgraded flow. `Block Cookie Consent Notices` is OFF </summary>

**STEPS:**
1. Install build 1.56
2. Launch Brave and go through the onboarding flow until you land on NTP
3. Close and relaunch Brave until you see the `Cookie consent notice` pop-up
4. Select `No thanks`
5. Three-dot menu > Settings > Brave Shields & Privacy 
6. Confirm that the `Block Cookie Consent Notices` toggle switch is OFF
7. Upgrade Brave to build 1.57 and launch it > Verify
8. Three-dot menu > Settings > Brave Shields & Privacy > `Block Cookie Consent Notices` > Verify

**ACTUAL RESULTS:**
- Verified that the `Cookie consent notice` pop-up is not shown again after the upgrade since the user already made a choice in the previous Brave version
- Verified that  the `Block Cookie Consent Notices` toggle switch is OFF after the upgrade

---------------------------

*iPhone*

https://github.com/brave/brave-ios/assets/128532965/0c2937e3-c703-42c1-a2e4-5f61109c690b

*iPad*

https://github.com/brave/brave-ios/assets/128532965/310d4917-cbf6-40a9-af56-6af86a1d4908

</details>

<details>
<summary> Fresh install </summary>

**STEPS:**
1. Install build 1.57
2. Launch Brave and go through the onboarding flow until you land on NTP
3. Close and relaunch Brave until you see the `Cookie consent notice` pop-up
4. Tap `Got it` or anywhere outside of the pop-up message
5. Three-dot menu > Settings > Brave Shields & Privacy > `Block Cookie Consent Notices` > Verify
6. Go back and open https://razer.com or https://anker.com > Verify

**ACTUAL RESULTS:**
- Verified that the `Cookie consent notice` pop-up is shown after Brave fresh install
- Verified that the `Block Cookie Consent Notices` toggle switch is ON by default
- Verified that `Block Cookie Consent Notices` is working properly when the toggle switch is ON or OFF

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/45a349c3-1db9-4b4e-9138-f0bb6c1bcbb3) | ![2](https://github.com/brave/brave-ios/assets/128532965/304928a0-b8a4-4215-87c8-746c0b819c11) | ![3](https://github.com/brave/brave-ios/assets/128532965/0a38291b-836b-4ab1-b4a5-f52f631dfdcf) | ![4](https://github.com/brave/brave-ios/assets/128532965/abdd88d1-cca7-41ba-b06d-6a90cc894749) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/642acc3c-04d7-471e-b80a-09f9c2a3669b) | ![2](https://github.com/brave/brave-ios/assets/128532965/00a11e08-59e2-4a20-9d6d-c13a8bad6600) | ![3](https://github.com/brave/brave-ios/assets/128532965/9bcb437c-f649-4b74-a58f-b5a3be0762a7) | ![4](https://github.com/brave/brave-ios/assets/128532965/4d4da110-f04b-4fea-9263-4e2899420b7d) |

*iPhone*

https://github.com/brave/brave-ios/assets/128532965/fa745194-c2fe-4efd-b066-be781728b3cc

*iPad*

https://github.com/brave/brave-ios/assets/128532965/8b5bda6b-c907-47e7-abc7-53362ce13787

</details>
