### ISSUE TITLE
Default Browser Prompt NTP - Logic Change

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7860]
### Description: 
Slack: https://bravesoftware.slack.com/archives/G01F4JUNXAQ/p1691614643386869

Please update the Make Default prompt with the following criteria
- Remove if one external url is opened(via mail app, notes, other apps...)
- Don't show for 7 days after install
- Never show over an NPT SI
- Stop showing it after 14 days since install

![iOS Make Default](https://github.com/brave/brave-ios/assets/7606853/81ead9b2-9c02-4712-ada9-7f533189cfce)

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.57 (23.8.28.13)
BraveCore: 1.57.53 (116.0.5845.114)Brave build: 1.57 (23.8.28.13)
BraveCore: 1.57.53 (116.0.5845.114)
```
Filled follow-up issue #7969 and #7977
---------------------------
<details>
<summary> Don't show for 7 days after installation </summary>

**STEPS:**
1. Fresh install and launch Brave 
2. Start onboarding flow > Don't set Brave as the default browser and select `Not now`
3. Tap `Done` > Wait until landed on NTP > Verify
4. Go to device settings and update the date to be less than 7 days from today
5. Close and relaunch Brave > Verify
6. Change the date to be `8 days` after Brave installed > Relaunch Brave > Verify
7. Tap on `Default browser prompt` > Verify

**ACTUAL RESULTS:**
- Verified that `Default browser prompt` is not shown on NTP after a fresh install
- Verified that `Default browser prompt` is not shown on NTP when it's less than 7 days after Brave installed
- Verified that `Default browser prompt` is shown after 7 days since Brave installed
- Verified, that tapping on `Default browser prompt` is opening device settings for the default browser setup, and going back to Brave is not showing `Default browser prompt` anymore
- Verified that no regression occurred and if Brave is set as the default browser, `Default browser prompt` is not shown after a fresh install or after 7 days

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/7edd4750-e92a-47ca-8386-80be751503ae) | ![2](https://github.com/brave/brave-ios/assets/128532965/826feff1-476e-40d8-ad25-764ee2bf0577) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/88c23264-5a1f-4de3-8df4-802afc711db1) | ![2](https://github.com/brave/brave-ios/assets/128532965/331622c8-d8cc-4d36-b043-c8418a19dccc) |

*Brave is not set as default*

https://github.com/brave/brave-ios/assets/128532965/89901adc-a639-4659-9527-d8c95cec63ad

*Brave is set as default*

https://github.com/brave/brave-ios/assets/128532965/8814d69c-1ad5-480c-ad20-d3b64a2e4bc1

</details>

<details>
<summary> Remove if one external URL is opened (via mail app, notes, other apps...) </summary>

**STEPS:**
1. Fresh install and launch Brave 
2. Start onboarding flow > Don't set Brave as the default browser and select `Not now`
3. Tap `Done` > Wait until landed on NTP > Confirm there is no `Default browser prompt` is shown
4. Go to device settings and update the date to be 8 days from today
5. Close and relaunch Brave > Confirm that `Default browser prompt` is shown
6. Open email, notes, messenger, etc > Open any link in Brave 
7. Open NTP > Verify

**ACTUAL RESULTS:**
- Verified that `Default browser prompt` is removed and not shown anymore when an external URL is opened in Brave

---------------------------

https://github.com/brave/brave-ios/assets/128532965/60e725ca-e679-4eaf-a552-ad9d78139bbf

</details>

<details>
<summary> Never show over an NTP SI </summary>

**STEPS:**
1. Fresh install and launch Brave 
2. Start onboarding flow > Don't set Brave as the default browser and select `Not now`
3. Tap `Done` > Wait until landed on NTP > Confirm there is no `Default browser prompt` is shown
4. Go to device settings and update the date to be 8 days from today
5. Close and relaunch Brave > Confirm that `Default browser prompt` is shown
6. Open another NTP until you see SI page > Verify

**ACTUAL RESULTS:**
- Verified that `Default browser prompt` must not be shown on NTP with SI
- Verified that `Default browser prompt` is shown on a regular NTP

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/ef4ba698-3c0f-4b4b-8524-e04b296c602f) | ![2](https://github.com/brave/brave-ios/assets/128532965/e7493886-b6d9-4a6c-8fcb-3773fce495c7) | ![3](https://github.com/brave/brave-ios/assets/128532965/26aac342-3f08-44c2-ac0b-011614d1eafe) |

https://github.com/brave/brave-ios/assets/128532965/b944304b-96ab-4782-9003-0a387de6579b
</details>

<details>
<summary> Stop showing it after 14 days since installation </summary>

**STEPS:**
1. Fresh install and launch Brave 
2. Start onboarding flow > Don't set Brave as the default browser and select `Not now`
3. Tap `Done` > Wait until landed on NTP > Confirm there is no `Default browser prompt` is shown
4. Device `Settings` > Update the date to be `<7 days` from today
5. Relaunch Brave > Confirm there is no `Default browser prompt` on NTP
6. Now update the date between `7 and 14 days` from today
7. Relaunch Brave > Confirm that `Default browser prompt` is shown on NTP
8. Now update the date to be`>14 days` from today
9. Relaunch Brave > Verify

**ACTUAL RESULTS:**
- Verified that `Default browser prompt` must not be shown on NTP after 14 days since installation

---------------------------

https://github.com/brave/brave-ios/assets/128532965/77972387-25cf-48be-8143-ab9cb8b3dcae

</details>
