### ISSUE TITLE
Enable cookie consent notice blocking by default

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7882]
### Description: 
We want to now enable this by default

### Steps to Reproduce 
  1. Install the app from scratch
  2. Check that cookie consent notice blocking is enabled
  3. Test cookie consent notice blocking works (will need to wait a few minutes as the necessary files download)

**Comment by iccub** [comment]
Are we not adding an opt-out popup?

See https://github.com/brave/brave-ios/issues/7792

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.6]
Brave build: 1.57 (23.8.21.22)
BraveCore: 1.57.47 (116.0.5845.96)
```
FIled follow-up issue #7920 and #7921
---------------------------
<details>
<summary> Upgraded flow. `Block Cookie Consent Notices` is ON </summary>

**STEPS:**
1. Install build 1.56
2. Launch Brave and go through the onboarding flow until landed on NTP
3. Close and relaunch Brave until you see the `Cookie consent notice` pop-up
4. Select `Yes, block cookie consent notices`
5. Three-dot menu > Settings > Brave Shields & Privacy 
6. Confirm that the `Block Cookie Consent Notices` toggle switch is ON
7. Upgrade Brave to build 1.57 and launch it > Verify
8. Three-dot menu > Settings > Brave Shields & Privacy > `Block Cookie Consent Notices` > Verify
9. Go back and open https://razer.com or https://anker.com > Verify

**ACTUAL RESULTS:**
- Verified that the `Cookie consent notice` pop-up is not shown again after the upgrade since the user already made a choice in the previous Brave version
- Verified that the `Block Cookie Consent Notices` toggle switch is ON after the upgrade
- Verified that `Block Cookie Consent Notices` is working properly when the toggle switch is ON or OFF

---------------------------

https://github.com/brave/brave-ios/assets/128532965/a9936333-1efc-4056-b46b-4a75a9ac52f6

</details>

<details>
<summary> Upgraded flow. `Block Cookie Consent Notices` is OFF </summary>

**STEPS:**
1. Install build 1.56
2. Launch Brave and go through the onboarding flow until landed on NTP
3. Close and relaunch Brave until you see the `Cookie consent notice` pop-up
4. Select `No thanks`
5. Three-dot menu > Settings > Brave Shields & Privacy 
6. Confirm that the `Block Cookie Consent Notices` toggle switch is OFF
7. Upgrade Brave to build 1.57 and launch it > Verify
8. Three-dot menu > Settings > Brave Shields & Privacy > `Block Cookie Consent Notices` > Verify
9. Go back and open https://razer.com or https://anker.com > Verify

**ACTUAL RESULTS:**
- Verified that the `Cookie consent notice` pop-up is not shown again after the upgrade since the user already made a choice in the previous Brave version
- Verified that  the `Block Cookie Consent Notices` toggle switch is OFF after the upgrade
- Verified that `Block Cookie Consent Notices` is working properly when the toggle switch is ON or OFF

---------------------------

https://github.com/brave/brave-ios/assets/128532965/445e83e7-7420-4af2-b0ab-3f9ccf5bb011

</details>

<details>
<summary> Fresh install </summary>

**STEPS:**
1. Install build 1.57
2. Launch Brave and go through the onboarding flow until landed on NTP
3. Close and relaunch Brave until you see the `Cookie consent notice` pop-up
4. Tap `Got it` or anywhere outside of the pop-up message
5. Three-dot menu > Settings > Brave Shields & Privacy > `Block Cookie Consent Notices` > Verify
6. Go back and open https://razer.com or https://anker.com > Verify

**ACTUAL RESULTS:**
- Verified that the `Cookie consent notice` pop-up is shown after Brave fresh install
- Verified that the `Block Cookie Consent Notices` toggle switch is ON by default
- Verified that `Block Cookie Consent Notices` is working properly when the toggle switch is ON or OFF

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/d40585ff-176c-47ff-a1c3-30e49b76dc29) | ![2](https://github.com/brave/brave-ios/assets/128532965/b1d1fb35-a7d4-4fd0-92f9-c98225c54906) | ![3](https://github.com/brave/brave-ios/assets/128532965/c8790754-f488-42e3-bf9b-3cefc459ed20) |

https://github.com/brave/brave-ios/assets/128532965/f967a15f-ffa7-40d0-b580-06b6f1f1452e

</details>
