### ISSUE TITLE
Sync UX improvement - Conditional Device Number 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7887]
Details at https://github.com/brave/brave-browser/issues/19670 and Slack discussion.

Android ticket https://github.com/brave/brave-browser/issues/32286
This is a follow up upon https://github.com/brave/brave-ios/issues/4470

When connecting the sync chain, we should:
I. Don't enable by default any sync types except device info, to prevent data leak.
II. Look on the number of existing devices in the chain, excluding ours:

1..4 devices - join the chain silently and enable bookmarks
5..9 devices - show alert (are you sure) with device list; if user answers no - leave chain, if yes - enable the bookmarks type
10 and more - add alert to block and prevent sync (leave chain)

Also existing confirmation dialogs must be removed. (iOS case should remain removed)

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.58 (23.9.22.13)`

Test Plan: https://github.com/brave/brave-ios/pull/7918#issue-1862231105

<details><summary>Case: 1-4 devices</summary>

- Ensured that device joins sync chain silently when < 4 devices connected.
- Ensured that only `Device Info` type is enabled by default

Example | Example
-|-
![IMG_3522](https://github.com/brave/brave-ios/assets/17885425/31eea189-5199-4c29-b579-a3676c7defc6) | ![IMG_3525](https://github.com/brave/brave-ios/assets/17885425/4a66a958-cdf8-4471-8d08-40282423b758)

</details>

<details><summary>Case: 5-9 devices</summary>

- Ensured that alert is shown with device list.
- Ensured that device is not connected to chain if user selects `Cancel`
- Ensured that device is connected to sync chain if user selects `Confirm`
- Ensured that joining sync chain is successful using QR code as well as entering code words after confirming on the prompt.

Example | Example
-|-
![IMG_3519](https://github.com/brave/brave-ios/assets/17885425/13649375-70bb-44e7-89a4-406eb6f2cc79) | ![IMG_3521](https://github.com/brave/brave-ios/assets/17885425/e642c2c1-a39c-4661-b1f1-73019fe2029b)

</details>


<details><summary>Case: 10 devices</summary>

- Ensured Error is shown preventing user from joining chain due to maximum number of devices connected.

![IMG_3520](https://github.com/brave/brave-ios/assets/17885425/29588f04-cc71-4460-94b8-1713536999ba)

</details>
