### ISSUE TITLE
Filtering NFTs by a specific network and selecting an account from a different network shouldn't show anything

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#7963]
### Description: 
Filtering NFTs by a specific network and selecting an account from a different network shouldn't show anything

### Steps to Reproduce 
  1. Restore wallet that has NFTs from different network
  2. Select Solana account from account filter
  3. Select Ethereum Network from network filter
  4. Save and close settings
  5. NFTs from Ethereum account is shown when account selected is for Solana

### Actual result: 
Filtering NFTs from network and account always shown NFTs from filtered network

### Expected result:
Filtering NFTs by a specific network and selecting an account from a different network shouldn't show anything

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
All

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
This is expected behaviour because `Hide Unowned` is not enabled. On the NFT tab, the account filters will only hide an NFT when `Hide Unowned` is checked. The intention of this toggle/behaviour is to allow users to add NFTs that they do not own.

On Portfolio, the account filters do not hide assets. They exclude the de-selected accounts from the displayed balance.
On NFT tab, we do not display balance so by selecting/de-selecting accounts has no effect unless we are also hiding unowned balances.

I've opened https://github.com/brave/brave-ios/issues/7966 to address slow balance fetch for NFTs when `Hide Unowned` is enabled.
