### ISSUE TITLE
NFT balance fetch is slow

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7966]
### Description: 

When enabling `Hide Unowned` filter on NFT tab, balances are fetched for each NFT to determine if an NFT is owned by one of the users selected accounts. There is a long delay before NFTs are shown after first enabling this filter because the balance fetch is slow.

### Steps to Reproduce 
  1. Have NFTs belonging to one of the accounts in active Wallet
  2. Open NFT tab and tap Filters & Display Settings button
  3. Enable `Hide Unowned` and tap `Save Changes`
  4. Observe slow balance fetch to determine ownership, NFTs hidden until balance is fetched.

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/614d334c-9171-4a87-85d7-f495ae3dce86

### Expected result:

Balance fetch is much quicker.

### Reproduces how often: 

Easily reproduced

### Brave Version: 

v1.57+

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.6 running 1.5 (23.8.28.22)
- Verified steps from [#7968](https://github.com/brave/brave-ios/pull/7968)
- Verified NFT balance fetch is instantaneous 
- Verified Tap area of NFT settings is on the entire div rather than just the text area

https://github.com/brave/brave-ios/assets/17010094/4f308205-55c2-44eb-aa32-aea184b55713
