### ISSUE TITLE
Update/add additional info to the web reporter

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8007]
### Description: 
We want to ensure the following is reported using the `WebcompatReporter`
1. origin + path
2. Enabled filter lists
3. Whether the user has Brave VPN enabled
4. Which filter lists are enabled (would not include custom lists, only which of the brave-UI-included filter list are enabled)
5. Fingerprinting settings (off, default, aggressive) for the site being reported

### Testing Strategy
(UI Changes are done separately)
1. Go to https://brave.com/privacy-features/#test?test=test
2. Disable shields 
3. Submit report (don't worry about the UI here but you may review this if testing both PRs at the same time)
4. Go to https://stats.brave.com/dashboard#webcompat
5. look at reports for https://brave.com
6. Should see a new report. Identify the following is correct
- [ ] "Platform" is `ios`
- [ ] "Version" reflects the current iOS version (ex. `17.0`)
- [ ] "URL" with the query params and fragments stripped out (i.e. `https://brave.com/privacy-features/`)
- [ ] "Shields enabled" (should be "No" right now because you can't submit the report without disabling shields)
- [ ] "Adblock setting" (should be "Allow" right now because you can't submit the report without disabling shields
- [ ] "Fingerprint block setting" (should be "Allow" right now because you can't submit the report without disabling shields
- [ ] "Enabled adblock lists" reflects the filter lists enabled (custom filter lists are not sent)
- [ ] "User languages" only shows the active language
- [ ] "Language farbling enabled?" is always "Yes" on iOS
- [ ] "Brave VPN connected?" is "yes" when VPN is enabled and "No" otherwise.
- [ ] "Contact info" and "Additional details" is empty because there is no UI for this yet

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.58 (23.10.4.11)`

Ensured the following cases are correctly sent using test strategy in https://github.com/brave/brave-ios/issues/8007#issue-1876196304. Test cases include a default install case, two cases with varying ad-block settings and no VPN and a fourth case with VPN and custom lists enabled (negative case).

<details><summary>Case 1: Youtube.com | Default Install</summary>

1. Fresh profile
2. Navigate to the following url: `https://youtube.com/*`
3. Disable shields
4. Submit report
5. Go to https://stats.brave.com/dashboard#webcompat
6. look at reports for https://brave.com/

![Screenshot 2023-10-10 at 7 06 06 PM](https://github.com/brave/brave-ios/assets/17885425/07faefb7-9370-43db-aac7-4d96aa631165)
![Screenshot 2023-10-10 at 7 06 16 PM](https://github.com/brave/brave-ios/assets/17885425/f18cf391-9147-4dfa-ac77-ed64e691f75a)


</details>

<details><summary>Case 2: Brave.com | VPN disabled | Standard Adblock | Filter lists</summary>

1. Fresh profile
2. Enable some filter lists
3. Navigate to the following url: `https://brave.com/privacy-features/#test?test=test`
4. Disable shields
5. Submit report
6. Go to https://stats.brave.com/dashboard#webcompat
7. look at reports for https://brave.com/

![Screenshot 2023-10-10 at 4 34 22 PM](https://github.com/brave/brave-ios/assets/17885425/684b940e-aaff-4b70-b94c-2313aa00762b)

</details>

<details><summary>Case 3: Brave.com | VPN Disabled | Aggressive Adblock | Filter lists</summary>

1. Fresh profile
2. Enable some filter lists, set Ad blocking to `Aggressive`
3. Navigate to the following url: `https://brave.com/privacy-features/#test?test=test`
4. Disable shields
5. Submit report
6. Go to https://stats.brave.com/dashboard#webcompat
8. look at reports for https://brave.com/

![Screenshot 2023-10-10 at 4 34 22 PM](https://github.com/brave/brave-ios/assets/17885425/684b940e-aaff-4b70-b94c-2313aa00762b)

</details>

<details><summary>Case 4: Reddit.com | VPN enabled | Aggressive Adblock | Filter lists + Custom list enabled</summary>

1. Fresh profile
2. Enable some filter lists, enabled custom filter list
3. Set Ad blocking to `Aggressive`
4. Navigate to the following url: `https://www.reddit.com/#test?test=test`
5. Disable shields
6. Submit report
9. Go to https://stats.brave.com/dashboard#webcompat
10. look at reports for https://brave.com/

![Screenshot 2023-10-10 at 6 35 40 PM](https://github.com/brave/brave-ios/assets/17885425/7ff54511-c586-47c6-800a-4a886cdf59f9)
![Screenshot 2023-10-10 at 6 35 52 PM](https://github.com/brave/brave-ios/assets/17885425/236987c5-44ea-4629-bda5-1ee7eed1db8d)

Example | Example | Example
-|-|-
![IMG_3580 2](https://github.com/brave/brave-ios/assets/17885425/26af56ee-7737-46d4-8a5a-b5593af78a88) | ![IMG_3581](https://github.com/brave/brave-ios/assets/17885425/56347ef8-4c60-4c2a-9bd8-5ec321125c97) | ![IMG_3582](https://github.com/brave/brave-ios/assets/17885425/71d02ebd-af20-4cab-ae72-45d8b8d96df6)

</details>

- [x] Ensured "Platform" is ios
- [x] Ensured  "Version" reflects the current iOS version (ex. 17.0)
- [x] Ensured "URL" with the query params and fragments stripped out (i.e. https://brave.com/privacy-features/)
- [x] Ensured "Shields enabled" (should be "No" right now because you can't submit the report without disabling shields)
- [x] Ensured "Adblock setting" (should be "Allow" right now because you can't submit the report without disabling shields
- [x] Ensured  "Fingerprint block setting" (should be "Allow" right now because you can't submit the report without disabling shields
- [x] Ensured "Enabled adblock lists" reflects the filter lists enabled (custom filter lists are not sent)
- [x] Ensured "User languages" only shows the active language
- [x] Ensured "Language farbling enabled?" is always "Yes" on iOS
- [x] Ensured "Brave VPN connected?" is "yes" when VPN is enabled and "No" otherwise.
- [x] Ensured "Contact info" and "Additional details" is empty because there is no UI for this yet
