### ISSUE TITLE
Add share button to the URL bar & URL bar redesign

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#8173]
### Description: 
Linked to https://github.com/brave/brave-ios/issues/7904

Please update the share button per the figma here:
https://www.figma.com/file/Ejai8TJykn1liKJlrHtstd/Browser-toolbar-and-menu-update?type=design&node-id=997-37097&mode=design&t=tSPaiHpFSLCDZXms-11

##

**Comment by Uni-verse** [comment]
Verified on `iPhone X` using version `1.61 (23.12.7.19)`

**_Fresh Profile_**

- Ensured share button is displayed instead of forward button in the URL bar when forward navigation is not available.
- Ensured tapping on share button will display share menu.
- Ensured share button is not shown when navigating back using back button. 
- Ensured that `Security Certificate` option is available in the share menu for webpages using HTTPS.
- Ensured that tapping on URL bar for `Not Secure` URLs will show a popup with a option to `View Certificate.`
- Ensured share button is grayed out on NTP.
- Ensured tool bar functionality using `Top Bar` and `Bottom Bar` mode.
- Ensured share button is working in normal and private modes.
- Ensured share button is working in landscape orientation.
- Verified all cases for https://badssl.com/ for proposed test plan in https://github.com/brave/brave-ios/pull/8417#issuecomment-1813403742
- Verified RTL scenarios mentioned in https://github.com/brave/reviews/issues/1443#issuecomment-1810864136
- Verified extended subdomain https://long-extended-subdomain-name-containing-many-letters-and-dashes.badssl.com/
- Verified Cyrillic test case https://github.com/brave/brave-ios/pull/8417#issuecomment-1813403742

**_Existing Profile_**

- Verified share button functionality on existing profile (1.60 -> 1.61). 
- Verified share button is working after switching to Bottom Bar via the callout (Top Mode set when upgrading).
- Verified share button is working when upgrading with Bottom Bar enabled (default).
- Verified test cases mentioned in https://github.com/brave/brave-ios/pull/8417#issuecomment-1813403742 on existing profile. 

NTP (light) | NTP (dark) | HTTPS URL | Not Secure Page | Certificate | Move Tabs Bar Callout
-|-|-|-|-|-
![Screenshot 2023-12-07 at 10 54 32 AM](https://github.com/brave/brave-ios/assets/17885425/e40fa3c7-3bdc-4aa4-b16d-edcaa62ac19e) | ![Screenshot 2023-12-07 at 11 59 41 AM](https://github.com/brave/brave-ios/assets/17885425/b900fa2d-021b-4b94-ad60-3b6f97f468ab) | ![Screenshot 2023-12-07 at 10 58 06 AM](https://github.com/brave/brave-ios/assets/17885425/21e30958-8b09-4672-a4ca-cdb0fe9f0b8f) | ![Screenshot 2023-12-07 at 11 00 06 AM](https://github.com/brave/brave-ios/assets/17885425/a1bcb91b-1733-4c58-86d8-656c5e81c53b) | ![Screenshot 2023-12-07 at 11 00 15 AM](https://github.com/brave/brave-ios/assets/17885425/5f6987a2-6197-459d-a5d6-374a384adf36) | ![Screenshot 2023-12-07 at 11 53 37 AM](https://github.com/brave/brave-ios/assets/17885425/c905ffe5-d06e-4045-ba54-48e3f14a486b)


Long URL (RTL) | Short URL (RTL) | Mixed Script page | Long subdomain (RTL) | Private Tab | Youtube (Playlist Icon)
-|-|-|-|-|-
![Screenshot 2023-12-07 at 11 21 35 AM](https://github.com/brave/brave-ios/assets/17885425/88f5169b-5be6-42d7-bb56-146455d96e06) | ![Screenshot 2023-12-07 at 11 19 20 AM](https://github.com/brave/brave-ios/assets/17885425/dce922cb-1542-42c1-b3c5-a9c84f6db0a4) | ![Screenshot 2023-12-07 at 11 22 21 AM](https://github.com/brave/brave-ios/assets/17885425/dc1c489c-0323-4602-8b08-c193edb2cb3d) | ![Screenshot 2023-12-07 at 11 16 47 AM](https://github.com/brave/brave-ios/assets/17885425/21c049dd-f4fa-49dc-9017-7810775b5a5e) | ![Screenshot 2023-12-07 at 11 33 06 AM](https://github.com/brave/brave-ios/assets/17885425/742f1078-873a-4439-9990-49a2a567d467) | ![Screenshot 2023-12-07 at 11 35 08 AM](https://github.com/brave/brave-ios/assets/17885425/451161c9-0ce0-4590-81b3-bcf9cc143950)


NTP (PBM) | Webpage (PBM) | Landscape | RTL | Extended subdomain | Cyrillic text | Top Bar
-|-|-|-|-|-|-
![Screenshot 2023-12-07 at 11 36 31 AM](https://github.com/brave/brave-ios/assets/17885425/7501dc8e-a022-49d6-aed5-09d8b504e2f2) | ![Screenshot 2023-12-07 at 11 37 25 AM](https://github.com/brave/brave-ios/assets/17885425/0563d2b0-72da-4e9b-9ebc-7381db8a54be) | ![Screenshot 2023-12-07 at 11 38 01 AM](https://github.com/brave/brave-ios/assets/17885425/5cd145ac-ec52-41dc-9dd1-19bed3409b96) | ![Screenshot 2023-12-07 at 11 39 25 AM](https://github.com/brave/brave-ios/assets/17885425/6959b720-826a-422e-92ca-d629099856ae) | ![Screenshot 2023-12-07 at 11 44 15 AM](https://github.com/brave/brave-ios/assets/17885425/9f69f00c-847c-4c4a-b534-6d96e208065f) | ![Screenshot 2023-12-07 at 11 45 09 AM](https://github.com/brave/brave-ios/assets/17885425/4f259a12-5bd6-4fdf-a07c-f2177230363e) | ![Screenshot 2023-12-07 at 11 01 42 AM](https://github.com/brave/brave-ios/assets/17885425/3d1f3756-5b3c-447c-a1c7-6b02df6ba607)
