### ISSUE TITLE
[Follow up to 8092] Fix creativeinstanceid total count to increment correctly

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#8178]
### Description: 
Fix creativeinstanceid total count to increment correctly

related to #8092 

### Steps to Reproduce 
  1. Install 1.58 (dev channel)
  2. View NTP SI several times
  3. Check creativeinstanceid.total.count in histogram logs

### Actual result: 
Increments on every event

### Expected result:
Increment on creative event only

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  1.58

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? TBD

### Device details: 
iPhone

**Comment by hffvld** [comment]
Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 [iOS 17.1]
Brave build: 1.58 (23.10.6.14)
BraveCore: 1.58.139 (117.0.5938.153)
```
---------------------------

**STEPS:**
1. Fresh install `Dev build` and launch Brave
2. Go through the onboarding flow and open `Settings`
3. BraveCore Switches > P3A > Set the flags:
- `Don't Randomize Upload Interval` = ON
- `Upload Interval` = 60 (seconds)
- `Typical Rotation Interval` = 60 (seconds)
- `Express Rotation Interval` = 60 (seconds)
4. Go back to `NTP` and open New Tabs until you see `Sponsored Image`
5. Open `Sponsored Image`
6. Settings > View Brave Histogram (p3a) Logs
7. Scroll down and see `creativeInstanceId.total.count` > Verify
8. Go back to `NTP`, open and click another NTP-SI > Verify again

**ACTUAL RESULTS:**
- Verified that the total increments per active campaign per rotation instead of per event per rotation are shown with `creativeInstanceId.total.count`
- Verified that `viewing` and `clicking` the same one NTP-SI counted as `1` under `creativeInstanceId.total.count`

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/17a76a84-2940-48cd-8c72-f129c68f7e4e) | ![2](https://github.com/brave/brave-ios/assets/128532965/0d76d073-3db3-4fca-b1ef-42e1e6ca96f5) | ![3](https://github.com/brave/brave-ios/assets/128532965/5fcd5758-3982-4e89-b675-2d4e1cec4d66) |
