### ISSUE TITLE
Unable to select RPC network when adding network via Dapp

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#8266]
### Description: 
Unable to select RPC network when adding network via Dapp

### Steps to Reproduce 
  1. Go to `https://chainlist.org`
  2. Connect wallet and add a network not in the pre-loaded list
  3. Try selecting the RPC URL, doesn't select

### Actual result: 
Unable to select RPC network when adding network via Dapp

### Expected result:
Should be able to select any RPC URL from the list

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
iPhone 13 (iOS 17.1)

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? Na

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by nuo-xu** [comment]
From the flow on desktop, network that is going to be added from dapps is not supposed to be configured before it is added. 
On iOS, each of the rpc url's radio button is disabled but the colour of the selected one gives users the feeling they can configure that during the step.
I can change the colour of that selected row so that users can understand the whole screen is only for viewing purpose.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.24.16)
- Verified steps from issue description & [#8434](https://github.com/brave/brave-ios/pull/84340)
- Verified when adding a custom network, the RPC URL selection is disabled
- Verified able to change RPC URL after custom network is added successfully

https://github.com/brave/brave-ios/assets/17010094/2f12791f-efda-4f5e-a5e7-828fd2069325
