### ISSUE TITLE
Adblock init crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8334]
### Description: 
- Upon initialization of the AdblockEngine, it can crash the application
- https://github.com/brave/brave-ios

### Steps to Reproduce 
  1. Run the app, enable a lot of Filters in Brave Shields -> Privacy
  2. You can enable up to 40 at the moment.

### Actual result: 
- Crash

### Expected result:
- Should not crash at all

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Very difficult to reproduce on new devices! (Easy to reproduce on iPhone 6, 6s, SE or older devices)

### Brave Version: 
- 1.58.x, 1.58.1

### Device details: 
- iPhone

<img width="560" alt="Zrzut ekranu 2023-10-30 o 17 04 23" src="https://github.com/brave/brave-ios/assets/6950387/552f4d33-598c-4ee5-9a54-445402d8bb9a">

**Comment by iccub** [comment]
test plan here https://github.com/brave/brave-ios/issues/8294

**Comment by Uni-verse** [comment]
Verified via https://github.com/brave/brave-ios/issues/8294#issuecomment-1786101677 & https://github.com/brave/brave-ios/issues/8294#issuecomment-1786359822.

**Comment by cuba** [comment]
Just a summary of the progress of this issue:
## Original issue (this issue)
This happened because I was eagerly compiling all engines and content blockers. Note this is change from 1.57 which didn't do this
**Important**: While it seems that eagerly compiling the engines causes the issue, this doesn't seem to be the case. You could have enabled all filter lists in 1.57 and nothing would crash. I believe that it's just an unhappy coincidence that, while adding the eager compile, something else also changed which caused the crashes and this change only exacerbated the effect.

### STR
Launch on an old device. Crashes.

## Patch 1 
https://github.com/brave/brave-ios/pull/8193
I removed the eager compile of engines. Fixed crashes locally but not on the app store

### STR 
Enable a large number of filter lists (more than 40 on iphone 6s)

## Patch 2 
1. https://github.com/brave/brave-ios/pull/8224 (hard limit of 30),  
2. https://github.com/brave/brave-ios/pull/8283 (limit based on device memory) 
3. https://github.com/brave/brave-ios/pull/8288 (add a minimum of 20)

Limit the number of enabled filter lists (the limit is based on the device memory with a 20 minimum)

### STR
At this point there is no more an STR so I built a tool to be able to reproduce the STR in Patch 1 (i.e circumvent the filter list limit) https://github.com/brave/brave-ios/pull/8351

## Patch 3
https://github.com/brave/brave-ios/pull/8295
Content blockers are eagerly compiled so i made sure they are not (this wasn't based on anything except a dumb attempt to limit the memory usage of the app. This is just a "hopeful fix")

### STR
Same as Patch 2.

### Some mysteries
1. Compiling the same filter list (even a large one 100 times) doesn't crash the app.
2. ~~Compiling filter lists on detached tasks pushes the amount of filter lists on iPhone 6s from 40 to 90~~ (seems to only be a fluke)
3. Often crashes on the Russian list. I tried to brute force compile this one thinking it can be the reason, but it seems to only crash on this one because its the largest filter list so an obvious bottle neck. So I don't believe that this list specifically is the problem. Though some people have said that disabling this filter list fixes the crashes.
