### ISSUE TITLE
Toolbar displays in landscape mode when changing device orientation with playlist/tab tray open

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8421]
### Description: 

On iOS 17 (*built with Xcode 15*), when you rotate the device while in a screen that fully covers the browser window (such as playlist or the tab tray) into landscape then back to portrait before dismissing it, the toolbar will display in the incorrect layout.

Dev investigation: 
- The actual bug lies within using the `fullScreen` modal presentation style in conjunction with rotation. This does not happen on the onboarding for instance because that screen can't be rotated
- The trait collection of the BVC does not update upon rotating back to the original orientation you were in
- iOS 15 & 16 do not hit this bug, iOS 17 does not hit this bug when built with Xcode 14.3 specifically so its an iOS 17 SDK issue

### Steps to Reproduce 
  1. Prefix: In portrait mode to start
  2. Open Playlist or the Tab Tray 
  3. Rotate to landscape then back to portrait
  4. Dismiss Playlist/Tab Tray

### Actual result: 
The toolbar will be showing as if the device is in landscape mode

### Expected result:
The toolbar should show correctly for the orientation and device type

### Reproduces how often: 
Easily

### Brave Version: 
1.58.1 & higher as thats which builds switched to Xcode 15 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details:
Tested across multiple devices

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.60 (23.11.20.17)`

- Verified Toolbar does not change using STR in https://github.com/brave/brave-ios/issues/8421#issue-1995583547
- Verified issue is not reproducible on upgraded profile (1.58.2 -> 1.60)
- Verified that using + to open tab instead of dismissing tab tray (Step 4) does not cause Toolbar to switch orientations. 
- Verified there are no issues using Top Bar mode. 

https://github.com/brave/brave-ios/assets/17885425/35424b00-7061-419b-b2c1-096e6208c070
