### ISSUE TITLE
Trying to create wallet in split screen causes onboarding to get stuck in split view 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#8425]
### Description: 
Trying to import/create wallet in split screen causes onboarding to get stuck in split view 

### Steps to Reproduce 
  1. Open Brave in split view on iPad
  2. Open Wallet on both views
  3. Initiate onboarding create wallet
  4. Go to create password screen on both view
  5. Enter different password in both window
  6. Finish onboarding in one view
  7. The other view gets stuck

### Actual result: 
![image](https://github.com/brave/brave-ios/assets/17010094/9fb90b53-f46b-4e7f-8789-8772766affcc)

### Expected result:
Should not allow to continue if different passwords are entered in split view

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Maybe
- Can you reproduce this issue with the current build from AppStore? Maybe

### Device details: 
iPad Pro (iOS 16.7.2)

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
If both windows are in the Create a Password screen, the window that you tap `Continue` on first will continue with the onboarding flow. The 2nd window (the window you did _not_ tap `Continue` on Create a Password) will just switch to showing Portfolio.
If you then switch from SplitView back to fullscreen, the 2nd window doesn't _close_, it gets minimized but is still open in the background; this is why when you re-open SplitView the onboarding view re-appears. But you should never get 'stuck', just one window continues with onboarding flow (backup recovery phrase, setup biometrics) while the other window just shows main wallet.

If this is what you are seeing, this is expected behaviour. If you're actually 'stuck' in either of these window (cannot progress through onboarding / interact with Portfolio), could you share a full screen recoding to help reproduce the bug?

This is behaviour I see (mouse clicks visible):

https://github.com/brave/brave-ios/assets/5314553/694b6dba-d67d-4f42-b625-72e5cde4ae6a


Similarly, 'minimize window' behaviour when switching from SplitView -> Fullscreen in Safari:

https://github.com/brave/brave-ios/assets/5314553/96908c9c-10a6-441a-9550-af288932c99c

**Comment by srirambv** [comment]
Verification passed on iPad with iOS 16.7.5 running 1.64 (24.1.25.17)
- Verified steps from issue description
- Verified using wallet in split screen doesn't get stuck while onboarding
- Verified the same accounts are created on both split screens

https://github.com/brave/brave-ios/assets/17010094/57203582-8917-47d8-a2c9-a955d6c26e16
