### ISSUE TITLE
Unable to view seed phrase in Brave Wallet

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-ios#8445]
The panel pops up, but the “view my recovery phrase” isn’t working correctly to display my seed phrase. @nuo-xu tested in 1.60 TF build and was reproducing as well.

**Comment by nuo-xu** [comment]
Marked as QA/No as no one can reproduce it. Will mention this to QA to run a sanity test on this to make sure new changes didn't break anything.

**Comment by kjozwiak** [comment]
> Marked as QA/No as no one can reproduce it. Will mention this to QA to run a sanity test on this to make sure new changes didn't break anything.

Thanks 👍 I also mentioned the above to @srirambv to basically spot check the above re: making sure that seed phrases are still working as expected. Going to label as `release-notes/include` as I believe this issue was found via the current release even though it's hard to reproduce. Please change if that's not correct.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.27.16)
- Verified seed phrase is visible on both new wallet and imported wallet
- Verified seed phrase is shown during onboarding
- Verified seed phrase is shown when backup option from accounts tab is selected
- Verified on new wallet clicking the backup message on portfolio and continuing shows the seed phrase
