### ISSUE TITLE
SSL Error shows on interstitial pages

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8650]
### Description: 
 - When on an interstitial page such as the "No Internet Connection" page, the page shows as `insecure` which can be misleading.
 - When on a `http` page, it shows the wrong status (warning) instead of (insecure).

### Steps to Reproduce 
  1. Test `http://neverssl.com`
  2. Test turning off internet on any page and refreshing it until you get the "No internet connection" interstitial page

### Actual result: 
  1. Shows "Warning" instead of "Insecure"
  2. Shows "Insecure" instead of "Secure"

### Expected result:
  1. Should show "Insecure"
  2. Should show "Secure"

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily Reproduced

### Brave Version: 

- 1.61.x, 1.62.x

### Device details: 
- Any

### Website problems only:
- Yes

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.62 (24.1.29.12)`

Test Steps: https://github.com/brave/brave-ios/issues/8650#issue-2079688125

_**Fresh Profile**_ 

1. Navigate to http://neverssl.com.
2. Confirm warning message shows `Not Secure`.
3. Tap on the warning message.
4. Disable internet and reload the page.
5. Confirm warning message shows a secure connection (no warning message).

- Verified loaded HTTP page shows `Not Secure` instead of warning message.
- Verified no internet interstitial page shows secure connection in the URL bar. 

Example | Example | Example
-|-|-
![IMG_3711](https://github.com/brave/brave-ios/assets/17885425/1eed51b0-26c3-48a7-a22f-e8c22b949c82) | ![IMG_3713](https://github.com/brave/brave-ios/assets/17885425/26513fd9-4320-467a-9269-44e33880a98f) | ![IMG_3712](https://github.com/brave/brave-ios/assets/17885425/c86ac3e1-b72a-4ae7-a10b-f035eed8d4c8)

**_Upgraded Profile (1.61.1 -> 1.62)_**

1. Install 1.61.1 app version.
2. Navigate to http://neverssl.com.
3. Confirm warning message is shown in URL bar. 
4. Disable internet on device and reload the page.
5. Confirm `Not Secure` message is shown. 
6. Enable internet on device, reload page.
7. Upgrade to 1.62.
8. Check message in URL bar. 
9. Repeat Step 4-6

- Verified http://neverssl.com shows `Not Secure` instead of warning message
- Verified no internet interstitial page shows secure connection in the URL bar. 

1.61.1 | 1.62
-|-
![IMG_3714](https://github.com/brave/brave-ios/assets/17885425/97207a3e-6c7e-46c6-ba29-4b71631f36d0) | ![IMG_3712](https://github.com/brave/brave-ios/assets/17885425/0fdc3d5e-7355-4460-a0de-39ec1a4032a7)
