### ISSUE TITLE
target=blank hyperlinks do not redirect sometimes 

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8661]
### Steps to Reproduce 
  1. go to carwow.com
  2. scroll down, tap on 'watch more videos'

### Actual result: 
about:blank may show, no redirect to youtube

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 Beta
Brave build: 1.62 (24.1.29.12)
BraveCore: 1.62.153 (121.0.6167.85)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-ios/issues/8661#issue-2086536499

**ACTUAL RESULTS:**
- Verified that redirection to the channel's YT home page is successful.
- Verified that no regression is happening and the issue is not reproducible
- Verified the same in the `Standard` and `Private` tabs with `Shields` On and Off

---------------------------

https://github.com/brave/brave-ios/assets/128532965/2d41855b-9907-410e-9d17-21a1f522df9a
