### ISSUE TITLE
Add default browser P3A

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8674]
### Description: 

Name: `Brave.IOS.IsLikelyDefault`
Answers:
```
0. Not enough info
1. No
2. Yes
```

- There's no actual way of determining if we're the default browser officially so we will record last http/https link opened by Brave and compare against a 14 day period.
- Special case: If the user has just installed the app within the past 7 days, instead of recording `No`, record `Not enough info` to avoid skewing data
- If a user opens a http/https link with Brave immediately record `Yes` even if within 7 day window
- Records histogram each time app launches

**Comment by hffvld** [comment]
Confirmed with @kylehickinson this issue can't be verified by QA at this moment. 

**REASON:** `Histogram (p3a) logs` can be seen in the `Nightly` build only, but at the same time `Nightly` can't be set as the `default` browser. So, we must wait for `brave://histograms` to be available in the `Release` build in the web view.

This is technically already in `1.63` and was uplifted via https://github.com/brave/brave-core/pull/21899, however, it cannot be checked using the `Release` builds due to not having the `debug` menu and can't use either `brave://histograms/` & `brave://local-state/`.

Updating the issue to `QA/No` and cc @kjozwiak
