### ISSUE TITLE
Provide More Granular Photo Access

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#903]
### Description: 

Starting in iOS 11, Apple has provided a write-only photo permissions. We should support this, even if never prompted (e.g. only a native Photos permission). This is supported in other browsers (e.g. FF)

### Steps to Reproduce 
  1. Go into Device Settings (_not_ Brave settings)
  2. Select Brave from app list
  3. Select Photos
  1. Select "Add Photos Only"

**Comment by magicwave** [comment]
In the described **Steps to Reproduce**, on my iPhone 7, iOS 12 I could not find Photos in the Brave panel from the apps list.

The version I'm running is the 1368a45236978a1d91342ecb5585fb4d2b5efa5a commit of the development branch, built to device with Xcode.

On iOS 12+ I think the Device path should be:
**Settings > Privacy > Photos > Brave**

However I am unable to verify that; there are 3rd party apps in the list but Brave is not among them. Maybe it's because Brave hasn't asked for access permissions to Photos yet, but I can't figure out how to have the Brave app prompt for them.

**Comment by iccub** [comment]
iOS 13 handles this automatically, so we only need to change iOS 12 behavior
@Brandon-T please correct me if I'm wrong

**Comment by srirambv** [comment]
Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.01.13.17)
- Verified first image save prompts permission to store in Photo app
![image](https://user-images.githubusercontent.com/17010094/72289416-14d7f100-3619-11ea-9397-830d0f9ef997.png)
- Verified selecting OK saves the image
- Verified selecting `Don't Allow` sets permission to `Never` 
- Verified when set to never shows the following prompt
![image](https://user-images.githubusercontent.com/17010094/72289431-1d302c00-3619-11ea-8810-b376a29f703e.png)
----------------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.01.13.17)
- Verified first image save prompts permission to store in Photo app
![image](https://user-images.githubusercontent.com/17010094/72289482-39cc6400-3619-11ea-8a4f-26e25e737fdc.png)
- Verified selecting OK saves the image
- Verified selecting `Don't Allow` sets permission to `Never` 
- Verified when set to never shows the following prompt
![image](https://user-images.githubusercontent.com/17010094/72289456-2caf7500-3619-11ea-9f62-161a9a8c2892.png)
-----

- Logged #2191 for iOS 13
